### ISSUE TITLE
Unable to start Jooby App on JDK 1.8_162

### ISSUE THREAD

**Issue by Rdebokx** [jooby-project/jooby#1033]
After installing the latest JDK 8 (update 162) I'm no longer able to start my Jooby application.

Steps to reproduce:
1. Create a new project using `mvn archetype:generate -B -DgroupId=com.mycompany -DartifactId=my-app -Dversion=1.0-SNAPSHOT -DarchetypeArtifactId=jooby-archetype -DarchetypeGroupId=org.jooby -DarchetypeVersion=1.2.3`

2. Start the application using `jooby:run`

```
Roys-MacBook-Pro:my-app Rdebokx$ mvn jooby:run
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jooby-maven-plugin:1.2.3:run (default-cli) > test-compile @ my-app >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce.versions) @ my-app ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ my-app ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ my-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/rdebokx/Desktop/my-app/src/main/resources
[INFO] Copying 0 resource
[INFO] skip non existing resourceDirectory /Users/rdebokx/Desktop/my-app/src/main/resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ my-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/rdebokx/Desktop/my-app/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ my-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/rdebokx/Desktop/my-app/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ my-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/rdebokx/Desktop/my-app/target/test-classes
[INFO] 
[INFO] <<< jooby-maven-plugin:1.2.3:run (default-cli) < test-compile @ my-app <<<
[INFO] 
[INFO] 
[INFO] --- jooby-maven-plugin:1.2.3:run (default-cli) @ my-app ---
>>> jooby:run[info|main]: Hotswap available on: [/Users/rdebokx/Desktop/my-app]
>>> jooby:run[info|main]:   includes: [**/*.class:**/*.conf:**/*.properties]
>>> jooby:run[info|main]:   excludes: []
>>> jooby:run[error|Hotswap]: com.mycompany.App.start() resulted in error
javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory not found
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:200)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
	at jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:235)
	at jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:78)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:319)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:254)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:480)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:487)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:357)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:292)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.<init>(XMLSchemaFactory.java:97)
	at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:232)
	at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:146)
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:213)
	at __redirected.__SchemaFactory.<clinit>(__SchemaFactory.java:65)
	at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:94)
	at org.jboss.modules.Module$1.run(Module.java:136)
	at org.jboss.modules.Module$1.run(Module.java:123)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.Module.<clinit>(Module.java:123)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:484)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:390)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:283)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:271)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:425)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: __redirected/__SAXParserFactory
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
	... 31 more

```

Tested on both OSX and Windows.
OSX Platform specs:
```
Roys-MacBook-Pro:my-app Rdebokx$ mvn -v
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: en_NL, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"
Roys-MacBook-Pro:my-app Rdebokx$ 
```

Windows specs:
```
C:\Users\roy_d\Desktop\my-app>mvn -v
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: C:\apache-maven-3.5.2\bin\..
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_162\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
Note that there are slight differences between the two platforms, however both result in the same error. I did not encounter any issues with JDK 1.8.0_144

Can this please be investigated? A workaround other than installing an older version of java would be desirable.

**Comment by jknack** [comment]
Fixed in master. Going to release it soon. See #990 for a workaround

**Comment by Rdebokx** [comment]
Thank you!

**Comment by jknack** [comment]
Thank you for using Jooby. Please support us by starring the project!
