### ISSUE TITLE
Unable to create Channel from class class io.netty.channel.epoll.EpollServerSocketChannel

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1114]
Hi, 

Upgrading to 1.4 and encountered an issue with jooby.

```
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.epoll.EpollServerSocketChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:283)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:279)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:261)
	at org.jooby.internal.netty.NettyServer.bootstrap(NettyServer.java:306)
	at org.jooby.internal.netty.NettyServer.start(NettyServer.java:280)
	at org.jooby.Jooby.start(Jooby.java:2221)
	at org.jooby.Jooby.start(Jooby.java:2163)
	at org.jooby.Jooby.run(Jooby.java:2094)
	at co.zeekit.server.App.main(App.java:277)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	... 10 common frames omitted
Caused by: java.lang.NoSuchMethodError: io.netty.util.ResourceLeakDetector.addExclusions(Ljava/lang/Class;[Ljava/lang/String;)V
	at io.netty.buffer.AbstractByteBufAllocator.<clinit>(AbstractByteBufAllocator.java:34)
	at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:82)
	at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24)
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:56)
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:69)
	at io.netty.channel.epoll.EpollChannelConfig.<init>(EpollChannelConfig.java:32)
	at io.netty.channel.epoll.EpollServerChannelConfig.<init>(EpollServerChannelConfig.java:40)
	at io.netty.channel.epoll.EpollServerSocketChannelConfig.<init>(EpollServerSocketChannelConfig.java:34)
	at io.netty.channel.epoll.EpollServerSocketChannel.<init>(EpollServerSocketChannel.java:44)
	... 15 common frames omitted
```

**Comment by aclowkey** [comment]
@jknack  I figured it out, I changed jooby version but not the version property, so the jooby-netty mismatched the jooby version.

**Comment by jknack** [comment]
happened to me too... not sure why Maven doesn't fix this!
