### ISSUE TITLE
ModuleLoadException: Error loading module from module.xml

### ISSUE THREAD

**Issue by vbauer** [jooby-project/jooby#112]
I've just created project from archetype (http://jooby.org/quickstart/) and got the following exception (after `mvn:run`):

```
Hotswap available on: [/Users/vbauer/Documents/workspace/java/my-app/public, /Users/vbauer/Documents/workspace/java/my-app/config, /Users/vbauer/Documents/workspace/java/my-app/target/classes]
  includes: [**/*.class,**/*.conf,**/*.properties]
  excludes: []
Error found while starting: com.mycompany.App
org.jboss.modules.ModuleLoadException: Error loading module from /Users/vbauer/Documents/workspace/java/my-app/target/jboss-modules/com/mycompany/my-app/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:127)
	at org.jboss.modules.LocalModuleFinder$1.run(LocalModuleFinder.java:150)
	at org.jboss.modules.LocalModuleFinder$1.run(LocalModuleFinder.java:144)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:144)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:234)
	at org.jooby.hotreload.AppModule.lambda$startApp$1(AppModule.java:138)
	at org.jooby.hotreload.AppModule$$Lambda$3/684874119.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jooby:jooby:0.5.3' (position: END_TAG seen ...../../../classes" />\n    <artifact name="org.jooby:jooby:0.5.3" />... @7:46) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:748)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:643)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:441)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:260)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	... 14 more
```

Content of the `module.xml` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="com.mycompany.my-app">
  <resources>
    <resource-root path="../../../../../../public" />
    <resource-root path="../../../../../../config" />
    <resource-root path="../../../../../classes" />
    <artifact name="org.jooby:jooby:0.5.3" />
    <artifact name="org.slf4j:slf4j-api:1.7.7" />
    <artifact name="com.typesafe:config:1.2.1" />
    <artifact name="org.ow2.asm:asm:5.0.3" />
    <artifact name="com.google.guava:guava:18.0" />
    <artifact name="com.google.inject.extensions:guice-multibindings:4.0-beta5" />
    <artifact name="com.google.inject:guice:4.0-beta5" />
    <artifact name="javax.inject:javax.inject:1" />
    <artifact name="aopalliance:aopalliance:1.0" />
    <artifact name="org.jooby:jooby-netty:0.5.3" />
    <artifact name="io.netty:netty-codec-http:4.0.27.Final" />
    <artifact name="io.netty:netty-codec:4.0.27.Final" />
    <artifact name="io.netty:netty-transport:4.0.27.Final" />
    <artifact name="io.netty:netty-handler:4.0.27.Final" />
    <artifact name="io.netty:netty-buffer:4.0.27.Final" />
    <artifact name="io.netty:netty-common:4.0.27.Final" />
    <artifact name="org.javassist:javassist:3.19.0-GA" />
    <artifact name="org.jooby:jooby-servlet:0.5.3" />
    <artifact name="javax.servlet:javax.servlet-api:3.1.0" />
    <artifact name="ch.qos.logback:logback-classic:1.1.2" />
    <artifact name="ch.qos.logback:logback-core:1.1.2" />
    <artifact name="junit:junit:4.11" />
    <artifact name="org.hamcrest:hamcrest-core:1.3" />
  </resources>
</module>
```

**Comment by jknack** [comment]
just tried it and it works, can I see the pom.xml? or you didn't touch it?

**Comment by vbauer** [comment]
Actually I didn't touch anything, just run this commands from the "quickstart":

```bash
mvn archetype:generate -B -DgroupId=com.mycompany -DartifactId=my-app -Dversion=1.0-SNAPSHOT -DarchetypeArtifactId=jooby-archetype -DarchetypeGroupId=org.jooby -DarchetypeVersion=0.5.3
cd my-app
mvn jooby:run
```

**Comment by jknack** [comment]
yea, me too. Ok will clean up my local dependencies and try again

**Comment by jknack** [comment]
I wipeout my maven repository, try from scratch and it worked.

 check your local maven repository and see if 0.5.3 has been download it correctly, or even better, delete it and try again.

sometimes maven leaves the repository in a bad state.

**Comment by vbauer** [comment]
I've just checked it on Linux machine and everything is fine. I'll try to check it on OS X again in the nearest future. It looks like you were right. The root of this problem was in the local Maven repository.
