### ISSUE TITLE
Problem upgrade to jooby 1.4 and pac4j2

### ISSUE THREAD

**Issue by martinfluchmfmfmf** [jooby-project/jooby#1128]
Hi, 

after recoding my authentication functions to support pac4j2 i'm facing an error after successful login and call to my test-function /profiletest (see below).

I already checked if the session is correctly in the hazelcast sessionstore, and yes - it's there. My log shows the successful stop of the authenticator function.   

 Any hint what it could be? 

```
1) Error in custom provider, com.google.inject.OutOfScopeException: Key[type=org.pac4j.core.profile.CommonProfile, annotation=[none]]
  at org.jooby.pac4j.Pac4j.lambda$null$1(Pac4j.java:623)
  at org.jooby.pac4j.Pac4j.lambda$null$1(Pac4j.java:623)
  while locating org.pac4j.core.profile.CommonProfile
```

The implementation is a follows

in my app.java

```
...
	use(new Hcast());
	session(HcastSessionStore.class);
...

UsersWebFunctions mfuserswebinstance = new UsersWebFunctions();
use(mfuserswebinstance);

use(new Pac4j()
				.client( "/p/**",conf -> { return new FormClient("/login", new MyUserPasswdAuthenticator(mfuserswebinstance)); })); 

...

get("/profiletest", (req,rsp) ->{
				CommonProfile test=req.require(CommonProfile.class);
				log.info("profiletest={}",test.toString());
		});

```
the authenticator 

```
@Override
	public void validate(final UsernamePasswordCredentials credentials, final WebContext context)
			throws HttpAction, CredentialsException {
		if (credentials == null) {
			throwsException("No credential");
		}

		String username = credentials.getUsername();
		String password = credentials.getPassword();
		log.info("AuthRequest");
		if (CommonHelper.isBlank(username)) {
			throwsException("Username cannot be blank");
		}

		if (CommonHelper.isBlank(password)) {
			throwsException("Password cannot be blank");
		}

		Mfuser u = um.findByUserPass(username, password);
		if (u == null) {
			throwsException("Username : '" + username + "' does not match password");
		}

		final CommonProfile profile = new CommonProfile();

		profile.setId(username);
		profile.addAttribute(Pac4jConstants.USERNAME, username);
		profile.addAttribute(CommonProfileDefinition.DISPLAY_NAME, username);
		profile.addAttribute(um.getSessionProfileuserid(), u.getId());
		profile.addAttribute(um.getSessionProfileuser(), u);

		//handle remember me in session
		String rememberme = context.getRequestParameter("rememberme");
		log.info("rememberme=" + rememberme);
		if (rememberme != null && rememberme.equalsIgnoreCase("on")) {
			context.setSessionAttribute(um.getSessionRememberme(), "yes");
			String token = "";
			if (u.getRemembermetoken() == null || u.getRemembermetoken().length() < 9) {
				token = um.createRemembermetoken(u);
			} else {
				token = u.getRemembermetoken();
			}
			Cookie c = new Cookie(um.getCookiename(), token);
			c.setMaxAge(um.getCookiemaxage());
			if (c != null) {
				context.addResponseCookie(c);
			}

		} else {
			context.setSessionAttribute(um.getSessionRememberme(), "no");
		}

		//handle roles in profile 
		String roles = u.getRoles();
		if (roles != null && roles.length() > 0) {
			for (String role : roles.split(",")) {
				profile.addRole(role);
			}
		}
		log.info("authentication successful for {}",username);
		credentials.setUserProfile(profile);
	}
```

**Comment by jknack** [comment]
Hi,

 Can you write an example to reproduce the issue?

 Also the `callback` url is now controlled by the `pac4j.callback.url` property and is set to `/callback`. In pac4j 1.x /Auth module the callback url was controlled by the `auth.callback` property and is set to `/auth`. Make sure the client code uses the `/callback`

**Comment by martinfluchmfmfmf** [comment]
Hi Jknack,

after two hours i was able to isolate the error. Using the pac4j-starter project i only modified the following lines of code

```
    .client("/p/**",conf ->
        {
          return  new FormClient("/login", ((credentials, context) -> {
              // Create default profile:
              String username = ((UsernamePasswordCredentials) credentials).getUsername();
              final CommonProfile profile = new CommonProfile();
              profile.setId(username);
              profile.addAttribute(Pac4jConstants.USERNAME, username);
              profile.addAttribute(CommonProfileDefinition.DISPLAY_NAME, username);
              credentials.setUserProfile(profile);
            }));
        }
        ));
```

in the old version i used this code to protect everything below the path /p and that worked pretty good. when i change the code i immediatly get the same error message as described above..

```
com.google.inject.ProvisionException: Unable to provision, see the following errors:


1) Error in custom provider, com.google.inject.OutOfScopeException: Key[type=org.pac4j.core.profile.UserProfile, annotation=[none]]

at org.jooby.pac4j.Pac4j.lambda$null$1(Pac4j.java:623)

at org.jooby.pac4j.Pac4j.lambda$null$1(Pac4j.java:623)

while locating org.pac4j.core.profile.UserProfile


1 error

at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)

at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)

at org.jooby.Jooby.require(Jooby.java:1205)

at org.jooby.Registry.require(Registry.java:233)

at starter.pac4j.App.lambda$new$6(App.java:69)

at org.jooby.Route$ZeroArgHandler.handle(Route.java:2297)

at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)

at org.jooby.internal.RouteChain.next(RouteChain.java:262)

at org.jooby.Route$Chain.next(Route.java:2609)

at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)

at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)

at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)

at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)

at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)

at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

at java.lang.Thread.run(Thread.java:748)

Caused by: com.google.inject.OutOfScopeException: Key[type=org.pac4j.core.profile.UserProfile, annotation=[none]]

at org.jooby.scope.Providers.lambda$outOfScope$0(Providers.java:219)

at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)

at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)

at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)

at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)

at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)

at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)

at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)

at org.jooby.internal.RequestScope.lambda$scope$0(RequestScope.java:234)

at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)

at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)

at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)

at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)

... 18 more
```

hope i did not misunderstand the documentation and that you can reproduce it now

Martin

**Comment by jknack** [comment]
I'm afraid the pac4j-starter example works as expected. I tried with pac4j 1.x/2.x and jooby 1.2.0/1.3.0/1.4.0 

If your auth method/client only intercept paths starting with `/p/**` then a request to `/` is going to fails. The error could be better, something like 403

**Comment by martinfluchmfmfmf** [comment]
Ok thanks, but how do I then select only one path/subpath to protect ?

In the documentation I found:

By default Pac4j restrict access to all the routes defined after the Pac4j module. You can specify what url must be protected using a path pattern:
{
  use(new Pac4j()
    .client("/admin/**", conf -> {
      return new FormClient("/login", new SimpleTestSimpleTestUsernamePasswordAuthenticator());
   }));
}
In my config only the path below p should be covered by pac4j

Martin

**Comment by jknack** [comment]
Probably need to change the doc but will be `after the pac4j module` and matches the path. So:

```
use(new Pac4j().client(conf -> {...})
```

Protects all the routes defined after the module. Pattern here is wide/all matches: `/**`

Now:
```
use(new Pac4j().client("/admin/**", conf -> {...});
```

Protects all the routes defined after that starts with `/admin/**`

Here is an example of your use case:

```
    get("/login", () -> Results.html("login"));

    use(new Pac4j()
        .client("/p/**", conf ->
            new FormClient("/login", ((credentials, context) -> {
              // Create default profile:
              String username = ((UsernamePasswordCredentials) credentials).getUsername();
              final CommonProfile profile = new CommonProfile();
              profile.setId(username);
              profile.addAttribute(Pac4jConstants.USERNAME, username);
              profile.addAttribute(CommonProfileDefinition.DISPLAY_NAME, username);
              credentials.setUserProfile(profile);
            }))
        ));

    /** Anonymous access: */
    get("/", () -> {
      return Results.html("anonymous");
    });

    /** Protected pages: */
    get("/p/profile", () -> {
      UserProfile profile = require(UserProfile.class);
      return Results.html("profile").put("profile", profile);
    });
```

Make sense?

**Comment by martinfluchmfmfmf** [comment]
Partly, 

first of all thanks for your help and yes i missed implementing the get("/"...) in the sample and of course the access to "/" works then but my problem with the access to UserProfile is not finally solved. 

my software consists of many different mondules, most of them export pathes below "/p/**", some of them still have to export unprotected pathes from the root.  so my implementation of a client covering the "/p/**" seems to be right as some of the modules exporting public pathes are after the Authentication MOdule. 

When i come to session checking and identifying if the user logged in correctly and has a valid session i use the part in your sample code above which works pretty well: 

```
/** Protected pages: */
   get("/p/profile", () -> {
     UserProfile profile = require(UserProfile.class);
     return Results.html("profile").put("profile", profile);
   });
```

my issue is that i have to check at every page access (the protected and the unprotected ones) if the customer has a valid session, and here is my problem: 

see the example:

```
 get("/", (req,rsp) ->
        {
        String message="/";
        if (req.ifSession().isPresent())
                {
                        message+="sessionpresent;";
                        Map<String,String> sessionattrib=req.session().attributes();
                for (String key:sessionattrib.keySet())
                {
                        message+=key+"="+sessionattrib.get(key)+";";
                }
                }
          log.info("message={}",message);
          if (req.session().isSet("pac4jUserProfiles"))
          {
          UserProfile profile = require(UserProfile.class);
          message+="profile="+profile.toString();
          }
                rsp.send(message);

        });
```

if the user is not logged in and completly new (so no session yet) - message is "/"
if the user logged in the session Information has valid session information
```
[2018-06-20 04:57:07,217]-[netty task-4-1] INFO  starter.pac4j.App - message=/
[2018-06-20 04:57:18,089]-[netty task-4-1] INFO  starter.pac4j.App - message=/sessionpresent;pac4jUserProfiles=b64~rO0ABXNyABdqYXZhLnV0aWwuTGlua2VkSGFzaE1hcDTATlwQbMD7AgABWgALYWNjZXNzT3JkZXJ4cgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAAXQACkZvcm1DbGllbnRzcgAkb3JnLnBhYzRqLmNvcmUucHJvZmlsZS5Db21tb25Qcm9maWxl5j2Ybq91JMsMAAB4cgAib3JnLnBhYzRqLmNvcmUucHJvZmlsZS5Vc2VyUHJvZmlsZX0t4lPmLJbSDAAAeHB0ABJtZkBtYXJ0aW5mbHVjaC5jb21zcQB+AAE/QAAAAAAADHcIAAAAEAAAAAJ0AAxkaXNwbGF5X25hbWVxAH4AB3QACHVzZXJuYW1lcQB+AAd4c3EAfgABP0AAAAAAAAB3CAAAABAAAAAAeHcBAHNyABFqYXZhLnV0aWwuSGFzaFNldLpEhZWWuLc0AwAAeHB3DAAAABA/QAAAAAAAAHhzcQB+AAx3DAAAABA/QAAAAAAAAHhxAH4AA3B4eAA=;FormClient$attemptedAuthentication=;
```
based on that i would assume to get the UserProfile with the proposed UserProfile profile = require(UserProfile.class); but that fails for routes that are not covered via the /p/** client. which seems as it should work, but is no solution for me ;-)

what would you suggest? how can I get the profile if a valid session exists even for routes that are unprotected? consulting profilemanager in a way similar to that
```
	ProfileManager pm = require(ProfileManager.class);
        List<Commonprofile> profiles = pm.getAll(req.ifSession().isPresent());
        find correct profile based on current session information...
```

Martin

**Comment by jknack** [comment]
Finally got the issue:

- login calling something under `/p/*`
- user was logged in 
- try to access to `/`
- you got the ugly exception

 Is this your workflow?

If this is the use case, then you're right a call to `/` should give you the `UserProfile` that was logged in previously.

> is a usage of profilemanager a feasable way

	ProfileManager pm = require(ProfileManager.class);
        List<Commonprofile> profiles = pm.getAll(req.ifSession().isPresent());
        find correct profile based on current session information...

Yes, this is a nice workaround. Also, going to fix the `require()` call to do this.

Cool?
