### ISSUE TITLE
jdbi / jdk10 / mysql database 

### ISSUE THREAD

**Issue by martinfluchmfmfmf** [jooby-project/jooby#1224]
Hi, 

after moving from linux to macos (and Jdk10) i see a strange behavior on startup that can be reproduced with your new java 10 starter project

in app.java
```
   use(new Jdbc());
   use(new Hbm().scan());
```

in application.conf
```
db.url = "jdbc:mysql://192.168.77.81:3306/myapp?zeroDateTimeBehavior=convertToNull"
db.user = myappdbdev
db.password = ****
```

in pom.xml
```
    <dependency>
  <groupId>org.jooby</groupId>
  <artifactId>jooby-jdbc</artifactId>
  <version>1.5.0</version>
</dependency>


<!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.6</version>
</dependency>

    <dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-hbm</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-jdbi</artifactId>
		</dependency>
```

jooby:run results in errors during runtime
```
[2018-07-31 23:30:27,754]-[Hotswap] INFO  com.zaxxer.hikari.HikariDataSource - mysql.myapp - Starting...
[2018-07-31 23:30:38,881]-[Hotswap] INFO  com.zaxxer.hikari.pool.PoolBase - mysql.myapp - Driver does not support get/set network timeout for connections. (null)
[2018-07-31 23:30:39,895]-[Hotswap] WARN  com.zaxxer.hikari.pool.PoolBase - mysql.myapp - Default transaction isolation level detection failed (No operations allowed after connection closed.).
[2018-07-31 23:30:39,896]-[Hotswap] ERROR com.zaxxer.hikari.pool.HikariPool - mysql.myapp - Exception during pool initialization.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.Util.getInstance(Util.java:381)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1098)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.ConnectionImpl.setTransactionIsolation(ConnectionImpl.java:5143)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:424)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:374)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at starter.hello.hello-java10-starter//org.jooby.jdbc.Jdbc.configure(Jdbc.java:539)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.install(Jooby.java:3431)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$bindService$50(Jooby.java:3092)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$null$44(Jooby.java:2942)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Try.run(Try.java:729)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2929)
	at starter.hello.hello-java10-starter//com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at starter.hello.hello-java10-starter//com.google.inject.spi.Elements.getElements(Elements.java:103)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at starter.hello.hello-java10-starter//com.google.inject.Guice.createInjector(Guice.java:87)
	at starter.hello.hello-java10-starter//com.google.inject.Guice.createInjector(Guice.java:78)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$new$0(Jooby.java:884)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.bootstrap(Jooby.java:3006)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.start(Jooby.java:2205)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.start(Jooby.java:2186)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.run(Jooby.java:2115)
	at starter.hello.hello-java10-starter//starter.hello.App.main(App.java:242)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:440)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Juli 31, 2018 11:30:39 NACHM. com.google.inject.internal.MessageProcessor visit
INFORMATION: An exception was caught and reported. Message: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: No operations allowed after connection closed.
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:576)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:555)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at starter.hello.hello-java10-starter//org.jooby.jdbc.Jdbc.configure(Jdbc.java:539)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.install(Jooby.java:3431)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$bindService$50(Jooby.java:3092)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$null$44(Jooby.java:2942)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Try.run(Try.java:729)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2929)
	at starter.hello.hello-java10-starter//com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at starter.hello.hello-java10-starter//com.google.inject.spi.Elements.getElements(Elements.java:103)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at starter.hello.hello-java10-starter//com.google.inject.Guice.createInjector(Guice.java:87)
	at starter.hello.hello-java10-starter//com.google.inject.Guice.createInjector(Guice.java:78)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$new$0(Jooby.java:884)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.bootstrap(Jooby.java:3006)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.start(Jooby.java:2205)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.start(Jooby.java:2186)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.run(Jooby.java:2115)
	at starter.hello.hello-java10-starter//starter.hello.App.main(App.java:242)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:440)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.Util.getInstance(Util.java:381)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1098)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.ConnectionImpl.setTransactionIsolation(ConnectionImpl.java:5143)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:424)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:374)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	... 37 more

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (jar:file:/Users/martinfluch/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2018-07-31 23:30:40,001]-[Hotswap] INFO  starter.hello.App - Stopped
[2018-07-31 23:30:40,004]-[Hotswap] ERROR starter.hello.App - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.jooby.spi.HttpHandler was bound.
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.netty.NettyServer.<init>(NettyServer.java:261)
  at starter.hello.hello-java10-starter//org.jooby.netty.Netty.configure(Netty.java:221)

2) An exception was caught and reported. Message: Failed to initialize pool: No operations allowed after connection closed.
  at starter.hello.hello-java10-starter//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)

2 errors
	at starter.hello.hello-java10-starter//com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at starter.hello.hello-java10-starter//com.google.inject.Guice.createInjector(Guice.java:87)
	at starter.hello.hello-java10-starter//com.google.inject.Guice.createInjector(Guice.java:78)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$new$0(Jooby.java:884)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.bootstrap(Jooby.java:3006)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.start(Jooby.java:2205)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.start(Jooby.java:2186)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.run(Jooby.java:2115)
	at starter.hello.hello-java10-starter//starter.hello.App.main(App.java:242)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:440)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: No operations allowed after connection closed.
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:576)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:555)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at starter.hello.hello-java10-starter//org.jooby.jdbc.Jdbc.configure(Jdbc.java:539)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.install(Jooby.java:3431)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$bindService$50(Jooby.java:3092)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$null$44(Jooby.java:2942)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at starter.hello.hello-java10-starter//org.jooby.funzy.Try.run(Try.java:729)
	at starter.hello.hello-java10-starter//org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2929)
	at starter.hello.hello-java10-starter//com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at starter.hello.hello-java10-starter//com.google.inject.spi.Elements.getElements(Elements.java:103)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at starter.hello.hello-java10-starter//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 18 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.Util.getInstance(Util.java:381)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1098)
	at starter.hello.hello-java10-starter//com.mysql.jdbc.ConnectionImpl.setTransactionIsolation(ConnectionImpl.java:5143)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:424)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:374)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at starter.hello.hello-java10-starter//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	... 37 common frames omitted
```

any idea what's wrong? mysql responds in a correct way when I test with nc 192.168.77.81 3306

Martin

**Comment by jknack** [comment]
Hi,

You have a connection problem. Just try [hello-java10-starter](https://github.com/jooby-project/hello-java10-starter) with:

```java
    use(new Jdbc());

    use(new Jdbi3());

    onStart(() -> {
      require(Jdbi.class).useTransaction(h -> {
        System.out.println(h.createQuery("select * from users").mapToMap().list());
      });
    });
```

and it works. Here is the output:

```
[INFO] --- jooby-maven-plugin:1.4.1:run (default-cli) @ hello-java10-starter ---
>>> jooby:run[info|main]: Hotswap available on: [/Users/edgar/Source/hello-java10-starter]
>>> jooby:run[info|main]:   includes: [**/*.class:**/*.conf:**/*.properties]
>>> jooby:run[info|main]:   excludes: []
[2018-08-01 09:59:15,297]-[Hotswap] INFO  com.zaxxer.hikari.HikariDataSource - mysql.hello - Starting...
[2018-08-01 09:59:15,587]-[Hotswap] INFO  com.zaxxer.hikari.HikariDataSource - mysql.hello - Start completed.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (jar:file:/Users/edgar/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[{name=Mr. T}]
[2018-08-01 09:59:16,037]-[Hotswap] INFO  starter.hello.App - [dev@netty]: Server started in 1320ms

  GET /    [*/*]     [*/*]    (/anonymous)

listening on:
  http://localhost:8080/
```

**Comment by martinfluchmfmfmf** [comment]
Thanks, after further investigation i was able to remove the problem by changing mysql client to mariadb client - though there is no difference but with the mariadb mvn plugin everything works fine.

martin
