### ISSUE TITLE
ApiTool breaks when running on jdk10

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#1236]
The `swagger` extensions tries to use a class that was removed from the `java.base` module

```
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlRootElement
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
  ...
```

_I think_ that updating the swagger dependency will fix the issue.

**Comment by Daniel-Dos** [comment]
Hello, 

currently the apitool is being compiled with Java 8.

as you are running with java 10/11 it jaxb is not really in JDK.

to get around this has two options:

1 - use --add-modules  java.xml.bind

2- add the dependencies in the pom.xml of your project

see here in this link: 

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j
