### ISSUE TITLE
Assets bug occur when start application.

### ISSUE THREAD

**Issue by mozhok** [jooby-project/jooby#1245]
Hello! I am japanese. I can understand little english, sorry if wrong grammar.

I am suffering from asset bugs. Using version 1.5.1 of Jooby with Gradle.
Bug occur when start application.

Assets config (in application.conf)
`assets {
  fileset {
    core: [
      stylesheets/style.css
    ]
  }
  pipeline {
    dev: []
    dist: []
  }
}`

Error
`java.lang.NoClassDefFoundError: com/eclipsesource/v8/V8Value
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.jooby.assets.AssetCompiler.engineFactory(AssetCompiler.java:812)
	at org.jooby.assets.AssetCompiler.<init>(AssetCompiler.java:294)
	at org.jooby.assets.Assets.configure(Assets.java:505)
	at org.jooby.Jooby.install(Jooby.java:3425)
	at org.jooby.Jooby.lambda$bindService$47(Jooby.java:3083)
	at org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at org.jooby.Jooby.lambda$null$41(Jooby.java:2932)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at org.jooby.funzy.Try.run(Try.java:729)
	at org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2918)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at org.jooby.Jooby.lambda$new$0(Jooby.java:885)
	at org.jooby.Jooby.bootstrap(Jooby.java:2996)
	at org.jooby.Jooby.start(Jooby.java:2197)
	at org.jooby.Jooby.start(Jooby.java:2178)
	at org.jooby.Jooby.run(Jooby.java:2107)
	at org.jooby.JoobyKt.run(Jooby.kt:116)
	at net.bdfps.api.web.App.main(Application.kt:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:444)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.eclipsesource.v8.V8Value from [Module "app" from AppModuleLoader@6167ee46 for finders []]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 42 common frames omitted`

**Comment by jknack** [comment]
Hi,

 You need to make sure to add a j2v8 for your operating system. This is done automatically for Maven, but (unfortunately) not for Gradle :( (I'm not a gradle user).

Here is an example for netty-epoll:

https://github.com/jooby-project/gradle-starter/blob/master/build.gradle

You need to do something similar for j2v8:

https://github.com/jooby-project/jooby/blob/master/modules/jooby-assets-j2v8/pom.xml#L33-L112

**Comment by mozhok** [comment]
I solved this problem. Thank you.
