### ISSUE TITLE
Bot requests sometime ends up as http 500 with error logging.

### ISSUE THREAD

**Issue by stoyle** [jooby-project/jooby#1259]
Version org.jooby:jooby-netty:1.5.1

Stack trace:
```
     | Method | Path  | Source   | Name | Pattern | Consumes | Produces |
      |--------|-------|----------|------|---------|----------|----------|
      | GET    | (X11; | ~builtin | 404  | (X11;   | [*/*]    | [*/*]    |

Stacktrace:
org.jooby.Err: Server Error(500)
	at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:589)
	at org.jooby.internal.HttpHandlerImpl.cleanup(HttpHandlerImpl.java:562)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:504)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:492)
	... 9 common frames omitted
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1837)
	at org.jooby.internal.RoutePattern$1.apply(RoutePattern.java:390)
	at org.jooby.internal.RoutePattern$1.apply(RoutePattern.java:383)
	at org.jooby.internal.RoutePattern.matcher(RoutePattern.java:300)
	at org.jooby.Route$Definition.matches(Route.java:1183)
	at org.jooby.internal.HttpHandlerImpl.findRoutes(HttpHandlerImpl.java:643)
	at org.jooby.internal.HttpHandlerImpl.routes(HttpHandlerImpl.java:611)
	at org.jooby.internal.HttpHandlerImpl.access$400(HttpHandlerImpl.java:259)
	at org.jooby.internal.HttpHandlerImpl$1.load(HttpHandlerImpl.java:722)
	at org.jooby.internal.HttpHandlerImpl$1.load(HttpHandlerImpl.java:719)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
... 14 common frames omitted
```

I guess the problem is in `org/jooby/internal/RoutePattern.java:389`, where it requires a `/` in the path, but where there isn't one.

Not sure what the fix would be, perhaps a `IgnoredRouteMatcher` or something like that. But at least it needs to check that there actually is a / in the path.

Best regards,
Alf Kristian

**Comment by jknack** [comment]
we need to silently ignore these requests and resolve them as 404
