### ISSUE TITLE
Async handler with response parameter gives unsupported content type error

### ISSUE THREAD

**Issue by rrva** [jooby-project/jooby#1270]
Given the following small working Jooby app:

```kotlin
object App {

    private val objectMapper = createObjectMapper()

    @JvmStatic
    fun main(args: Array<String>) {
        org.jooby.run(*args) {
            use(Jackson(objectMapper))
            map(AsyncMapper())

            post("/query") { req ->
                val body = objectMapper.readValue(req.body().value, Request::class.java)
                executeAsync(body)
            }

        }
    }

    private fun executeAsync(req: Request): CompletableFuture<ExecutionResult> {
        return CompletableFuture.supplyAsync { ExecutionResult(result = req.query) }
    }

    data class Request(val query: String)
    data class ExecutionResult(val result: String)
}


fun createObjectMapper(): ObjectMapper {
    return ObjectMapper().apply {
        registerKotlinModule()
    }
}
```

If I change the request handler accept a response parameter in order to modify response headers:

```kotlin
post("/query") { req, rsp ->
                val body = objectMapper.readValue(req.body().value, Request::class.java)
                rsp.header("Foo", "Bar")
                executeAsync(body)
            }
```

The app starts responding HTTP 415:

```
org.jooby.Err: Unsupported Media Type(415): application/json
	at org.jooby.internal.HttpHandlerImpl.handle406or415(HttpHandlerImpl.java:699)
	at org.jooby.internal.HttpHandlerImpl.lambda$routes$9(HttpHandlerImpl.java:616)
	at org.jooby.internal.FallbackRoute.handle(FallbackRoute.java:303)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2475)
	at org.jooby.Route$Handler.handle(Route.java:2073)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2475)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:271)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

What is a working way to be able to modify outgoing response headers and still be fully async in the processing and writing of the response?

**Comment by rrva** [comment]
I solved this with an `after` handler and used the form of request handler which does not require access to the `Response` object. Closing.

```kotlin
after("POST", "/query") {
                req, rsp, result ->
                rsp.header("Foo", "Bar")
                result
            }
```
