### ISSUE TITLE
NullpointerException with Hibernate

### ISSUE THREAD

**Issue by martinbe1io** [jooby-project/jooby#1277]
Hi

my software runs Jooby on MacOs with Hbm Module without any problems. Java Version is
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

trying to run same software on linux returns an error which can be easily reproduced using the Jooby-hibernate-starter project from GitHub: https://github.com/jooby-project/hibernate-starter (see below)

java version on linux host
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

Already included the line <java.source.version>11</java.source.version> in pom.xml. 

errors thrown:

```
hibernate-starter$ mvn jooby:run
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -------------------< starter.jdbi:hibernate-starter >-------------------
[INFO] Building hibernate-starter 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> jooby-maven-plugin:1.5.1:run (default-cli) > test-compile @ hibernate-starter >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce.versions) @ hibernate-starter ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ hibernate-starter ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (add-querydsl-source) @ hibernate-starter ---
[INFO] Source directory: /home/mf/jooby/hibernate-starter/target/generated-sources added.
[INFO] 
[INFO] --- apt-maven-plugin:1.1.3:process (default) @ hibernate-starter ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ hibernate-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/mf/jooby/hibernate-starter/src/main/resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ hibernate-starter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/mf/jooby/hibernate-starter/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ hibernate-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/mf/jooby/hibernate-starter/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ hibernate-starter ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< jooby-maven-plugin:1.5.1:run (default-cli) < test-compile @ hibernate-starter <<<
[INFO] 
[INFO] 
[INFO] --- jooby-maven-plugin:1.5.1:run (default-cli) @ hibernate-starter ---
>>> jooby:run[info|main]: Hotswap available on: [/home/mf/jooby/hibernate-starter]
>>> jooby:run[info|main]:   includes: [**/*.class:**/*.conf:**/*.properties]
>>> jooby:run[info|main]:   excludes: []
[2018-12-12 23:12:43,270]-[Hotswap] INFO  com.zaxxer.hikari.HikariDataSource - h2.1544652763223 - Starting...
[2018-12-12 23:12:43,574]-[Hotswap] INFO  com.zaxxer.hikari.HikariDataSource - h2.1544652763223 - Start completed.
[2018-12-12 23:12:43,780]-[Hotswap] INFO  org.hibernate.Version - HHH000412: Hibernate Core {5.2.1.Final}
[2018-12-12 23:12:43,789]-[Hotswap] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
[2018-12-12 23:12:43,791]-[Hotswap] INFO  org.hibernate.cfg.Environment - HHH000021: Bytecode provider name : javassist
[2018-12-12 23:12:43,897]-[Hotswap] INFO  org.hibernate.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
[2018-12-12 23:12:44,075]-[Hotswap] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Dez. 12, 2018 11:12:45 NACHM. com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.NullPointerException
org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at starter.jdbi.hibernate-starter//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at starter.jdbi.hibernate-starter//org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:128)
	at starter.jdbi.hibernate-starter//org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:296)
	at starter.jdbi.hibernate-starter//org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:483)
	at starter.jdbi.hibernate-starter//org.jooby.hbm.Hbm.configure(Hbm.java:796)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.install(Jooby.java:3425)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$bindService$47(Jooby.java:3083)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$null$41(Jooby.java:2932)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Try.run(Try.java:729)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2918)
	at starter.jdbi.hibernate-starter//com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at starter.jdbi.hibernate-starter//com.google.inject.spi.Elements.getElements(Elements.java:103)
	at starter.jdbi.hibernate-starter//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at starter.jdbi.hibernate-starter//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at starter.jdbi.hibernate-starter//com.google.inject.Guice.createInjector(Guice.java:87)
	at starter.jdbi.hibernate-starter//com.google.inject.Guice.createInjector(Guice.java:78)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$new$0(Jooby.java:885)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.bootstrap(Jooby.java:2996)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.start(Jooby.java:2197)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.start(Jooby.java:2178)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.run(Jooby.java:2107)
	at starter.jdbi.hibernate-starter//starter.hbm.App.main(App.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:444)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:91)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:116)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:382)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:510)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:124)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
	... 39 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:88)
	... 48 more
Caused by: java.lang.NullPointerException
	at starter.jdbi.hibernate-starter//javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:131)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:530)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:515)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:451)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:422)
	at starter.jdbi.hibernate-starter//org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:72)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:158)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
	... 53 more

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (jar:file:/home/mf/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2018-12-12 23:12:45,538]-[Hotswap] INFO  starter.hbm.App - Stopped
[2018-12-12 23:12:45,550]-[Hotswap] ERROR starter.hbm.App - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.jooby.spi.HttpHandler was bound.
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.netty.NettyServer.<init>(NettyServer.java:261)
  at starter.jdbi.hibernate-starter//org.jooby.netty.Netty.configure(Netty.java:221)

2) An exception was caught and reported. Message: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
  at starter.jdbi.hibernate-starter//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)

2 errors
	at starter.jdbi.hibernate-starter//com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at starter.jdbi.hibernate-starter//com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at starter.jdbi.hibernate-starter//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at starter.jdbi.hibernate-starter//com.google.inject.Guice.createInjector(Guice.java:87)
	at starter.jdbi.hibernate-starter//com.google.inject.Guice.createInjector(Guice.java:78)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$new$0(Jooby.java:885)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.bootstrap(Jooby.java:2996)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.start(Jooby.java:2197)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.start(Jooby.java:2178)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.run(Jooby.java:2107)
	at starter.jdbi.hibernate-starter//starter.hbm.App.main(App.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:444)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at starter.jdbi.hibernate-starter//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at starter.jdbi.hibernate-starter//org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:128)
	at starter.jdbi.hibernate-starter//org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:296)
	at starter.jdbi.hibernate-starter//org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:483)
	at starter.jdbi.hibernate-starter//org.jooby.hbm.Hbm.configure(Hbm.java:796)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.install(Jooby.java:3425)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$bindService$47(Jooby.java:3083)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$null$41(Jooby.java:2932)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at starter.jdbi.hibernate-starter//org.jooby.funzy.Try.run(Try.java:729)
	at starter.jdbi.hibernate-starter//org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2918)
	at starter.jdbi.hibernate-starter//com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at starter.jdbi.hibernate-starter//com.google.inject.spi.Elements.getElements(Elements.java:103)
	at starter.jdbi.hibernate-starter//com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at starter.jdbi.hibernate-starter//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 18 common frames omitted
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:91)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:116)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:382)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:510)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:124)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at starter.jdbi.hibernate-starter//org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
	... 39 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:88)
	... 48 common frames omitted
Caused by: java.lang.NullPointerException: null
	at starter.jdbi.hibernate-starter//javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:131)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:530)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:515)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:451)
	at starter.jdbi.hibernate-starter//javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:422)
	at starter.jdbi.hibernate-starter//org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:72)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:158)
	at starter.jdbi.hibernate-starter//org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
	... 53 common frames omitted

```

any idea what the issue is? maybe similar to this topic https://hibernate.atlassian.net/browse/HHH-12924 ?

Martin

**Comment by jknack** [comment]
looks like a hibernate issue :S

add this to your pom properties:

`<hibernate.version>5.3.5.Final</hibernate.version>`

and try again

**Comment by martinbe1io** [comment]
No another error occurs 

‘‘‘
ERROR] execute error
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated
    at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    at java.util.concurrent.FutureTask.get (FutureTask.java:191)
    at com.mysema.maven.apt.AbstractProcessorMojo.execute (AbstractProcessorMojo.java:346)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions (MojoExecutor.java:353)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:198)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated
    at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions (JavacTaskImpl.java:163)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall (JavacTaskImpl.java:100)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:94)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Generated
    at com.querydsl.codegen.EntitySerializer.introImports (EntitySerializer.java:423)
    at com.querydsl.codegen.EntitySerializer.intro (EntitySerializer.java:269)
    at com.querydsl.codegen.EntitySerializer.serialize (EntitySerializer.java:594)
    at com.querydsl.apt.AbstractQuerydslProcessor.serialize (AbstractQuerydslProcessor.java:574)
    at com.querydsl.apt.AbstractQuerydslProcessor.serializeMetaTypes (AbstractQuerydslProcessor.java:513)
    at com.querydsl.apt.AbstractQuerydslProcessor.process (AbstractQuerydslProcessor.java:94)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor (JavacProcessingEnvironment.java:972)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs (JavacProcessingEnvironment.java:888)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run (JavacProcessingEnvironment.java:1214)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing (JavacProcessingEnvironment.java:1326)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations (JavaCompiler.java:1258)
    at com.sun.tools.javac.main.JavaCompiler.compile (JavaCompiler.java:936)
    at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0 (JavacTaskImpl.java:104)
    at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions (JavacTaskImpl.java:147)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall (JavacTaskImpl.java:100)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:94)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
    at java.net.URLClassLoader.findClass (URLClassLoader.java:471)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:588)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:521)
    at com.querydsl.codegen.EntitySerializer.introImports (EntitySerializer.java:423)
    at com.querydsl.codegen.EntitySerializer.intro (EntitySerializer.java:269)
    at com.querydsl.codegen.EntitySerializer.serialize (EntitySerializer.java:594)
    at com.querydsl.apt.AbstractQuerydslProcessor.serialize (AbstractQuerydslProcessor.java:574)
    at com.querydsl.apt.AbstractQuerydslProcessor.serializeMetaTypes (AbstractQuerydslProcessor.java:513)
    at com.querydsl.apt.AbstractQuerydslProcessor.process (AbstractQuerydslProcessor.java:94)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor (JavacProcessingEnvironment.java:972)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs (JavacProcessingEnvironment.java:888)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run (JavacProcessingEnvironment.java:1214)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing (JavacProcessingEnvironment.java:1326)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations (JavaCompiler.java:1258)
    at com.sun.tools.javac.main.JavaCompiler.compile (JavaCompiler.java:936)
    at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0 (JavacTaskImpl.java:104)
    at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions (JavacTaskImpl.java:147)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall (JavacTaskImpl.java:100)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:94)
    at com.sun.tools.javac.api.JavacTaskImpl.call (JavacTaskImpl.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.906 s
[INFO] Finished at: 2018-12-13T00:30:45+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mysema.maven:apt-maven-plugin:1.1.3:process (default) on project hibernate-starter: java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE

‘‘‘

**Comment by jknack** [comment]
well yea it is a hibenate issue. Revert the hibernate upgrade (remove the `hibernate.version` property)
and add this one: `<javassist.version>3.24.0-GA</javassist.version>`

**Comment by martinbe1io** [comment]
Works, thx
