### ISSUE TITLE
sse and session usage

### ISSUE THREAD

**Issue by martinbe1io** [jooby-project/jooby#1297]
hi, 

I try to use sse with the following code

server side:
```
router.sse("/sse/register", (req, sse) -> {
			
		    log.info("sse register req={} session={}",req.param("m").isSet(),req.ifSession().orElse(null));
		    
		    sse.send("seas");
		  });
```

client side:
```
function enable_sse(location)
{
	console.log("try to enable sse via "+location);
	if(typeof(EventSource) !== "undefined") {
	 
		var source = new EventSource(location);
		source.onmessage = function(event) {
		    //document.getElementById("result").innerHTML += event.data + "<br>";
		    console.log("sse event: "+event.data);
		};
		
	} else {
	    console.log("no see support");
	}	
}
...
enable_sse("/sse/register");
```

I would expect getting the session if present but getting the following error 

```
caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
  at io.be1.circular.my-app//org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2980)
  while locating org.jooby.Response

1 error
	at io.be1.circular.my-app//com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at io.be1.circular.my-app//com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at io.be1.circular.my-app//com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1081)
	at io.be1.circular.my-app//org.jooby.internal.RequestImpl.require(RequestImpl.java:481)
	at io.be1.circular.my-app//org.jooby.Registry.require(Registry.java:233)
	at io.be1.circular.my-app//org.jooby.internal.RequestImpl.ifSession(RequestImpl.java:557)
	at io.be1.circular.my-app//io.be1.circular.dynamicmainmenu.DynamicDashboard.lambda$configurerouter$0(DynamicDashboard.java:728)
	at io.be1.circular.my-app//org.jooby.Sse$Handler.lambda$null$0(Sse.java:616)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at io.be1.circular.my-app//org.jooby.funzy.Try.run(Try.java:729)
	at io.be1.circular.my-app//org.jooby.Sse$Handler.lambda$null$3(Sse.java:616)
	... 4 common frames omitted
Caused by: com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
	at io.be1.circular.my-app//org.jooby.internal.RequestScope.getScopedObjectMap(RequestScope.java:255)
	at io.be1.circular.my-app//org.jooby.internal.RequestScope.lambda$scope$0(RequestScope.java:230)
	at io.be1.circular.my-app//com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at io.be1.circular.my-app//com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 15 common frames omitted
[2019-02-27 22:22:11,904]-[netty task-4-2] ERROR org.jooby.Sse - execution of /sse/register resulted in error
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
  at io.be1.circular.my-app//org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2980)
  while locating org.jooby.Response

1 error
	at io.be1.circular.my-app//com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at io.be1.circular.my-app//com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at io.be1.circular.my-app//com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1081)
	at io.be1.circular.my-app//org.jooby.internal.RequestImpl.require(RequestImpl.java:481)
	at io.be1.circular.my-app//org.jooby.Registry.require(Registry.java:233)
	at io.be1.circular.my-app//org.jooby.internal.RequestImpl.ifSession(RequestImpl.java:557)
	at io.be1.circular.my-app//io.be1.circular.dynamicmainmenu.DynamicDashboard.lambda$configurerouter$0(DynamicDashboard.java:728)
	at io.be1.circular.my-app//org.jooby.Sse$Handler.lambda$null$0(Sse.java:616)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at io.be1.circular.my-app//org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at io.be1.circular.my-app//org.jooby.funzy.Try.run(Try.java:729)
	at io.be1.circular.my-app//org.jooby.Sse$Handler.lambda$null$3(Sse.java:616)
	at io.be1.circular.my-app//io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.be1.circular.my-app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.be1.circular.my-app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.google.inject.OutOfScopeException: Cannot access Key[type=org.jooby.Response, annotation=[none]] outside of a scoping block
	at io.be1.circular.my-app//org.jooby.internal.RequestScope.getScopedObjectMap(RequestScope.java:255)
	at io.be1.circular.my-app//org.jooby.internal.RequestScope.lambda$scope$0(RequestScope.java:230)
	at io.be1.circular.my-app//com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at io.be1.circular.my-app//com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 15 common frames omitted
```

what's wrong? 
I would like to check the session (ifset)  include the sse in a list to access the communication channel per client. if I remove the req.ifSession the sse channel works. 

any hint why I'm facing this problem?

martin

**Comment by jknack** [comment]
nothing wrong, just session isn't supported in sse or websockets :S

you can save the SSE in a concurrentmap at the time it connects, then you will have them all.

don't forget to removed it from map on close

**Comment by martinbe1io** [comment]
Ok thx but what is best practice for authentication of a sse? passing a token with the sse  request seems to be not that cool, sending a special payload? What would you recommend ? 

Thx m
