### ISSUE TITLE
Change to MySQL in apitool-kotlin-starter produces java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required

### ISSUE THREAD

**Issue by JavierFuentes** [jooby-project/jooby#1301]
I've just downloaded master branch of [apitool-kotlin-starter](https://github.com/jooby-project/apitool-kotlin-starter) demo.

I can run it with `mvn jooby:run` with **h2** database...

However, when I try to change database connection to my localhost **MySQL** database server I get this error...

¿Could you provide the right setup needed to run OK this starter kit?

I've made these changes to setup MySQL after manually create the database `jooby-pets` following official docs from jooby website:

### pom.xml file

```xml
    <!-- h2 driver -->
    <!--
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
    </dependency>
    -->

    <!-- MySQL -->
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>${mysql-connector-java.version}</version>  <!-- actually 5.1.42 -->
    </dependency>
```

### application.conf file
```properties
#db = fs
db.url = "jdbc:mysql//localhost:3306/jooby-pets"
db.user = myuser
db.password = mypass
```

After that, I run again and get these logs:

```kotlin
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Volumes/Datos/Users/javier/IdeaProjects/jooby-apitool-kotlin-starter-master "-Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=49692:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2017.3.4 jooby:run
objc[2049]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building apitool-kotlin-starter 1.5.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jooby-maven-plugin:1.5.0:run (default-cli) > test-compile @ apitool-kotlin-starter >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce.versions) @ apitool-kotlin-starter ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ apitool-kotlin-starter ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ apitool-kotlin-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ apitool-kotlin-starter ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.51:compile (compile) @ apitool-kotlin-starter ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ apitool-kotlin-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Volumes/Datos/Users/javier/IdeaProjects/jooby-apitool-kotlin-starter-master/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ apitool-kotlin-starter ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.51:test-compile (test-compile) @ apitool-kotlin-starter ---
[WARNING] Source root doesn't exist: /Volumes/Datos/Users/javier/IdeaProjects/jooby-apitool-kotlin-starter-master/target/generated-test-sources/test-annotations
[INFO] 
[INFO] <<< jooby-maven-plugin:1.5.0:run (default-cli) < test-compile @ apitool-kotlin-starter <<<
[INFO] 
[INFO] --- jooby-maven-plugin:1.5.0:run (default-cli) @ apitool-kotlin-starter ---
>>> jooby:run[info|main]: Hotswap available on: [/Volumes/Datos/Users/javier/IdeaProjects/jooby-apitool-kotlin-starter-master]
>>> jooby:run[info|main]:   includes: [**/*.class:**/*.conf:**/*.properties]
>>> jooby:run[info|main]:   excludes: []
[2019-03-14 20:05:27,364]-[Hotswap] ERROR com.zaxxer.hikari.HikariConfig - mysql//localhost.pets - dataSource or dataSourceClassName or jdbcUrl is required.
mar 14, 2019 8:05:27 PM com.google.inject.internal.MessageProcessor visit
INFORMACIÓN: An exception was caught and reported. Message: java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required.
java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required.
	at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:955)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:77)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:539)
	at org.jooby.Jooby.install(Jooby.java:3422)
	at org.jooby.Jooby.lambda$bindService$47(Jooby.java:3083)
	at org.jooby.Jooby$$Lambda$266/2077289537.tryAccept(Unknown Source)
	at org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at org.jooby.funzy.Throwing$Consumer$$Lambda$267/1923853862.tryRun(Unknown Source)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at org.jooby.Jooby.lambda$null$41(Jooby.java:2932)
	at org.jooby.Jooby$$Lambda$265/591915621.tryRun(Unknown Source)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at org.jooby.funzy.Try.run(Try.java:729)
	at org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2918)
	at org.jooby.Jooby$$Lambda$239/822093365.configure(Unknown Source)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at org.jooby.Jooby.lambda$new$0(Jooby.java:885)
	at org.jooby.Jooby$$Lambda$194/534055592.apply(Unknown Source)
	at org.jooby.Jooby.bootstrap(Jooby.java:2996)
	at org.jooby.Jooby.start(Jooby.java:2197)
	at org.jooby.Jooby.start(Jooby.java:2178)
	at org.jooby.Jooby.run(Jooby.java:2107)
	at org.jooby.JoobyKt.run(Jooby.kt:116)
	at starter.apitool.AppKt.main(App.kt:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:440)
	at org.jooby.run.Main$$Lambda$185/557455197.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[2019-03-14 20:05:27,513]-[Hotswap] INFO  starter.apitool.App - Stopped
[2019-03-14 20:05:27,519]-[Hotswap] ERROR starter.apitool.App - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.jooby.spi.HttpHandler was bound.
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.netty.NettyServer.<init>(NettyServer.java:261)
  at org.jooby.netty.Netty.configure(Netty.java:221)

2) An exception was caught and reported. Message: dataSource or dataSourceClassName or jdbcUrl is required.
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at org.jooby.Jooby.lambda$new$0(Jooby.java:885)
	at org.jooby.Jooby$$Lambda$194/534055592.apply(Unknown Source)
	at org.jooby.Jooby.bootstrap(Jooby.java:2996)
	at org.jooby.Jooby.start(Jooby.java:2197)
	at org.jooby.Jooby.start(Jooby.java:2178)
	at org.jooby.Jooby.run(Jooby.java:2107)
	at org.jooby.JoobyKt.run(Jooby.kt:116)
	at starter.apitool.AppKt.main(App.kt:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:440)
	at org.jooby.run.Main$$Lambda$185/557455197.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required.
	at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:955)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:77)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:539)
	at org.jooby.Jooby.install(Jooby.java:3422)
	at org.jooby.Jooby.lambda$bindService$47(Jooby.java:3083)
	at org.jooby.Jooby$$Lambda$266/2077289537.tryAccept(Unknown Source)
	at org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at org.jooby.funzy.Throwing$Consumer$$Lambda$267/1923853862.tryRun(Unknown Source)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at org.jooby.Jooby.lambda$null$41(Jooby.java:2932)
	at org.jooby.Jooby$$Lambda$265/591915621.tryRun(Unknown Source)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at org.jooby.funzy.Try.run(Try.java:729)
	at org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2918)
	at org.jooby.Jooby$$Lambda$239/822093365.configure(Unknown Source)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 21 common frames omitted

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

**Comment by jknack** [comment]
think you have a typo in the url. try: `db.url = "jdbc:mysql://localhost:3306/jooby-pets"`

**Comment by JavierFuentes** [comment]
Hi @jknack,
you are right!!! it was a typo...

Additionally I needed to do this changes to work properly on MySQL:

### PetRepository.kt
```kotlin
    //@SqlUpdate("delete pets where id=:id")  /* This doesn't work with MySQL 5.6.23 */
    @SqlUpdate("delete from pets where id=:id")
    fun delete(id: Long): Boolean
```

### v1.0_Schema.sql
```sql
# CREATE TABLE pets (id bigint auto_increment, name varchar(255))
CREATE TABLE pets (id bigint PRIMARY KEY auto_increment, name varchar(255)) 
```
**Before** change this last file, it threw this error:
```
INFORMACIÓN: An exception was caught and reported. Message: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Incorrect table definition; there can be only one auto column and it must be defined as a key
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration v1.0_Schema.sql failed
--------------------------------
SQL State  : 42000
Error Code : 1075
Message    : Incorrect table definition; there can be only one auto column and it must be defined as a key
Location   : db/migration/v1.0_Schema.sql (/Volumes/Datos/Users/javier/IdeaProjects/jooby-apitool-kotlin-starter-master/src/main/resources/db/migration/v1.0_Schema.sql)
Line       : 1
Statement  : CREATE TABLE pets (id bigint auto_increment, name VARCHAR(255))
``` 

**It seems to work ok with latest MySQL connector 8.0.15 version too**...
### pom.xml
```xml
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>8.0.15</version>
    </dependency>
```

**Comment by jknack** [comment]
yea, those silly errors from one db engine vs another. The only reason to keep h2 into the example is simplicity so app can run without issue.

**Comment by JavierFuentes** [comment]
In case it can help someone ...

After **moving the `apitool-kotlin-starter` example code using Jdbi3 from script-mode to mvc-mode**, I had some difficulties with Swagger's interpretation with the optional parameters of the list method ... 

I was finally able to solve it using the **Optional<>** wrapper in the parameters .

Now the mvc-based API already looks 100% equivalent to the original one and looks like this:

### App.kt
```kotlin
package starter.apitool
import [ ... ]

/**
 * Kotlin ApiTool.
 */
class App : Kooby({
    [ ... ]

    /** Register Controllers */
    // path("/api/pet") { ... } script block removed from here
    use(PetsController::class)  // added
})
```

### PetsController.kt
```kotlin
package starter.apitool
import org.jooby.Err
import org.jooby.Result
import org.jooby.Results
import org.jooby.Status
import org.jooby.mvc.*
import java.util.*
import javax.inject.Inject

/**
 * Everything about your Pets.
 */
@Path("/api/pet")
class PetsController @Inject constructor(val db: PetRepository) {

    /**
     * List pets ordered by id.
     * @param start Start offset, useful for paging. Default is `0`.
     * @param max Max page size, useful for paging. Default is `20`.
     * @return Pets ordered by id.
     */
    @GET
    @Path("/list")
    fun list(start: Optional<Int>, max: Optional<Int>): List<Pet> {
        val _start = if (start.isPresent) start.get() else 0
        val _max = if (max.isPresent) max.get() else 20

        return db.list(_start, _max)
    }

    /**
     * Find pet by ID
     * @param id Pet ID.
     * @return Returns `200` with a single pet or `404`
     */
    @GET
    @Path("/:id")
    fun findById(id: Long): Pet {
        val pet = db.findById(id) ?: throw Err(Status.NOT_FOUND)
        return pet
    }

    /**
     * Add a new pet to the store.
     * @param body Pet object that needs to be added to the store.
     * @return Returns a saved pet.
     */
    @POST
    @Path("/add")
    fun add(@Body() pet: Pet): Pet {
        val id = db.insert(pet)

        return Pet(id, pet.name)
    }

    /**
     * Update an existing pet.
     * @param body Pet object that needs to be updated.
     * @return Returns a saved pet.
     */
    @PUT
    @Path("/:id")
    fun update(@Body() pet: Pet): Pet {
        if (!db.update(pet)) {
            throw Err(Status.NOT_FOUND)
        }

        return pet
    }

    /**
     * Deletes a pet by ID.
     * @param id Pet ID.
     * @return A `204`
     */
    @DELETE
    @Path("/:id")
    fun delete(id: Long): Result {
        if (!db.delete(id)) {
            throw Err(Status.NOT_FOUND)
        }

        return Results.noContent()
    }

}
```
