### ISSUE TITLE
Websocket: Fragmented Text Frames are not reassembled - partial data passed to user code

### ISSUE THREAD

**Issue by altmind** [jooby-project/jooby#1306]
Jooby+Kooby 1.6.0, Netty
```
ws("/ws") { ws ->
        ws.onMessage { message ->
            println(jsonParse(ws, message.value()))
        }
    }
```
Sometimes(usually takes ~5minutes of websocket request-response with recent chrome on localhost), we only receive a part of the message from the browser. In my case, browser sends ~2K of json, jooby executes callback with only ~400bytes string, the received message is partial json.

AFAIK, websocket text messages can be fragmented on the protocol level, to correctly handle whole messages you need to re-assemble the frames until you receive a frame with a FIN flag - http://www.lenholgate.com/blog/2011/07/websockets-is-a-stream-not-a-message-based-protocol.html

Netty TextWebSocketFrame exposes `bool finalFragment`, that marks if we need to expect more frames for same message coming https://netty.io/4.0/api/io/netty/handler/codec/http/websocketx/WebSocketFrame.html#isFinalFragment--

However, I dont see that `getFinalFragment`/`isFinalFragment` is called anywhere in jooby code. Seems that as soon jooby receives a text frame, it converts it to string and pass to the user code. This is not correct and results in partial data being passed to user app. This cannot be hacked/fixed in user code as `isFinalFragment` is not exposed to the user code.

I've captured some screeenshots of a debug session outlining the problem.
![image](https://user-images.githubusercontent.com/107891/55038613-6f06b780-4fef-11e9-9d6d-2cf0e7abd282.png)
![image](https://user-images.githubusercontent.com/107891/55038619-75952f00-4fef-11e9-9def-f726c9c622c0.png)
![image](https://user-images.githubusercontent.com/107891/55038622-79c14c80-4fef-11e9-9259-d37a830282eb.png)

**Comment by altmind** [comment]
Some examples on how "continuation" frames may be handled https://www.programcreek.com/java-api-examples/?class=io.netty.handler.codec.http.websocketx.WebSocketFrame&method=isFinalFragment - check example2 and example5

**Comment by altmind** [comment]
Please check #1307

Can you please create and push 1.6.0 branch so 1.6.0 could live on as "stable" while you are making these changes for 2.0 release? Right now, I cannot make a proper MR because v1.6.0 is only a TAG and github compares my changes to `master`.

**Comment by altmind** [comment]
Any updates? 
We're seeing this problem happening constantly, polluting our logs and causing neverending disconnects from the websocket clients.

The problem is aggravated by the fact you cannot just specify git url to use custom jooby in our pom.xml, so we need to get this changes integrated to jooby itself and get the jars released :(

```
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:588)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2029)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2016)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:278)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:445)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4044)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539)
...
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.internal.WebSocketImpl.lambda$null$5(WebSocketImpl.java:409)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.internal.WebSocketImpl.lambda$sync$13(WebSocketImpl.java:556)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.funzy.Try.run(Try.java:729)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.internal.WebSocketImpl.lambda$connect$6(WebSocketImpl.java:409)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.internal.netty.NettyWebSocket.handle(NettyWebSocket.java:373)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:283)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Apr 01 12:33:30 multi-admin.crtrading.loc multi_admin[28345]: at java.lang.Thread.run(Thread.java:748)
```
