### ISSUE TITLE
2.x Nullpointer when requesting resource that does not exist

### ISSUE THREAD

**Issue by yholkamp** [jooby-project/jooby#1319]
While playing around with the 2.x branch I noticed that using the `Jooby.resource(ResourceKey)` method with a key that does not exists results in a NPE. I think the framework should throw a more specific error here to notify us what's wrong.

```
java.lang.NullPointerException
	at io.jooby.Router.resource(Router.java:143)
	at io.jooby.Jooby.resource(Jooby.java:448)
	at net.test.api.App.lambda$new$baa66101$1(App.java:25)
	at io.jooby.internal.handler.SendCharSequence.apply(SendCharSequence.java:32)
	at io.jooby.internal.handler.WorkerHandler.lambda$apply$0(WorkerHandler.java:33)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jknack** [comment]
Fixed it
