### ISSUE TITLE
better error message when `assets.conf` is missing

### ISSUE THREAD

**Issue by AZWN** [jooby-project/jooby#1324]
Hi,

I am trying to set up jooby with react as described in the [docs](https://jooby.org/doc/assets-react/). However, I encounter a strange format exception. Debugging shows ```AssetCompiler.format``` is called with:

- ```w1 = 0```
- ```w2 = 0```
- ```args = ["Fileset", "Output", "Size"]```

This looks strange to me.

Do you have any suggestion how to fix this, or do you have any workaround?

Exception Stacktrace
```
[2019-05-21 14:56:17,289]-[Hotswap] ERROR nl.azwaan.quotedb.QuoteDBApp - An error occurred while starting the application:
java.util.MissingFormatWidthException: %-0s
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2954)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2725)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.jooby.assets.AssetCompiler.format(AssetCompiler.java:582)
	at org.jooby.assets.AssetCompiler.summary(AssetCompiler.java:568)
	at org.jooby.assets.Assets.lambda$configure$2(Assets.java:542)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Runnable.run(Throwing.java:86)
	at org.jooby.LifeCycle.lambda$onStarted$7(LifeCycle.java:487)
	at org.jooby.funzy.Throwing$Consumer.lambda$accept$0(Throwing.java:273)
	at org.jooby.funzy.Throwing.runAction(Throwing.java:2415)
	at org.jooby.funzy.Throwing.access$000(Throwing.java:39)
	at org.jooby.funzy.Throwing$Consumer.accept(Throwing.java:273)
	at org.jooby.Jooby.start(Jooby.java:2247)
	at org.jooby.Jooby.start(Jooby.java:2178)
	at org.jooby.Jooby.run(Jooby.java:2107)
```

**Comment by AZWN** [comment]
The issue turned out to be that my ```assets.conf``` file was accidentally called ```asserts.conf```. May it is an idea to have a better error message for that?
