### ISSUE TITLE
ApiTool map type parsing issue

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1329]
`org.jooby.internal.apitool.TypeJsonDeserializer.parse()` incorrectly parses complex map type like

`Map<UUID, List<Integer>>` 

it loses map key argument and generating signature `Map<List<java.lang.Integer>>` 
that can't be recognized as `java.lang.reflect.Type`

**Comment by walkman90** [comment]
To reproduce:
1. Build application with apitool plugin enabled
2. At least one endpoint shoud have response type `Map<String, List<Integer>>`
3. Run app
4. Open swagger doc page

Here is a stacktrace while apitool trying to load `/swagger/swagger.json`:

`Stacktrace:
org.jooby.Err: Bad Request(400)
        at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:589)
        at org.jooby.internal.HttpHandlerImpl.cleanup(HttpHandlerImpl.java:562)
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:504)
        at org.jooby.internal.undertow.UndertowHandler.handleRequest(UndertowHandler.java:252)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

`Caused by: java.lang.IllegalArgumentException: Cannot create TypeBindings for class java.util.Map with 1 type parameter: class expects 2`

        at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:126)
        at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:96)
        at com.fasterxml.jackson.databind.type.TypeFactory._fromParamType(TypeFactory.java:1454)
        at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1221)
        at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:631)
        at com.fasterxml.jackson.databind.ObjectMapper.constructType(ObjectMapper.java:1687)
        at org.jooby.internal.apitool.FriendlyTypeName.name(FriendlyTypeName.java:218)
        at org.jooby.internal.apitool.SwaggerBuilder.lambda$buildResponse$13(SwaggerBuilder.java:479)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.jooby.internal.apitool.SwaggerBuilder.buildResponse(SwaggerBuilder.java:479)
        at org.jooby.internal.apitool.SwaggerBuilder.build(SwaggerBuilder.java:432)
        at org.jooby.apitool.ApiTool.lambda$swagger$8(ApiTool.java:1054)
        at org.jooby.Route$OneArgHandler.handle(Route.java:1817)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
        at org.jooby.internal.RouteChain.next(RouteChain.java:262)
        at org.jooby.Route$Chain.next(Route.java:2163)
        at org.jooby.jdbi.OpenHandle.handle(OpenHandle.java:240)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
        at org.jooby.internal.RouteChain.next(RouteChain.java:262)
        at org.jooby.Route$Chain.next(Route.java:2163)
        at org.jooby.Route$Handler.handle(Route.java:1761)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
        at org.jooby.internal.RouteChain.next(RouteChain.java:262)
        at org.jooby.Route$Chain.next(Route.java:2163)
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
        ... 6 common frames omitted`
