### ISSUE TITLE
Jooby 1.6.x throws exception for empty cookies

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#1331]
As of Jooby 1.6.0 and 1.6.2, this code:

```java
import org.jooby.Jooby;
import org.jooby.Mutant;
import org.junit.Test;

import com.google.common.collect.ImmutableMap;
import io.restassured.RestAssured;

public class AuthEmptyCookieRepro {
  @Test
  public void repro() {
    Jooby app = new Jooby();
    app.get("/test", req -> {
      Mutant loginCookie = req.cookie("login");
      return loginCookie.isSet() ? loginCookie.value() : "not set";
    });
    app.start("server.join=false");
    RestAssured.given().cookies(ImmutableMap.of("login", "")).get("/test");
    app.stop();
  }
}
```

The server will throw

```
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.jooby.internal.RequestImpl.lambda$cookie$4(RequestImpl.java:439)
	at java.util.Optional.map(Optional.java:215)
	at org.jooby.internal.RequestImpl.cookie(RequestImpl.java:439)
	at auth.AuthEmptyCookieRepro.lambda$0(AuthEmptyCookieRepro.java:34)
	at org.jooby.Route$OneArgHandler.handle(Route.java:1817)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2163)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	... 10 common frames omitted
```

Because of line 439 in https://github.com/jooby-project/jooby/blob/ec6235cb36778816c5b40f6224ff0136e5c71b19/jooby/src/main/java/org/jooby/internal/RequestImpl.java#L435-L444

Looks like there may have been a regression from an issue fixed in #649, but I don't know when it starts.

**Comment by jknack** [comment]
undertow?

**Comment by nedtwigg** [comment]
netty

**Comment by nedtwigg** [comment]
I just tested with undertow, and I get the same problem
