### ISSUE TITLE
Netty: ctx.form() throws NullPointerException

### ISSUE THREAD

**Issue by ajcamilo** [jooby-project/jooby#1338]
With jooby-netty, in Jooby 2.0:

```
        post("/test", ctx -> {
            ctx.form().forEach(System.out::println);
            return "hello";
        });
```

returns `NullPointerException`:

```
java.lang.NullPointerException: null
	at io.jooby.internal.netty.NettyContext.decodeForm(NettyContext.java:537)
	at io.jooby.internal.netty.NettyContext.form(NettyContext.java:192)
	at com.premiumminds.jiffy.template.App.lambda$new$baa66101$2(App.java:81)
	at com.premiumminds.jiffy.template.common.rest.GuiceRequestScope.lambda$install$6e177016$1(GuiceRequestScope.java:16)
	at io.jooby.Route$Decorator.lambda$then$e67b40fd$1(Route.java:79)
	at io.jooby.internal.handler.SendCharSequence.apply(SendCharSequence.java:22)
	at io.jooby.internal.handler.WorkerHandler.lambda$apply$0(WorkerHandler.java:23)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Analyzing the code, `NettyContext` object has the field decoder set to `null` and I couldn't find any set to the field.

**Comment by jknack** [comment]
What did you send from client?

**Comment by ajcamilo** [comment]
```
curl -X POST http://localhost:8080/test
```

The problem is when no form-data was sent. 

But that's the case my use-case, the form-data is optional.
