### ISSUE TITLE
cann't load main class examples.HelloApp

### ISSUE THREAD

**Issue by flyzb618** [jooby-project/jooby#1340]
when I run the example, there is an error below:

"cann't load  main class examples.HelloApp".

my jdk is "1.8.0_162", who can tell me the reason ?

**Comment by jknack** [comment]
how did you start? IDE? java -jar? jooby:run?

Thanks

**Comment by flyzb618** [comment]
I use eclipse. When I run jooby 1.62 with same envirement, it works fine.

**Comment by jknack** [comment]
from IDE shouldn't be any problem. Make sure project classpath is OK

**Comment by flyzb618** [comment]
I got the erro blow:

> 
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method runApp(String[], App::new) is undefined for the type App

	at myTest.App.main(App.java:12)
>

**Comment by flyzb618** [comment]
can you give me a  example of 'https://github.com/jooby-project/greeting'  with jooby 2.x  ?

**Comment by jknack** [comment]
look at your pom.xml file:

- make sure groupId is `io.jooby` not `org.jooby`
- jooby version is set to `2.0.1` not `1.6.2`

It is a compilation/classpath issue

**Comment by flyzb618** [comment]
Exception in thread "main" java.util.ServiceConfigurationError: io.jooby.Server: Provider io.jooby.netty.Netty could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.jooby.Jooby.start(Jooby.java:539)
	at io.jooby.Jooby.runApp(Jooby.java:752)
	at io.jooby.Jooby.runApp(Jooby.java:715)
	at myTest.App.main(App.java:12)
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/ChannelHandler
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 13 more
Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelHandler
	at java.net.URLClassLoader$1.run(URLClassLoader.java:371)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:476)
	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:410)
	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:444)
	at java.util.jar.Attributes.read(Attributes.java:376)
	at java.util.jar.Manifest.read(Manifest.java:234)
	at java.util.jar.Manifest.<init>(Manifest.java:81)
	at java.util.jar.Manifest.<init>(Manifest.java:73)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:992)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	... 24 more

**Comment by jknack** [comment]
one or more jar files are corrupted (bad download)

> Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)

but it is hard to know which one is... Try to delete all io.jooby and io.netty artifacts from your local maven repository.

then do a `mvn clean package` from project root and wait for a SUCCESS build
