### ISSUE TITLE
ow2.asm Problem with Java 11

### ISSUE THREAD

**Issue by tobilebonk** [jooby-project/jooby#1345]
Hi :)

I encountered a problem while running Jooby 1.x under Java 11:

Environment:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

Stacktrace:
```
ERROR [atMyClass] An error occurred while starting the application:
java.lang.IllegalStateException: Can't read class: [anotherClass]
	at org.jooby.internal.RouteMetadata.extractMetadata(RouteMetadata.java:273)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at org.jooby.internal.RouteMetadata.lambda$md$0(RouteMetadata.java:259)
	at org.jooby.funzy.Throwing.fn(Throwing.java:2423)
	at org.jooby.funzy.Throwing.access$400(Throwing.java:39)
	at org.jooby.funzy.Throwing$Supplier.get(Throwing.java:145)
	at org.jooby.funzy.Try.apply(Try.java:691)
	at org.jooby.internal.RouteMetadata.md(RouteMetadata.java:259)
	at org.jooby.internal.RouteMetadata.startAt(RouteMetadata.java:254)
	at org.jooby.internal.mvc.MvcRoutes.lambda$routes$2(MvcRoutes.java:288)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.jooby.internal.mvc.MvcRoutes.routes(MvcRoutes.java:292)
	at org.jooby.Jooby.lambda$normalize$36(Jooby.java:2738)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.jooby.Jooby.normalize(Jooby.java:2731)
	at org.jooby.Jooby.bootstrap(Jooby.java:2797)
	at org.jooby.Jooby.start(Jooby.java:2197)
	at org.jooby.Jooby.start(Jooby.java:2178)
	at org.jooby.Jooby.start(Jooby.java:2167)
	at [aClass].start([aClass].java:74)
	at [aClass].lambda$[aMethod]$8([yetAnotherClass].java:597)
```

I was able to resolve this issue by building the Jooby application locally for myself with the latest version of ASM (https://mvnrepository.com/artifact/org.ow2.asm/asm/7.1) and embedding it to my project.

Could you include the latest ASM version and provide a new Jooby 1.x release with Java 11 support? 

Thanks in advance :)

Note: I also tried to run Jooby on Java 12 and got the same issue. I am not sure though if the latest ASM version would fix my problem on Java 12, since ASM seems not to support Java 12 at all (https://asm.ow2.io/versions.html) .

**Comment by jknack** [comment]
Another workaround if you inherited from jooby-project pom:

```
<asm.version>7.1</asm.version>
```

Set the `asm.version` property to 7.1

If you don't inherited from jooby-project pom:

- find the jooby dependency
- on top of if add the asm dependency

That should override the one that jooby uses

**Comment by tobilebonk** [comment]
Ah, thank you!
I'll try it out.

**Comment by aclowkey** [comment]
@jknack  Hey Edgar, We want to use java12 and encountered this issue with ASM.
We compile with Gradle and tried using shadow plugin to relocate, but it didn't work. 
Any suggestions?
Also ETA on 1.6.4 with the upgrade ?
