### ISSUE TITLE
Jooby without server (netty...) and without controllers

### ISSUE THREAD

**Issue by mbayealioune** [jooby-project/jooby#1348]
Hi,

How can I use jooby without having to add the web server layer ?
I want to just add this in my pom :

```
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby</artifactId>
            <version>1.6.3</version>
        </dependency>
```

If I do that, I get this error:
```

02:01:21.045 [main] DEBUG app.DaemonApplication - server.stop() resulted in exception
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.jooby.spi.Server was bound.
  while locating org.jooby.spi.Server

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075) ~[guice-4.2.2.jar:na]
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1034) ~[guice-4.2.2.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086) ~[guice-4.2.2.jar:na]
	at org.jooby.Jooby.stop(Jooby.java:3170) ~[jooby-1.6.3.jar:1.6.3]
	at org.jooby.Jooby.start(Jooby.java:2180) ~[jooby-1.6.3.jar:1.6.3]
	at org.jooby.Jooby.run(Jooby.java:2107) ~[jooby-1.6.3.jar:1.6.3]
	at app.DaemonApplication.main(DaemonApplication.java:57) ~[classes/:na]
02:01:21.045 [main] INFO  app.DaemonApplication - Stopped
02:01:21.045 [main] ERROR app.DaemonApplication - An error occurred while starting the application:
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.jooby.spi.Server was bound.
  while locating org.jooby.spi.Server

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075) ~[guice-4.2.2.jar:na]
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1034) ~[guice-4.2.2.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086) ~[guice-4.2.2.jar:na]
	at org.jooby.Jooby.start(Jooby.java:2233) ~[jooby-1.6.3.jar:1.6.3]
	at org.jooby.Jooby.start(Jooby.java:2178) ~[jooby-1.6.3.jar:1.6.3]
	at org.jooby.Jooby.run(Jooby.java:2107) ~[jooby-1.6.3.jar:1.6.3]
	at app.DaemonApplication.main(DaemonApplication.java:57) ~[classes/:na]

Process finished with exit code 0
```

But If I add the jooby netty dependecy for example, I do not have the error anymore.

Thank you in advance

**Comment by jknack** [comment]
Not sure what is the use case for this... but nope, Jooby is a web framework it won't work without a web server
