### ISSUE TITLE
Make jooby 2 stop idempotent

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#1351]
If jooby.stop is called twice a null pointer exception is thrown:

```
java.lang.NullPointerException
        at io.jooby.internal.RouterImpl.destroy(RouterImpl.java:430)
        at io.jooby.Jooby.stop(Jooby.java:642)
...
```

I'm assuming somewhere jooby 2.0 registers a `java.lang.Runtime` shutdown hook. Ignoring various race conditions our problem is we will shutdown all services that need shutdown on the Runtime hook as well.

We could differentiate from runtime shutdown and manual shutdown of the service but that would not be desirable as it would probably be brittle (again race conditions).

**Comment by agentgt** [comment]
For now here is my quick fix.
 
```
	public static class MyJooby extends Jooby {
		private final AtomicInteger state = new AtomicInteger();
		private static final int NEW = 0;
		private static final int STOPPING = 1;
		private static final int STOPPED = 2;
		private static final int FAILED = 3;
		
		@Override
		public Jooby stop() {
			if (state.compareAndSet(NEW, STOPPING)) {
				try {
					Jooby j = super.stop();
					state.compareAndSet(STOPPING, STOPPED);
					return j;
				}
				finally {
					state.compareAndSet(STOPPING, FAILED);
				}
			}
			return this;
		}
	}
```

You don't need all those states. A simple AtomicBoolean will probably be fine for this but every time I go the boolean route I always regret it and want more state inspection later.

**Comment by agentgt** [comment]
Also we should probably document the system property:

```
jooby.useShutdownHook
```

I was unaware of it till I looked at the code.
