### ISSUE TITLE
mvn:jooby run fails on version 2.0.2

### ISSUE THREAD

**Issue by ross-oreto** [jooby-project/jooby#1352]
Setup the most basic jooby kotlin project taken from the section https://jooby.io/#getting-started
- linux 64 bit
- java: 12.0.1
- maven: 3.6.1

pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.oreto</groupId>
    <artifactId>jooby</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <kotlin.version>1.3.41</kotlin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.jooby</groupId>
            <artifactId>jooby-netty</artifactId>
            <version>2.0.2</version>
        </dependency>

        <!-- Optional. Only for MVC routes-->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>1.3.41</version>
        </dependency>

        <!-- Optional. Only for suspend handlers-->
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <version>1.2.2</version>
        </dependency>

        <dependency>
            <groupId>io.jooby</groupId>
            <artifactId>jooby-test</artifactId>
            <version>2.0.2</version>
        </dependency>

        <dependency>
            <groupId>io.jooby</groupId>
            <artifactId>jooby-jackson</artifactId>
            <version>2.0.2</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <version>${kotlin.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>1.8</jvmTarget>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jooby</groupId>
                <artifactId>jooby-maven-plugin</artifactId>
                <version>1.6.3</version>
            </plugin>
        </plugins>
    </build>

</project>
```

App.kt
```
import io.jooby.Context
import io.jooby.runApp

fun main(args: Array<String>) {
    runApp(args) {

        get("/") { ctx: Context -> "Hello World!" }

    }
}
```

Unexpected error:

```
$ mvn jooby:run
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< org.oreto:jooby >---------------------------
[INFO] Building jooby 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> jooby-maven-plugin:1.6.3:run (default-cli) > test-compile @ jooby >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jooby ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jooby ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- kotlin-maven-plugin:1.3.41:compile (compile) @ jooby ---
[WARNING] /mnt/sdb1/code/projects/testy/jooby/src/main/kotlin/App.kt: (7, 20) Parameter 'ctx' is never used, could be renamed to _
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jooby ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /mnt/sdb1/code/projects/testy/jooby/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jooby ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- kotlin-maven-plugin:1.3.41:test-compile (test-compile) @ jooby ---
[WARNING] No sources found skipping Kotlin compile
[INFO] 
[INFO] <<< jooby-maven-plugin:1.6.3:run (default-cli) < test-compile @ jooby <<<
[INFO] 
[INFO] 
[INFO] --- jooby-maven-plugin:1.6.3:run (default-cli) @ jooby ---
>>> jooby:run[info|main]: Hotswap available on: [/mnt/sdb1/code/projects/testy/jooby]
>>> jooby:run[info|main]:   includes: [**/*.class:**/*.conf:**/*.properties]
>>> jooby:run[info|main]:   excludes: []
>>> jooby:run[error|Hotswap]: null.start() resulted in error
java.lang.NoClassDefFoundError: Failed to link org/jooby/internal/run__/JoobyRef (Module "org.oreto.jooby" from AppModuleLoader@28dc241e for finders []): org/jooby/funzy/Throwing$Consumer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:436)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jknack** [comment]
Project uses 2.x but jooby:run is 1.x

Change this:
```
<plugin>
                <groupId>org.jooby</groupId>
                <artifactId>jooby-maven-plugin</artifactId>
                <version>1.6.3</version>
            </plugin>
```

for:

```
<plugin>
                <groupId>io.jooby</groupId>
                <artifactId>jooby-maven-plugin</artifactId>
                <version>2.0.2</version>
            </plugin>
```

You need the `application.class` property too:

```
<!-- Startup class -->
    <application.class>yourpackage.AppKt</application.class>
```

**Comment by ross-oreto** [comment]
I added the correct jooby-maven-plugin which should take care of the initial reported error however now with the specified App.kt above, I get this error when running jooby:run

```
[ERROR] execution of org.oreto.AppKt resulted in exception
```
And I don't see any more error reporting for this issue in the console and also I added a global error handler and that doesn't print anything either.

**Comment by ross-oreto** [comment]
I'm able to run the App.kt class directly in intelliJ using App.kt as the main class and the application runs as expected, but not with jooby:run and I am using the maven property
```
<application.class>org.oreto.AppKt</application.class>
```

**Comment by jknack** [comment]
do a `mvc dependency:tree`, then `mvn clean jooby:run -X`

paste the output here

**Comment by ross-oreto** [comment]
I found the issue. It was a wrong package name, once it actually found the correct path to App.kt, the app started as expected.

**Comment by jknack** [comment]
glad you found, still need to print a better error message

**Comment by ross-oreto** [comment]
Yeah I agree, I'm running into this error again and this time it doesn't seem to have anything to do with the package path.

**Comment by jknack** [comment]
should be better now in 2.0.3 (just released it)
