### ISSUE TITLE
ApiTool doesn't allow additional responses

### ISSUE THREAD

**Issue by CDPrete** [jooby-project/jooby#1354]
Hi!
In the Swagger definition of an API contract as well as in the Java implementation is it possible to define multiple responses returned by an endpoint.
For example, in the Java implementation we have the annotations `@ApiResponse` and `@ApiResponses` for defining such additional responses.

It would be great if the same is applicable in Kooby as well.

**Comment by jknack** [comment]
`@ApiResponse(s)` annotations are supported at MVC routes.

For script routes it is bit more verbose (but possible). Here is a Java example:

```
Map apiResponse1 = new LinkedHashMap();
    apiResponse1.put("apiResponse.response", MyResponseType1.class);
    apiResponse1.put("apiResponse.message", "My type 1 description");

    Map apiResponse2 = new LinkedHashMap();
    apiResponse2.put("apiResponse.response", MyResponseType2.class);
    apiResponse2.put("apiResponse.message", "My type 2 description");
    
    Map[] apiResponses = {apiResponse1, apiResponse2};
    get("/some", req -> {
      return "SS";
    }).attr("apiResponses", apiResponses);
```

**Comment by CDPrete** [comment]
Is it possible to define those even on paths so that they're applied to all the routes inside a path?

**Comment by CDPrete** [comment]
Actually I get a NPE while doing so:
```
Caused by: java.lang.NullPointerException
	at org.jooby.internal.apitool.SwaggerBuilder.buildResponse(SwaggerBuilder.java:519) ~[jooby-apitool-1.6.3.jar:1.6.3]
	at org.jooby.internal.apitool.SwaggerBuilder.lambda$buildResponse$11(SwaggerBuilder.java:463) ~[jooby-apitool-1.6.3.jar:1.6.3]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181]
	at org.jooby.internal.apitool.SwaggerBuilder.buildResponse(SwaggerBuilder.java:464) ~[jooby-apitool-1.6.3.jar:1.6.3]
	at org.jooby.internal.apitool.SwaggerBuilder.build(SwaggerBuilder.java:432) ~[jooby-apitool-1.6.3.jar:1.6.3]
	at org.jooby.apitool.ApiTool.lambda$swagger$8(ApiTool.java:1054) ~[jooby-apitool-1.6.3.jar:1.6.3]
	at org.jooby.Route$OneArgHandler.handle(Route.java:1817) ~[jooby-1.6.3.jar:1.6.3]
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280) ~[jooby-1.6.3.jar:1.6.3]
	at org.jooby.internal.RouteChain.next(RouteChain.java:262) ~[jooby-1.6.3.jar:1.6.3]
	at org.jooby.Route$Chain.next(Route.java:2163) ~[jooby-1.6.3.jar:1.6.3]
...
```

**Comment by CDPrete** [comment]
> Also, how would you define the status code associated with each of the other responses?
After digging a bit in the code, I can answer myself here with `apiResponse.code`
