### ISSUE TITLE
Vulnerability in the default error renderer

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#1366]
I think that the problem mentioned in #453 is not yet solved. Using the most recent Jooby version we still experience the problem, and the security scan of our network also reported it.

The Jooby XSS features are awesome but the default error renderer does not seem to use them.

I don't know whether the problem still present in Jooby 2.x.

Using a custom template with XSS protection features (or simple escaping) is a workaround for this.

**Comment by jknack** [comment]
The issue in #453 was caused by rendering the request path as part of the HTML error page, which was solved. Jooby 2.x doesn't render the path so this won't occurs.

I need your help to identify the problem and fix it. Need an example

**Comment by imeszaros** [comment]
The security scanner uses the following URL and issues a GET request to it:

`http://hostname/"><script>alert(document.domain)</script>.html`

And the response is the following:

```
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {font-family: "open sans",sans-serif; margin-left: 20px;}
h1 {font-weight: 300; line-height: 44px; margin: 25px 0 0 0;}
h2 {font-size: 16px;font-weight: 300; line-height: 44px; margin: 0;}
footer {font-weight: 300; line-height: 44px; margin-top: 10px;}
hr {background-color: #f7f7f9;}
div.trace {border:1px solid #e1e1e8; background-color: #f7f7f9;}
p {padding-left: 20px;}
p.tab {padding-left: 40px;}
</style>
<title>
400 Bad Request
</title>
<body>
<h1>Bad Request</h1>
<hr><h2>message: Illegal char <"> at index 0: "><script>alert(document.domain)</script>.html</h2>
<h2>status: 400</h2>
</body>
</html>
```

Do you need anything else?

**Comment by jknack** [comment]
Something else is happens, I tried:

`http://localhost:8080/"><script>alert(document.domain)</script>.html`

Got:

```html
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {font-family: "open sans",sans-serif; margin-left: 20px;}
h1 {font-weight: 300; line-height: 44px; margin: 25px 0 0 0;}
h2 {font-size: 16px;font-weight: 300; line-height: 44px; margin: 0;}
footer {font-weight: 300; line-height: 44px; margin-top: 10px;}
hr {background-color: #f7f7f9;}
div.trace {border:1px solid #e1e1e8; background-color: #f7f7f9;}
p {padding-left: 20px;}
p.tab {padding-left: 40px;}
</style>
<title>
404 Not Found
</title>
<body>
<h1>Not Found</h1>
<hr><h2>message: Not Found(404): /%22%3E%3Cscript%3Ealert(document.domain)%3C/script%3E.html</h2>
<h2>status: 404</h2>
</body>
</html>
```

The path is escaped.

**Comment by imeszaros** [comment]
You're right. As i figured out, you need to register an asset handler to trigger the bad request response instead of 404:

```
package com.evonik.epic.statusreport.server;

import java.nio.file.Paths;

import org.jooby.Jooby;

public class XSSTest extends Jooby {

	{
		assets("/**", Paths.get("c:\\"));
	}

	public static void main(final String[] args) {
		run(XSSTest::new, args);
	}
}
```

**Comment by jknack** [comment]
think I got, but your example still doesn't produce the error

**Comment by jknack** [comment]
Found the problem

```
import java.nio.file.Paths;

import org.jooby.Jooby;

public class XSSTest extends Jooby {

	{
		get("/", req->req.param("x").intValue());
	}

	public static void main(final String[] args) {
		run(XSSTest::new, args);
	}
}
```

GET `http://localhost:8080/?"><script>alert(document.domain)</script>.html`

**Comment by imeszaros** [comment]
For me the error comes consistently without the parameter too, here is the full log:

```
15:15:05: Executing task 'XSSTest.main()'...

> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes

> Task :XSSTest.main()
15:15:10.528 [main] DEBUG XSSTest - config tree:
??? merge of system properties
 ??? org/jooby/spi/server.conf @ jar:file:/C:/Users/conta/.gradle/caches/modules-2/files-2.1/org.jooby/jooby-netty/1.6.1/2478dd9567c3548e8a4c6434f2fe6f203f07eac6/jooby-netty-1.6.1.jar!/org/jooby/spi/server.conf
  ??? org/jooby/mime.properties @ jar:file:/C:/Users/conta/.gradle/caches/modules-2/files-2.1/org.jooby/jooby/1.6.1/df9713d1a89b1919a3755048c7cc4ba02274eb8b/jooby-1.6.1.jar!/org/jooby/mime.properties
   ??? org/jooby/jooby.conf @ jar:file:/C:/Users/conta/.gradle/caches/modules-2/files-2.1/org.jooby/jooby/1.6.1/df9713d1a89b1919a3755048c7cc4ba02274eb8b/jooby-1.6.1.jar!/org/jooby/jooby.conf: 1

15:15:10.544 [main] DEBUG org.jooby.spi.Server - netty.threads.boss(1)
15:15:10.546 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
15:15:10.551 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 32
15:15:10.566 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
15:15:10.566 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
15:15:10.572 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
15:15:10.572 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
15:15:10.586 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
15:15:10.587 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
15:15:10.587 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
15:15:10.588 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
15:15:10.588 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
15:15:10.589 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
15:15:10.589 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
15:15:10.590 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
15:15:10.590 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
15:15:10.590 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
15:15:10.590 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
15:15:10.590 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\conta\AppData\Local\Temp\XSSTest
15:15:10.590 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
15:15:10.591 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 3803185152 bytes
15:15:10.591 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
15:15:10.592 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
15:15:10.592 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
15:15:10.597 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
15:15:10.888 [main] DEBUG org.jooby.spi.Server - netty.threads.worker(32)
15:15:10.928 [main] DEBUG org.jooby.spi.Server - netty.options.SO_REUSEADDR(true)
15:15:10.928 [main] DEBUG org.jooby.spi.Server - netty.worker.options.SO_REUSEADDR(true)
15:15:10.936 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 6120 (auto-detected)
15:15:10.938 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
15:15:10.938 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
15:15:11.191 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
15:15:11.191 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
15:15:11.465 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 60:45:cb:ff:fe:a0:eb:6b (auto-detected)
15:15:11.475 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
15:15:11.475 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 32
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 32
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
15:15:11.499 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
15:15:11.511 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
15:15:11.511 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
15:15:11.511 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
15:15:11.535 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0xb7835cac] REGISTERED
15:15:11.537 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0xb7835cac] BIND: /0.0.0.0:8080
15:15:11.538 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0xb7835cac, L:/0:0:0:0:0:0:0:0:8080] ACTIVE
15:15:11.537 [main] INFO XSSTest - [dev@netty]: Server started in 1520ms

  GET /**    [*/*]     [*/*]    (/anonymous)

listening on:
  http://localhost:8080/

15:15:43.186 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0xb7835cac, L:/0:0:0:0:0:0:0:0:8080] READ: [id: 0x52468ed1, L:/127.0.0.1:8080 - R:/127.0.0.1:58664]
15:15:43.187 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0xb7835cac, L:/0:0:0:0:0:0:0:0:8080] READ COMPLETE
15:15:43.205 [nio-worker-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
15:15:43.205 [nio-worker-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
15:15:43.206 [nio-worker-3-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@644ef071
15:15:43.230 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
15:15:43.230 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
15:15:43.230 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
15:15:43.230 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
15:15:43.260 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - execution of: GET/"><script>alert(document.domain)</script>.html resulted in exception
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "><script>alert(document.domain)</script>.html
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.jooby.handlers.AssetHandler.lambda$loader$5(AssetHandler.java:570)
	at org.jooby.handlers.AssetHandler.resolve(AssetHandler.java:551)
	at org.jooby.handlers.AssetHandler.resolve(AssetHandler.java:540)
	at org.jooby.handlers.AssetHandler.handle(AssetHandler.java:460)
	at org.jooby.Route$Handler.handle(Route.java:1760)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2163)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
15:15:43.264 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: org.jooby.Err$DefHandler@b2c9a9c
15:15:43.266 [netty task-4-1] ERROR org.jooby.Err - execution of: GET/"><script>alert(document.domain)</script>.html resulted in exception
Route:
      | Method | Path                                            | Source    | Name       | Pattern | Consumes | Produces |
      |--------|-------------------------------------------------|-----------|------------|---------|----------|----------|
      | GET    | /"><script>alert(document.domain)</script>.html | XSSTest:8 | /anonymous | /**     | [*/*]    | [*/*]    |

Stacktrace:
org.jooby.Err: Bad Request(400)
	at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:589)
	at org.jooby.internal.HttpHandlerImpl.cleanup(HttpHandlerImpl.java:562)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:504)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "><script>alert(document.domain)</script>.html
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.jooby.handlers.AssetHandler.lambda$loader$5(AssetHandler.java:570)
	at org.jooby.handlers.AssetHandler.resolve(AssetHandler.java:551)
	at org.jooby.handlers.AssetHandler.resolve(AssetHandler.java:540)
	at org.jooby.handlers.AssetHandler.handle(AssetHandler.java:460)
	at org.jooby.Route$Handler.handle(Route.java:1760)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2163)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	... 10 common frames omitted
15:15:43.956 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - execution of: GET/favicon.ico resulted in exception
org.jooby.Err: Not Found(404)
	at org.jooby.handlers.AssetHandler.handle(AssetHandler.java:483)
	at org.jooby.Route$Handler.handle(Route.java:1760)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2163)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
15:15:43.956 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: org.jooby.Err$DefHandler@b2c9a9c
15:15:43.956 [netty task-4-1] ERROR org.jooby.Err - execution of: GET/favicon.ico resulted in exception
Route:
      | Method | Path         | Source    | Name       | Pattern | Consumes | Produces |
      |--------|--------------|-----------|------------|---------|----------|----------|
      | GET    | /favicon.ico | XSSTest:8 | /anonymous | /**     | [*/*]    | [*/*]    |

Stacktrace:
org.jooby.Err: Not Found(404)
	at org.jooby.handlers.AssetHandler.handle(AssetHandler.java:483)
	at org.jooby.Route$Handler.handle(Route.java:1760)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2163)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jknack** [comment]
oh yea, bc we found a bad char for windows file system, that is not the case in OSX :)

anyway, found the issue it is on the `exception.message` which is not escaped it

**Comment by imeszaros** [comment]
Oh... :) That explains it! I should have mention it that we're using windows, sorry!

**Comment by jknack** [comment]
np, can you send a pull request?

**Comment by imeszaros** [comment]
Sure! But i'm not certain where to put the escaping. The safest would be to put it in `DefaultErrRenderer`, where it concatenates the response, But that would mess up at least the 404 page, because it already throws an `Err` with an escaped path:

`throw new Err(Status.NOT_FOUND, req.path(/* escape: */ true));`

What do you think?

**Comment by jknack** [comment]
This is what I should do:

- Find the `throw new Err(Status.NOT_FOUND, req.path(true))` and just do `req.path()`
- On default error handler, find where we do build the error map, get the `message` from it, escape the value and put it again.

The escaper is available via: `require(Env.class).xss("html")`

So now no matter if it is just the path or any message we always escape the value.

**Comment by imeszaros** [comment]
Okay, i'm on it!
