### ISSUE TITLE
MVC + jackson - List parameters not working

### ISSUE THREAD

**Issue by ajcamilo** [jooby-project/jooby#1391]
I'm having the following problem:

```
io.jooby.TypeMismatchException: Cannot convert value: 'body', to: 'com.premiumminds.jiffy.template.gdpr.dto.GdprConsentDTO'
	at io.jooby.internal.ValueInjector.resolve(ValueInjector.java:158)
	at io.jooby.internal.ValueInjector.value(ValueInjector.java:363)
	at io.jooby.internal.ValueInjector.collection(ValueInjector.java:387)
	at io.jooby.internal.ValueInjector.value(ValueInjector.java:296)
	at io.jooby.internal.ValueInjector.inject(ValueInjector.java:61)
	at io.jooby.Value.to(Value.java:458)
	at io.jooby.Value.toList(Value.java:333)
	at com.premiumminds.jiffy.template.gdpr.rest.GdprManagementAPI$POST$_me$obj.apply(GdprManagementAPI.java)
```
with this code:

```java
    @POST
    @Path({"/@me"})
    public void updateNewSettings(List<GdprConsentDTO> body) {
        this.service.saveNewSettings(body);
    }
```

My request it's fine (I checked many times). The problem after digging into the jooby code is that jackson is not being used. I don't know why.

The MVC annotation processor generated the following:

```
    public Object apply(Context ctx) throws Exception {
        ((GdprManagementAPI)this.provider.get()).updateNewSettings((List)var1.body().toList(GdprConsentDTO.class));
        return var1.isResponseStarted() ? var1 : var1.send(StatusCode.NO_CONTENT);
    }
```

FYI: when the generated code uses `body(ClassDTO.class)` jackson is used

**Comment by jknack** [comment]
found this bug too and should be fixed it in 2.x branch. It is an issue on how the Value API works.

Going to add a test for this.
