### ISSUE TITLE
Feature request: type-safe role annotations with enums

### ISSUE THREAD

**Issue by cbxp** [jooby-project/jooby#1527]
According to documentation, in MVC controllers custom annotation can be used to specify required roles that are later available in attributes.

This works with string-based annotation, but not with type-safe enum, e.g.:

```
@Path("/hello")
class SomeController {
  enum class Role {USER, ADMIN}

  @Target(AnnotationTarget.CLASS, AnnotationTarget.FUNCTION)
  @Retention(AnnotationRetention.RUNTIME)
  annotation class RequireRole(val value: Role)

  @GET @RequireRole(Role.ADMIN)
  fun login() {}
}
```

It seems that annotation processor expects annotation value to always be String and generates invalid bytecode:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.jooby.Jooby.lambda$null$10(Jooby.java:1042)
	at io.jooby.SneakyThrows$Function.apply(SneakyThrows.java:521)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.jooby.Jooby.lambda$reflectionProvider$12(Jooby.java:1042)
	at io.jooby.Jooby.createApp(Jooby.java:938)
	at io.jooby.Jooby.runApp(Jooby.java:910)
	at io.jooby.Jooby.runApp(Jooby.java:850)
	at io.jooby.KoobyKt.runApp(Kooby.kt:296)
	at io.jooby.KoobyKt.runApp(Kooby.kt:292)
	at LauncherKt.main(Launcher.kt:4)
Caused by: java.util.ServiceConfigurationError: io.jooby.MvcFactory: auth.SomeController$Module Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at io.jooby.Jooby.mvc(Jooby.java:296)
	at io.jooby.Jooby.mvc(Jooby.java:283)
	at app.AppKt.registerControllers(App.kt:90)
	at app.AppKt.access$registerControllers(App.kt:1)
	at app.App$1.invoke(App.kt:55)
	at app.App$1.invoke(App.kt:33)
	at io.jooby.Kooby.<init>(Kooby.kt:108)
	at app.App.<init>(App.kt:33)
	... 14 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    auth/SomeController$Module.install(Lio/jooby/Jooby;Ljavax/inject/Provider;)V @23: invokevirtual
  Reason:
    Type 'io/jooby/Route' (current frame, stack[0]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'io/jooby/Jooby', 'javax/inject/Provider', 'io/jooby/Route' }
    stack: { 'io/jooby/Route', 'java/lang/String' }
  Bytecode:
    0000000: 2a12 2d2b ba00 3800 00b6 0057 4d2c 1244
    0000010: b600 5d57 2c12 5fb6 0063 57b1          

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
	... 34 more
```

**Comment by cbxp** [comment]
Also, support for array or either Strings or Enums would also be helpful in case multiple roles are allowed to access an endpoint
