### ISSUE TITLE
[jooby-cli] posix file permissions throws UnsupportedOperationException on Windows

### ISSUE THREAD

**Issue by Canoir** [jooby-project/jooby#1668]
Hi Jooby,
in jooby 2 when I use the terminal for creating a new project from windows 10 with your bat file and administration permission I get this error(just by Gradle, everything else is fine):
``
java.lang.UnsupportedOperationException
        at java.nio.file.Files.setPosixFilePermissions(Files.java:2044)
        at io.jooby.internal.cli.CommandContextImpl.copyResource(CommandContextImpl.java:129)
        at io.jooby.cli.CreateCmd.gradleWrapper(CreateCmd.java:294)
        at io.jooby.cli.CreateCmd.run(CreateCmd.java:199)
        at io.jooby.cli.Cmd.run(Cmd.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at io.jooby.cli.Cli.main(Cli.java:117)
``

The command is :``create MySecond2 --gradle`` OR ``create MySecond3 -g`` both same error.

So what should I do now?
Thanks.

**Comment by jknack** [comment]
Thanks, pushed a fix.
