### ISSUE TITLE
Unsupported Media Type When Post

### ISSUE THREAD

**Issue by Sayyiditow** [jooby-project/jooby#1705]
I can't seem to get the post method to work at all. I am using mvc routes. Here is a simple controller:

`public class TestController {
@Path("/login-api")
    @POST
public void testPost(Context context) {
System.out.println(context.form());
}
}`

The main class has:

`{
        mvc(new TestController());
}`

I keep getting error:

`
io.jooby.exception.UnsupportedMediaType: application/x-www-form-urlencoded
	at io.jooby.MessageDecoder.lambda$static$0(MessageDecoder.java:25)
	at io.jooby.MessageDecoder$$Lambda$561/000000005400DE90.decode(Unknown Source)
	at io.jooby.DefaultContext.decode(DefaultContext.java:386)
	at io.jooby.internal.ByteArrayBody.to(ByteArrayBody.java:77)
	at io.jooby.Body.to(Body.java:92)
	at io.jooby.DefaultContext.body(DefaultContext.java:363)
	at com.sayyiditow.server.jooby.controller.LoginController$Module.postPerformLogin$context$body$header$contextr(com.sayyiditow.server.jooby.controller.LoginController$Module.java)
	at com.sayyiditow.server.jooby.controller.LoginController$Module$$Lambda$543/00000000FE3544D0.apply(Unknown Source)
	at io.jooby.internal.handler.DefaultHandler.apply(DefaultHandler.java:23)
	at io.jooby.internal.handler.WorkerHandler.lambda$apply$0(WorkerHandler.java:23)
	at io.jooby.internal.handler.WorkerHandler$$Lambda$557/0000000034055680.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

I have tried to add "consumes" to the method to try application/json and that does not work too.

**Comment by Sayyiditow** [comment]
Sorry, it actually works. It's weird, I did a maven rebuild and it worked. The little annoying things sometimes!
