### ISSUE TITLE
[2.8.6] Unable to create Guice injector at startup

### ISSUE THREAD

**Issue by JeffLeFoll** [jooby-project/jooby#1799]
Since 2.8.6, Jooby fail to start when installing GuiceModule, probably a side effect of #1774.  

Here is the complete stack trace :  

```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to io.jooby.Environment was already configured at io.jooby.di.JoobyModule.configureEnv(JoobyModule.java:71).
  at io.jooby.di.JoobyModule.configureResources(JoobyModule.java:62)

2) A binding to com.typesafe.config.Config was already configured at io.jooby.di.JoobyModule.configureEnv(JoobyModule.java:70).
  at io.jooby.di.JoobyModule.configureResources(JoobyModule.java:62)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.jooby.di.GuiceModule.install(GuiceModule.java:76)
	at io.jooby.Jooby.lambda$install$5(Jooby.java:393)
	at io.jooby.SneakyThrows$Runnable.run(SneakyThrows.java:124)
	at io.jooby.Jooby.fire(Jooby.java:1049)
	at io.jooby.Jooby.start(Jooby.java:703)
	at io.jooby.Server$Base.fireStart(Server.java:57)
	at io.jooby.utow.Utow.start(Utow.java:105)
	at io.jooby.Jooby.start(Jooby.java:669)
	at io.jooby.Jooby.runApp(Jooby.java:957)
	at io.jooby.Jooby.runApp(Jooby.java:920)  
```

**Comment by jknack** [comment]
Fixed and released: 2.8.7
