### ISSUE TITLE
File upload multipart hits an error of ClassCastException while using CsrfHandler

### ISSUE THREAD

**Issue by Sayyiditow** [jooby-project/jooby#1815]
When trying to upload a file through a multipart/form-data encoded form, then scripts path fails and hits the error below:

```
java.lang.ClassCastException: io.jooby.internal.FormdataNode incompatible with io.jooby.Multipart
    at io.jooby.internal.utow.UtowContext.formData(UtowContext.java:543)
    at io.jooby.internal.utow.UtowContext.form(UtowContext.java:240)
    at io.jooby.DefaultContext.form(DefaultContext.java:326)
    at io.jooby.CsrfHandler.apply(CsrfHandler.java:124)
    at io.jooby.Route$Before.lambda$then$e67b40fd$1(Route.java:131)
    at io.jooby.Route$Before$$Lambda$240/0000000041BEDBF0.apply(Unknown Source)
    at io.jooby.internal.handler.DefaultHandler.apply(DefaultHandler.java:23)
    at io.jooby.internal.handler.WorkerHandler.lambda$apply$0(WorkerHandler.java:23)
    at io.jooby.internal.handler.WorkerHandler$$Lambda$261/000000009C07E950.run(Unknown Source)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

Here is the scripts path being used:

```
before(new CsrfHandler());

post("/test-upload", ctx -> {
    System.out.println(ctx.multipart("file"));
    return 0;
 });
```

Html form looks like this:

```
<form method="post" action="/test-upload" 
                  enctype="multipart/form-data">
<input type="file" name="file" multiple required accept="image/*" id="file"
                               class="image-upload">
<input type="submit" class="button-primary submitButton" value="Submit"/>
</form>
```

I've tried this on both normal form submit and through the fetch API using FormData. Both give the same error.

Jooby version: 2.8.5

**Comment by Sayyiditow** [comment]
Thank you! Appreciated!
