### ISSUE TITLE
ctx.responseStream().flush() fails with NPE

### ISSUE THREAD

**Issue by cbxp** [jooby-project/jooby#1865]
Jooby 2.8.9.

We are using ZXing to send QR code to the client, which uses Java desktop ImageIO to write a png to the stream.
Internally, it calls stream.flush() before close(), but `NettyOutputStream.flush()` is broken in a way that it calls `flush(null, null)`, but then tries to add a listener as null.

```
java.lang.NullPointerException: listener
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:176)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at io.jooby.internal.netty.NettyOutputStream.flush(NettyOutputStream.java:96)
	at io.jooby.internal.netty.NettyOutputStream.flush(NettyOutputStream.java:73)
	at java.desktop/javax.imageio.stream.FileCacheImageOutputStream.close(FileCacheImageOutputStream.java:238)
	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1596)
	at com.google.zxing.client.j2se.MatrixToImageWriter.writeToStream(MatrixToImageWriter.java:157)
	at com.google.zxing.client.j2se.MatrixToImageWriter.writeToStream(MatrixToImageWriter.java:142)
	at auth.InvitationController.invitationQR(InvitationController.kt:31)
	at auth.InvitationController$Module.getInvitationQR$invitationId$ctx(auth.InvitationController$Module.java)
	at app.RequestDecorator$install$$inlined$run$lambda$1$1$1.invoke(RequestDecorator.kt:25)
	at db.ThreadLocalTransactionKt.withTransaction(ThreadLocalTransaction.kt:41)
	at db.ThreadLocalTransactionKt.withTransaction$default(ThreadLocalTransaction.kt:36)
	at app.RequestDecorator$install$$inlined$run$lambda$1$1.invoke(RequestDecorator.kt:24)
	at app.RequestDecorator.runWith(RequestDecorator.kt:59)
	at app.RequestDecorator.runWithLogging(RequestDecorator.kt:54)
	at app.RequestDecorator$install$$inlined$run$lambda$1.invoke(RequestDecorator.kt:23)
	at app.RequestDecorator$install$$inlined$run$lambda$1.invoke(RequestDecorator.kt:13)
	at io.jooby.Kooby$decorator$1$1.apply(Kooby.kt:126)
	at io.jooby.HeadHandler.lambda$apply$e67b40fd$1(HeadHandler.java:26)
	at io.jooby.Route$Decorator.lambda$then$e67b40fd$1(Route.java:89)
	at io.jooby.Route$Before.lambda$then$e67b40fd$1(Route.java:133)
	at io.jooby.internal.handler.SendDirect.apply(SendDirect.java:22)
	at io.jooby.internal.HeadResponseHandler.apply(HeadResponseHandler.java:29)
	at io.jooby.internal.handler.WorkerHandler.lambda$apply$0(WorkerHandler.java:23)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jknack** [comment]
As workaround you can switch to Undertow or Jetty: https://jooby.io/#server
