### ISSUE TITLE
IOException: connection closed [Netty, IE11]

### ISSUE THREAD

**Issue by csisy** [jooby-project/jooby#1867]
- Jooby version: 2.8.9.
- Netty server
- IE 11 browser

Created a new empty Jooby application (gradle, Netty) using the provided CLI tool. Using IE 11, I get an exception when the browser's tab is closed:

```
[2020-07-21 08:49:20,643]-[eventloop-4-2] ERROR app.App - GET / 500 Server Error
java.io.IOException: An existing connection was forcibly closed by the remote host
        at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
        at myapp//io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
        at myapp//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
        at myapp//io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at myapp//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at myapp//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at myapp//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at myapp//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at myapp//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:484)
        at myapp//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at myapp//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at myapp//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

So the steps to reproduce:

- Create a new Jooby application (Gradle, Netty server, MVC)
- Start the application from the command line: `gradlew joobyRun`
- Open Internet Explorer 11 and navigate to the configured host:port
- The server responds with a message: "Welcome to Jooby!"
- Close the browser's tab
- On the terminal, the above exception is produced

It work as expected with Chrome and Edge so it might not be a Jooby issue at all, but I cannot decide. It's not urgent, but please take a look when you have some spare time.

**Comment by jknack** [comment]
Hi,

 The connection reset by peer is exactly that: client closing the connection. This exception is usually printed as DEBUG level, so we are missing this check somewhere. Can you trace where the log is made? I don't have IE to test.

Thanks

**Comment by imeszaros** [comment]
Can be reporduced this small program (Jooby running at `http://localhost:8080` of course):

```
public class Client {

    public static void main(String[] args) {
        try {
            new URL("http://localhost:8080").openConnection().getInputStream();
            System.exit(0);
        } catch (IOException ignored) {}
    }
}
```

Easy to fix by extending `io.jooby.Server#connectionLost`. The only problem is that these messages are localized (by the OS I guess), so it only works on english OS? Mine is hungarian and the error message is hungarian.. :) Setting the Java default `Locale` has no effect on it.

**Comment by jknack** [comment]
I didn't know about the localized message is bit odd.

Thanks for your PR
