### ISSUE TITLE
 com.google.inject.ConfigurationException: Guice configuration errors:

### ISSUE THREAD

**Issue by anacarlagb** [jooby-project/jooby#193]
I'm using jooby in my aplication, but every time that run all tests throw this jooby problem. 
However, when run test by package, the test is correct.

1) No implementation for org.jooby.spi.Server was bound.
  while locating org.jooby.spi.Server

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.jooby.Jooby.start(Jooby.java:3042)
	at org.jooby.Jooby.start(Jooby.java:3003)
	at org.jooby.test.AppRule.before(AppRule.java:39)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by jknack** [comment]
when did you get the error? or how did you run tests and get this error?

also, can you paste your pom.xml?

thanks

**Comment by paulovictorv** [comment]
So @anacarlagb happens to be working by my side, so I've managed to fix the issue.

The problem was apparently happening by having two classes extending BaseTest, one being the default class the archetype generates and the other being a custom one. I deleted the default one and the tests started to magically pass.

Before that, I was tinkering with the code and I switched the ``@ClassRule`` to a ``@Rule``, forcing Jooby to create an server instance before each method, resulting in no errors.

Maybe what I explained to you above can help you clarify the problem.

PS: @anacarlagb works for the same company as me, and we are developing two micro-services using Jooby. This one I hope to make it open-source, so expect news from us.

**Comment by anacarlagb** [comment]
@paulovictorv . 
Ok, resolved issue.

**Comment by jknack** [comment]
yea, didn't try it... but BaseTest(generated by jooby) should probably be an abstract class.

**Comment by anacarlagb** [comment]
@jknack the BaseTest isn't abstract class and the problem is because two or more controller class cannot run at the same time.

**Comment by jknack** [comment]
ok, but when/how they run at the same time?

**Comment by anacarlagb** [comment]
We run all controller test for check if all test are correct when integrate the modifications.

**Comment by jknack** [comment]
that's ok, but tests don't run in parallel

**Comment by anacarlagb** [comment]
No, the controller test don't run in parallel when AppTest Class exists, in this case.
