### ISSUE TITLE
jooby-cli: Can not set workspace on Mac OS X 10.14.6

### ISSUE THREAD

**Issue by nikolaosinlight** [jooby-project/jooby#2109]
Hello,

Not sure what I am doing wrong but I cannot seem to get jooby-cli 2.9.2 setup.

When I run jooby-cli to create a workspace with a ~ or even an absolute path it fails - see below.

How do I resolve this issue?  I want to use the CLI to create a starter project and cannot.

```
# ./bin/jooby set -w ~/workspace
java.io.FileNotFoundException: /Users/nikolaos/workspace
        at io.jooby.internal.cli.CommandContextImpl.setWorkspace(CommandContextImpl.java:82)
        at io.jooby.cli.SetCmd.run(SetCmd.java:28)
        at io.jooby.cli.Cmd.run(Cmd.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at io.jooby.cli.Cli.main(Cli.java:107)
```

```
# ./bin/jooby set -w /Users/nikolaos/workspace
java.io.FileNotFoundException: /Users/nikolaos/workspace
        at io.jooby.internal.cli.CommandContextImpl.setWorkspace(CommandContextImpl.java:82)
        at io.jooby.cli.SetCmd.run(SetCmd.java:28)
        at io.jooby.cli.Cmd.run(Cmd.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at io.jooby.cli.Cli.main(Cli.java:107)

```

**Comment by jknack** [comment]
Does the `~/workspace` exist?

I can't reproduce it on when directory exist. Only happens when `workspace` doesn't exit.

Both works for me:`./bin/jooby set -w ~/workspace` ./bin/jooby set -w /Users/nikolaos/workspace

The `~` doesn't work when running inside jooby cli:

```
jooby> set -w ~/Source
java.io.FileNotFoundException: /Users/edgar/~/Source
	at io.jooby.internal.cli.CommandContextImpl.setWorkspace(CommandContextImpl.java:82)
	at io.jooby.cli.SetCmd.run(SetCmd.java:28)
	at io.jooby.cli.Cmd.run(Cmd.java:20)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at io.jooby.cli.Cli.main(Cli.java:117)
```

But using absolute path inside jooby-cli does work too:

    jooby> set -w /Users/edgar/Source

**Comment by nikolaosinlight** [comment]
No. It didn't exist and yes it works once I create it. Sorry for the waste of time to test this.

My bad but it is very surprising to create an empty folder for a command to run successfully.

A few thoughts:
- Might be worth documenting that this an empty folder for the workspace needs to be created
- OR better yet might be worth considering having the command simply create the folder if it doesn't exist
- OR best of all simply trap the FileNotFoundException and try to create the folder vs. continuing

--Nikolaos

**Comment by jknack** [comment]
going to add a `-f` option:

```
jooby> set -w ~/foodir
Directory doesn't exist: /Users/edgar/foodir
Use -f to force directory creation
jooby> set -w ~/foodir -f
jooby>
```

**Comment by jknack** [comment]
Also the `concept` of workspace is the working folder for ALL your projects and that is reason why assumes it must be present. The project folder is created by cli.
