### ISSUE TITLE
SslOptions.x509() method doesn't allow for absolute paths

### ISSUE THREAD

**Issue by Metroite** [jooby-project/jooby#2303]
```java
SslOptions.x509("C:\Users\user\Documents\GitHub\JoobyT\build\resources\main\key\cert.pem", "C:\Users\user\Documents\GitHub\JoobyT\build\resources\main\key\privkey.pem")
```

Expected Output:
`C:\Users\user\Documents\GitHub\JoobyT\build\resources\main\key\cert.pem`

Real Output:
`C:\Users\user\Documents\GitHub\JoobyT\run\C:\Users\user\Documents\GitHub\JoobyT\build\resources\main\key\cert.pem`

**Comment by jknack** [comment]
I can't reproduce on Mac OSX.

Also, did you get a file not found exception? You should get one.

**Comment by U1F984** [comment]
This is a Windows-specific issue:

In SslOptions#getResource `Paths.get(System.getProperty("user.dir"), path)` will cause an `InvalidPathException`:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 34: C:\Users\U1F984\IdeaProjects\prj\C:\Users\U1F984\AppData\Local\Temp\certificate.crt
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at io.jooby.SslOptions.getResource(SslOptions.java:237)
	at io.jooby.internal.SslX509Provider.create(SslX509Provider.java:29)
	at io.jooby.ServerOptions.getSSLContext(ServerOptions.java:566)
	at io.jooby.utow.Utow.start(Utow.java:127)
	at io.jooby.Jooby.start(Jooby.java:802)
```

This is presumably not reproducible on Linux or Mac OSX since there an additional `/` does not matter.

Due to the fact that SslOptions is final I was only able to work around this bug by setting `user.dir` to empty string, like this:

```kt
val oldValue = System.getProperty("user.dir")
System.setProperty("user.dir", "")
try {
    server = app.start()
} finally {
    System.setProperty("user.dir", oldValue)
}
```
