### ISSUE TITLE
Can't get MVC to work with coroutines

### ISSUE THREAD

**Issue by garkin** [jooby-project/jooby#2322]
Can't get MVC to work with coroutines as in the https://jooby.io/#mvc-api-responses-nonblocking
`joobyVersion = "2.9.5"`

Requests fails with an error in both Maven and Gradle generated projects:
```
Bad Request
message: Missing value: 'coroutineRouter'
status code: 400
```

<details> 
  <summary>Exception in the console:

```
io.jooby.exception.MissingValueException: Missing value: 'coroutineRouter'
    at io.jooby.Router.attribute(Router.java:140)
    at io.jooby.Jooby.attribute(Jooby.java:648)
```

 </summary>

   ```io.jooby.exception.MissingValueException: Missing value: 'coroutineRouter'
    at io.jooby.Router.attribute(Router.java:140)
    at io.jooby.Jooby.attribute(Jooby.java:648)
    at io.jooby.internal.mvc.CoroutineLauncher.apply(CoroutineLauncher.kt:17)
    at io.jooby.internal.netty.NettyContext.detach(NettyContext.java:221)
    at io.jooby.internal.handler.DetachHandler.apply(DetachHandler.java:21)
    at io.jooby.internal.StaticRouterMatch.execute(StaticRouterMatch.java:34)
    at io.jooby.internal.netty.NettyHandler.channelRead(NettyHandler.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:484)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details> <summary>Sample code:
 </summary>

```kotlin
package scaff

import io.jooby.Kooby
import io.jooby.runApp
import io.jooby.annotations.*
import kotlinx.coroutines.delay

class App: Kooby({
  serverOptions {
    port = 8888
  }
  mvc(Controller())
})

fun main(args: Array<String>) {
  runApp(args, App::class)
}

@Path("/")
class Controller {
  @GET
  suspend fun sayHi(): String {
    delay(800)
    return "Welcome to Jooby!"
  }
}
```
</details>

Sample project:
[corutines issue error sample.zip](https://github.com/jooby-project/jooby/files/6353806/corutines.issue.error.sample.zip)

**Comment by jknack** [comment]
try with the coroutine block first;

```
coroutine {
   mvc(Controller())
}
```

https://jooby.io/#responses-nonblocking-kotlin-coroutines

**Comment by garkin** [comment]
@jknack works like a charm. Thank you!
