### ISSUE TITLE
jackson: remove BlackBirdModule from defaults setup

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#2428]
Next release 2.11+ requires to manually add Afterburner(for java8) or BlackBird for (java9+).

Want to remove the warning:

```
WARNING: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!
java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandles.privateLookupIn(Class,Lookup)Lookup/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:871)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
	at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.init(ReflectionHack.java:39)
	at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.<clinit>(ReflectionHack.java:34)
	at com.fasterxml.jackson.module.blackbird.util.ReflectionHack.privateLookupIn(ReflectionHack.java:24)
```

So, from next release you will need to choose one of them (in case you want/need it):

**Comment by raj8789** [comment]
jknack I am not clear with solution. I have same issue. Could  you help me out to resolve issue?

**Comment by jamwal25** [comment]
> 

whats the fix for this issue

**Comment by jknack** [comment]
BlackBird was removed. Either you want it back or you are using an older version:

```
ObjectMapper mapper = JacksonModule.create(<<add here your modules>>);
install(new JacksonModule(mapper));
```

**Comment by jamwal25** [comment]
why would it suddenly start showing this error
