### ISSUE TITLE
Request cancellation not supported?

### ISSUE THREAD

**Issue by maxpert** [jooby-project/jooby#2436]
So I am using Jooby with Kotlin coroutines, and I can consistently verify that on client cancelling the request the cancellation is not propagated, example:

```kotlin
            get ("/") {
                val j = coroutineScope.launch {
                    suspendCancellableCoroutine { cnt ->
                        cnt.invokeOnCancellation {
                            logger.info("Request cancelled...", it)
                        }
                    }
                }

                delay(10_000)
                j.cancel("Manually cancelled")
            }
```

Hit the server with basic `curl http://...` and terminate curl before 10 seconds. 

## Expected:
Cancellation should have been invoked with cancellation error coming from stack.

### Result:
Always hits manual cancellation which means main coroutine is never cancelled.

```
07:18:45.377 [handler-3] INFO  Main - Request cancelled...
java.util.concurrent.CancellationException: Manually cancelled
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:608)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source)
	at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:608)
	at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
	at com.gateway.LauncherKt$main$1$2$1.invokeSuspend(Launcher.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at net.openhft.affinity.AffinityThreadFactory$1.run(AffinityThreadFactory.java:60)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jknack** [comment]
I couldn't find how to do it. PR is welcome in case you want to do it.
