### ISSUE TITLE
Cannot intercept 404 not found errors if no routes match when using Netty

### ISSUE THREAD

**Issue by cbxp** [jooby-project/jooby#2438]
When installing `error {}` or `error(NOT_FOUND) {}` handlers, they are never called on 404 if the request path doesn't match any routes. It seems that in this case Netty returns it's own empty 404 response without going through any of Jooby filters/etc.

I think that filters for request logging/error handling/etc should still work for not matching 404 requests.

**Comment by jknack** [comment]
Can you add an example to reproduce it?

The default handler does the call https://github.com/jooby-project/jooby/blob/2.x/jooby/src/main/java/io/jooby/Route.java#L309

**Comment by cbxp** [comment]
It seems that the problem exists if you have `AssetsHandler` active, here is the code to reproduce:

```Kotlin
package app

import io.jooby.Kooby
import io.jooby.runApp

class DummyApp: Kooby({
  error { ctx, e, code -> println(e) }
  get("/hello") { "World" }
  assets("/*", "public")
})

fun main(args: Array<String>) {
  runApp(args, DummyApp::class)
}
```

If you remove the `assets` call, then error handler runs on 404. If the `assets` is there - no error handlers are called (404 empty response is hardcoded in AssetsHandler itself)

**Comment by jknack** [comment]
Right. So asset handler is like a module/component by it self. The reason on that is because browser usually ask for lot of extra things (map files, metadata, etc..). That is way anything not found by an asset handler is just silenced it (no error handler).

You have two options:

1. See if the single page app setup works for you: https://jooby.io/#static-files-spas
2. Add a custom asset source that throws an error

```java
AssetSource throwError = path -> throw new NotFoundException(path);

assets("/*", new AssetHandler(AssetSource.create(Paths.get("public"), throwError));
```

**Comment by nikolaosinlight** [comment]
> That is way anything not found by an asset handler is just silenced it (no error handler).

Hi @jknack - I have an Asset handler and it works great however when a resource is requested that is not found I get the following exception in our logs which concerns me with SPAM bots/etc.  Any way that I can trap 404's in the logs and simply produce a 1-liner as follows:

`404 (Not Found):  /register
`
vs.

```
753492 [eventloop-epoll-4-16] ERROR com.digitalstore.base.App - GET /register/ 404 Not Found
io.jooby.exception.NotFoundException: /register/
        at io.jooby.Route.lambda$static$c28b8fe8$1(Route.java:310)
        at io.jooby.internal.RouterMatch.execute(RouterMatch.java:87)
        at io.jooby.internal.netty.NettyHandler.channelRead(NettyHandler.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

```
