### ISSUE TITLE
Error Handler Imposes 500 on *any* Exception Thrown From CompletableFuture

### ISSUE THREAD

**Issue by Nyefan** [jooby-project/jooby#2452]
##To Reproduce:
* Build the following project
* `curl localhost:8080/healthz` returns 200
* `curl localhost:8080/cferror` returns 500

Is there a recommended workaround in the documentation or elsewhere which I am missing?

---
[build.gradle]
```gradle
plugins {
  id 'application'
  id 'java'
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenLocal()
  mavenCentral()
}

dependencies {
  implementation libs.jooby
  implementation libs.jooby.utow
  implementation libs.log4j.core
  implementation libs.log4j.slf4j.impl
}

application {
  // Define the main class for the application.
  mainClass = 'io.jooby.ErrorDemonstrationApplication'
}
```
---
[settings.gradle]
```gradle
enableFeaturePreview('VERSION_CATALOGS')

rootProject.name = 'joobypoc'

dependencyResolutionManagement {
  versionCatalogs {
    libs {
      version('jooby', '2.10.0')
      version('log4j2', '2.14.1')

      alias('jooby').to('io.jooby', 'jooby').versionRef('jooby')
      alias('jooby-utow').to('io.jooby', 'jooby-utow').versionRef('jooby')

      alias('log4j-core').to('org.apache.logging.log4j', 'log4j-core').versionRef('log4j2')
      alias('log4j-slf4j-impl').to('org.apache.logging.log4j', 'log4j-slf4j-impl').versionRef('log4j2')
    }
  }
}
```
---
[src/main/java/io.jooby.ErrorDemonstrationApplication.java]
```java
package io.jooby;

import io.jooby.exception.StatusCodeException;

import java.util.concurrent.CompletableFuture;

public class ErrorDemonstrationApplication extends Jooby {
  {
    decorator(new AccessLogHandler());

    get("/healthz", ctx -> "");
    get("/cferror", ctx -> CompletableFuture.supplyAsync(
        () -> {
          throw new StatusCodeException(StatusCode.NOT_FOUND);
        }
    ));
  }

  public static void main(String[] args) {
    runApp(args, ErrorDemonstrationApplication::new);
  }
}
```
---
[stack trace]
```java
12:23:14.677 [ForkJoinPool.commonPool-worker-3] ERROR io.jooby.ErrorDemonstrationApplication - GET /cferror 500 Server Error
java.util.concurrent.CompletionException: io.jooby.exception.StatusCodeException: Not Found (404)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
Caused by: io.jooby.exception.StatusCodeException: Not Found (404)
	at io.jooby.ErrorDemonstrationApplication.lambda$new$0(ErrorDemonstrationApplication.java:14) ~[main/:?]
Caused by: io.jooby.exception.StatusCodeException: Not Found (404)

	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 6 more
```

**Comment by jknack** [comment]
Hi,

you need a custom error handler: https://jooby.io/#error-handler that basically unwrap the `CompletionException`. That will be a workaround.

will do something in next. release to handle this automatically.

**Comment by Nyefan** [comment]
Pending the release, I have added the following to my static initializer (for anyone searching for this in the future):

```java
error(CompletionException.class, (ctx, cause, statusCode) -> {
  log.error("unwrapping CompletionException - see https://github.com/jooby-project/jooby/issues/2452", cause); //This is not strictly necessary except that it guarantees that the original and overridden error messages will be colocated in the logs
  ctx.sendError(cause.getCause());
});
```

Please let me know if this is poor practice in some way.  Thank You.

**Comment by jknack** [comment]
looks perfect.
