### ISSUE TITLE
ArrayIndexOutOfBoundsException in RequestImpl.port() method

### ISSUE THREAD

**Issue by silentcharacter** [jooby-project/jooby#250]
I'm running jooby app behind public domain on port 80. When I open private page I get:

org.jooby.Err: Server Error(500)
	at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:252) [jooby-0.12.0.jar!/:na]
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:197) [jooby-0.12.0.jar!/:na]
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:85) [jooby-netty-0.12.0.jar!/:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.0.33.Final.jar!/:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) [netty-transport-4.0.33.Final.jar!/:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:42) [netty-transport-4.0.33.Final.jar!/:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:309) [netty-transport-4.0.33.Final.jar!/:4.0.33.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [netty-common-4.0.33.Final.jar!/:4.0.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.33.Final.jar!/:4.0.33.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.33.Final.jar!/:4.0.33.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.jooby.internal.RequestImpl.lambda$port$10(RequestImpl.java:299) ~[jooby-0.12.0.jar!/:na]
	at org.jooby.internal.RequestImpl$$Lambda$124/1030697208.apply(Unknown Source) ~[na:na]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_45]
	at org.jooby.internal.RequestImpl.port(RequestImpl.java:299) ~[jooby-0.12.0.jar!/:na]
	at org.jooby.internal.pac4j.AuthContext.getServerPort(AuthContext.java:131) ~[jooby-pac4j-0.12.0.jar!/:na]
	at org.jooby.internal.pac4j.AuthContext.getFullRequestURL(AuthContext.java:141) ~[jooby-pac4j-0.12.0.jar!/:na]
	at org.jooby.internal.pac4j.AuthFilter.handle(AuthFilter.java:104) ~[jooby-pac4j-0.12.0.jar!/:na]
	at org.jooby.internal.pac4j.FormFilter.handle(FormFilter.java:94) ~[jooby-pac4j-0.12.0.jar!/:na]
	at org.jooby.pac4j.Auth.lambda$null$8(Auth.java:410) ~[jooby-pac4j-0.12.0.jar!/:na]
	at org.jooby.pac4j.Auth$$Lambda$70/1190318386.handle(Unknown Source) ~[na:na]
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:86) ~[jooby-0.12.0.jar!/:na]
	at org.jooby.internal.RouteChain.next(RouteChain.java:59) ~[jooby-0.12.0.jar!/:na]
	at org.jooby.Route$Chain.next(Route.java:1444) ~[jooby-0.12.0.jar!/:na]
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:191) [jooby-0.12.0.jar!/:na]
	... 9 common frames omitted

**Comment by jknack** [comment]
add a root at the top of your app (before pac4j Auth) and print the ```host``` header:

```java
get("*", (req, rsp) -> {
   System.out.println(req.header("host").value("missing")); 
});
```

**Comment by silentcharacter** [comment]
host is "3edfd8c1.ngrok.io"
there is no port, so org.jooby.internal.RequestImpl.port throws ArrayIndexOutOfBoundsException

**Comment by jknack** [comment]
yea, thought always was a port but probably not for default port: 80

will fix it

**Comment by jknack** [comment]
btw, can you edit/update bug subject?

**Comment by silentcharacter** [comment]
thank you! is this subject ok?

**Comment by jknack** [comment]
perfect!
