### ISSUE TITLE
Cannot invoke "java.util.LinkedList.getLast()" because "this.stack" is null

### ISSUE THREAD

**Issue by webleaf** [jooby-project/jooby#2507]
I try to use `assets()` to specify `PATH` outside project dir, where my static files located.
When I try, for examle, `assets("/any/path")` for that, I get
```
Server Error
message: Cannot invoke "java.util.LinkedList.getLast()" because "this.stack" is null
status code: 500
```
Stacktrace is:
```
[worker-1-1] ERROR io.jooby.Kooby - GET / 500 Server Error
java.lang.NullPointerException: Cannot invoke "java.util.LinkedList.getLast()" because "this.stack" is null
	at test//io.jooby.internal.RouterImpl.newRoute(RouterImpl.java:453)
	at test//io.jooby.internal.RouterImpl.route(RouterImpl.java:448)
	at test//io.jooby.Jooby.route(Jooby.java:548)
	at test//io.jooby.Kooby.route(Kooby.kt:240)
	at test//io.jooby.Router.assets(Router.java:787)
	at test//io.jooby.Router.assets(Router.java:776)
	at test//MainKt$main$1$1.invoke(Main.kt:14)
	at test//MainKt$main$1$1.invoke(Main.kt:12)
	at test//io.jooby.Kooby$route$1.apply(Kooby.kt:245)
	at test//io.jooby.internal.handler.DefaultHandler.apply(DefaultHandler.java:23)
	at test//io.jooby.internal.handler.WorkerHandler.lambda$apply$0(WorkerHandler.java:23)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at test//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by jknack** [comment]
Hi, 

 I need an example to reproduce it.

Thanks.

**Comment by webleaf** [comment]
`assets("/")`

**Comment by jknack** [comment]
Don't use that for now... need to update doc and probably remove it. It is wrongly initializing assets without a source.

If you have an external dir, try:

```
assets("/*", Paths.get("mydir"));
```

**Comment by webleaf** [comment]
Same result (this is exactly where I initially got stuck).

for example, such code `assets("/", Paths.get("doc"))` produce
```
Not Found
message: /home/user/.gradle/daemon/7.1/doc
status code: 404
```
But if I do `assets("/", Paths.get("/"))`, i get
```
Server Error
message: Cannot invoke "java.util.LinkedList.getLast()" because "this.stack" is null
status code: 500
```

**Comment by webleaf** [comment]
In short, it looks like all relative paths look relative to `/home/user/.gradle/daemon/7.1/`
and all absolute ones cause an error `Cannot invoke "java.util.LinkedList.getLast()" because "this.stack" is null`

**Comment by jknack** [comment]
The dir `/home/user/.gradle/daemon/7.1/` is set by gradle, you can try  `Paths.get(System.getProperty("user.dir"), "doc")` and that (think) should give you your project dir.

Try `assets("/*", Paths.get("/"))`, please note the `*` at the end of the path and don't forget to remove the access to the entire file system.

**Comment by jknack** [comment]
I can't reproduce it:

```
{
  assets("/"); // or assets("/*");
}
```

    GET /any/path

Gives a `404`

I'm happy to review again, just need a valid way to reproduce it
