### ISSUE TITLE
Websocket idle cleanup close causing exception in undertow

### ISSUE THREAD

**Issue by U1F984** [jooby-project/jooby#2722]
Starting a jooby app with undertow results in this exception after a couple of minutes:

```
[worker I/O-5] ERROR io.jooby.Kooby - Websocket resulted in exception: /test
java.io.IOException: UT002002: Channel is closed
	at io.undertow.websockets.core.WebSocketChannel.send(WebSocketChannel.java:354)
	at io.undertow.websockets.core.WebSockets.sendInternal(WebSockets.java:906)
	at io.undertow.websockets.core.WebSockets.sendInternal(WebSockets.java:900)
	at io.undertow.websockets.core.WebSockets.sendClose(WebSockets.java:856)
	at io.undertow.websockets.core.WebSockets.sendClose(WebSockets.java:831)
	at io.jooby.internal.utow.UtowWebSocket.handleClose(UtowWebSocket.java:251)
	at io.jooby.internal.utow.UtowWebSocket.onCloseMessage(UtowWebSocket.java:241)
	at io.undertow.websockets.core.AbstractReceiveListener.onFullCloseMessage(AbstractReceiveListener.java:189)
	at io.undertow.websockets.core.AbstractReceiveListener$1.complete(AbstractReceiveListener.java:136)
	at io.undertow.websockets.core.AbstractReceiveListener$1.complete(AbstractReceiveListener.java:124)
	at io.undertow.websockets.core.BufferedBinaryMessage.read(BufferedBinaryMessage.java:95)
	at io.undertow.websockets.core.AbstractReceiveListener.readBufferedBinary(AbstractReceiveListener.java:124)
	at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:98)
	at io.undertow.websockets.core.AbstractReceiveListener.onClose(AbstractReceiveListener.java:62)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:50)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:959)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:939)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.conduits.IdleTimeoutConduit$1.run(IdleTimeoutConduit.java:84)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
```

Jooby version: 2.16.1

**Comment by jknack** [comment]
There is a default timeout of 5 minutes. You need to set `websocket.idleTimeout` to something else. If you set to `0`, no timeout occurs.

I probably need to make this log.debug statetement.
