### ISSUE TITLE
Exception when using RAML with MVC Routes

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#297]
Hello, check this out:

I get this exception when I try to use the RAML module with MVC routes:

``java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class``

This is how I'm using:

``new Raml().install(this);``

I've also tried like this:

``new Raml().filter(routeSpec -> routeSpec.pattern().startsWith("/user")).install(this);``

To no avail.

Do you know what I might be doing wrong?

Thanks

**Comment by jknack** [comment]
saw this before... it is bug in JavaParser.

Can you isolate and reproduce the problem in a single use case?

**Comment by paulovictorv** [comment]
Got it.

The issue is when you have routes defined with wildcards, such as:

`` get("/app/**", () -> "a"); ``

If I comment out this route, the exception is not thrown anymore. But still, no documentation is generated for my MVC routes, although I can see your debug logs when parsing the source code.

When opening the route provided by the module, I get an infinite message "loading RAML".

PS: is there a way to disable this debug logging?

**Comment by jknack** [comment]
I can't reproduce it.

Creating an app with just:

```
get("/app/**", () -> "a");
```
works as expected.

Need you to create an app and run ```mvn jooby:spec``` to reproduce the error.

Can you paste the stacktrace?

What logging message are you referring to?

**Comment by paulovictorv** [comment]
Have you tried using the RAML filter? It only happens for me when there's a route defined using ``get()`` syntax, not for MVC defined routes. 

``new Raml().filter(routeSpec -> routeSpec.pattern().startsWith("/app"))``

Check this snippet:
`` 
        use("/user/:userId/**", (request, response) -> {
            try {
                authenticate(request, response, request.param("userId").value());
            } catch (WrongIdParameterException e) {
                response.status(403)
                        .type("application/json")
                        .send(new JsonMapperObject().toJson(e.mapToJsonResponse()));
            } catch (TokenException e){
                response.status(401)
                        .type("application/json")
                        .send(new JsonMapperObject().toJson(e.mapToJsonResponse()));
            }
        });
``
And this is my filter:

``new Raml().filter(routeSpec -> routeSpec.pattern().startsWith("/user")).install(this);``

Stack trace:

``
org.jooby.Err: Server Error(500)
        at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:335) [jooby-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:278) [jooby-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:85) [jooby-netty-0.15.1.jar!/:0.15.1]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
        at io.netty.channel.DefaultChannelHandlerInvoker$7.run(DefaultChannelHandlerInvoker.java:159) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:56) [netty-common-4.1.0.CR3.jar!/:4.1.0.CR3]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-common-4.1.0.CR3.jar!/:4.1.0.CR3]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.1.0.CR3.jar!/:4.1.0.CR3]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class
        at org.jooby.internal.raml.RamlType.toClass(RamlType.java:225) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlType.componentType(RamlType.java:230) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlType.simpleParse(RamlType.java:161) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlType.parse(RamlType.java:140) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlType.parse(RamlType.java:150) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlType.parse(RamlType.java:150) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlType.parse(RamlType.java:150) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlType.parseAll(RamlType.java:133) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlBuilder.lambda$build$21(RamlBuilder.java:274) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.raml.RamlBuilder.lambda$build$23(RamlBuilder.java:283) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_74]
        at org.jooby.internal.raml.RamlBuilder.build(RamlBuilder.java:279) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.raml.Raml.lambda$install$31(Raml.java:325) ~[jooby-raml-0.15.1.jar!/:0.15.1]
        at org.jooby.Route$OneArgHandler.handle(Route.java:1370) ~[jooby-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:87) ~[jooby-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.RouteChain.next(RouteChain.java:60) ~[jooby-0.15.1.jar!/:0.15.1]
        at org.jooby.Route$Chain.next(Route.java:1444) ~[jooby-0.15.1.jar!/:0.15.1]
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:272) [jooby-0.15.1.jar!/:0.15.1]
        ... 8 common frames omitted
``
If I comment out the ``get`` definition, the exception is not thrown anymore but there's no RAML available.

**Comment by jknack** [comment]
found it!

somewhere in your data you have a wildcard type, like: ```List<? extends Type>``` or ```List<? super Type>``` or something very similar...

**Comment by paulovictorv** [comment]
Hmm.. I've been inspecting the code to the deepest layer and I cannot find any wildcard types (it's not a commom practice between my team).

Also, this error is only thrown when I leave the ``use(...)`` declaration uncommented. If I comment it out, there's no more errors but the documentation is not generated...

**Comment by jknack** [comment]
yea, that is what I got from stacktrace (wasn't able to reproduce it)

just push can you build and try it with master?

**Comment by paulovictorv** [comment]
Ok, will do.

**Comment by paulovictorv** [comment]
Sorry for the delay.

I've tested it with this version, but now I get a different error:

https://gist.github.com/paulovictorv/ae3d1efd21491a89445a

Also, there was a missing closing tag on the pom.xml. I can fix it if you want.

**Comment by jknack** [comment]
fixed. please try it again

**Comment by paulovictorv** [comment]
Done. No more errors.

However, the RAML file is generated with a bunch of types that I believe are obtained by inspecting the source code. See the sample:

https://gist.github.com/paulovictorv/289f3032fab0c22c1724

I initially thought that it was inspecting the member variables and rendering them as RAML types, but I removed all member variables and the types are still generated..

I can't post the whole RAML for reasons ;)

**Comment by jknack** [comment]
seems you return/read some Jackson objects?

can you give me one example?

**Comment by jknack** [comment]
well, actually think you should read the doc: http://jooby.org/doc/spec and learn how to use the module

please read it and let me know if you have questions

**Comment by paulovictorv** [comment]
OK. It went completely over my head that you needed to explicitly set the return type. My bad.

But also, the docs cover a lot of the scripting style and not very much about the MVC routes, and that's why I got confused: I thought it was just a plug-n-play solution, and it didn't matter how the methods were written. 

But that's fine :) I will try to work a little bit on this documentation during the weekend.

Thanks

**Comment by jknack** [comment]
You're right about scripting style... MVC routes don't require much bc all the information is already present via reflection. We took param and return types from method definitions.

Still your routes (scripts or mvc) must/need to work with business object and not with technology specific objects.

Anyway, there is a ```workaround``` for return type. You basically set the return type via javadoc: http://jooby.org/doc/spec/#definition-response
The workaround applies for mvc or script routes:

```java
/**
 *
 * @return Returns a {@link BusinessObject}
 */
public Raw myrouter() {
   ...
}
```

here you returns whatever you want but annotated your returns javadoc with: ```{@link MyType}```

**Comment by noboomu** [comment]
Does this workaround apply to Swagger as well? Looking for a way to override a Deferred response with a different class.

**Comment by jknack** [comment]
Yes, it does work. There is an abstraction layer (called route spec) that handle all these and then produces RAML or Swagger
