### ISSUE TITLE
[3.0.1] joobyRun does not work with Kotlin MPP

### ISSUE THREAD

**Issue by rjaros** [jooby-project/jooby#3061]
Some changes in 3.0.1 (probably the new classloader strategy) breaks `joobyRun` gradle task when using Jooby inside Kotlin multiplatform project. In my case I have this exception
```
io.jooby.exception.StartupException: Application initialization resulted in exception
        at jars//io.jooby.Jooby.createApp(Jooby.java:1211)
        at jars//io.jooby.Jooby.runApp(Jooby.java:1172)
        at jars//io.jooby.kt.KoobyKt.runApp(Kooby.kt:343)
        at addressbook-fullstack-jooby//com.example.MainKt.main(Main.kt:19)
Caused by: java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required.
        at jars//com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:1026)
        at jars//com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:77)
        at jars//io.jooby.hikari.HikariModule.install(HikariModule.java:212)
        at jars//io.jooby.Jooby.install(Jooby.java:554)
        at addressbook-fullstack-jooby//com.example.MainKt$main$1.invoke(Main.kt:21)
        at addressbook-fullstack-jooby//com.example.MainKt$main$1.invoke(Main.kt:19)
        at jars//io.jooby.kt.Kooby.<init>(Kooby.kt:143)
        at jars//io.jooby.kt.KoobyKt.runApp$lambda$1(Kooby.kt:343)
        at jars//io.jooby.Jooby.createApp(Jooby.java:1204)
        at jars//io.jooby.Jooby.runApp(Jooby.java:1172)
        at jars//io.jooby.kt.KoobyKt.runApp(Kooby.kt:343)
        at addressbook-fullstack-jooby//com.example.MainKt.main(Main.kt:19)
        at org.jboss.modules.Module.run(Module.java:352)
        at io.jooby.run.JoobyRun$AppModule.start(JoobyRun.java:104)
        at io.jooby.run.JoobyRun.start(JoobyRun.java:362)
        at io.jooby.gradle.RunTask.run(RunTask.java:157)

```
I suspect Jooby can't find `application.conf` from the `resources` directory. This is working correctly in 3.0.0.

**Comment by jknack** [comment]
I see, do you have a sample project?

**Comment by rjaros** [comment]
Yes
https://github.com/rjaros/jooby-issue-3061

**Comment by jknack** [comment]
The issue is here:

```
runApp(args) {
        println(this.classLoader) // HERE

        install(HikariModule("db"))
        onStarted {
            val db = require(DataSource::class, "db")
        }
    }
```

This will be io.jooby.Jooby/io.jooby.kt.Kooby these are loaded in the `jars` classloader so they don't have access to the application resources. Instead if we have a class here, like:

```
runApp(args, ::App)
```

It should works. I didn't try in Java yet, but I'm sure we have the same issue.

**Comment by jknack** [comment]
Confirmed the same issue with maven+java:

```
public static void main(final String[] args) {
    runApp(args, app -> {
      var config = app.getConfig();
      System.out.println(config.getString("db"));
      app.get("/", ctx -> "Works");
    });
  }
```

and yes, you're right is a side effect of #3018
