### ISSUE TITLE
Support Java 21 for Jooby 2.x

### ISSUE THREAD

**Issue by froque** [jooby-project/jooby#3195]
Compiling and running with jdk 21 produces this:

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at io.jooby.internal.$shaded.asm.ClassReader.<init>(ClassReader.java:199)
	at io.jooby.internal.$shaded.asm.ClassReader.<init>(ClassReader.java:180)
	at io.jooby.internal.$shaded.asm.ClassReader.<init>(ClassReader.java:166)
	at io.jooby.internal.RouteAnalyzer.returnType(RouteAnalyzer.java:44)
	at io.jooby.internal.RouterImpl.start(RouterImpl.java:555)
	at io.jooby.Jooby.start(Jooby.java:865)
	at io.jooby.Server$Base.fireStart(Server.java:93)
	at io.jooby.jetty.Jetty.start(Jetty.java:96)
	at io.jooby.Jooby.start(Jooby.java:805)
	... 3 more
```

**Comment by jknack** [comment]
2.16.3 is on central
