### ISSUE TITLE
Coroutine route in an MVC router is broken.

### ISSUE THREAD

**Issue by zzj37** [jooby-project/jooby#3229]
The code from official document [https://jooby.io/#mvc-api-responses-nonblocking](https://jooby.io/#mvc-api-responses-nonblocking) does not compile because `use()` method requires an argument of type `Filter`.

If use `mvc()` instead of `use()`:

```kotlin
class SuspendMvc {
    @GET
    @Path("/delay")
    suspend fun delayed(ctx: Context): String {
        delay(100)
        return ctx.getRequestPath()
    }
}

fun main(args: Array<String>) {
    runApp(args) {
        // use(SuspendMvc())
        mvc(SuspendMvc())
    }
}
```

then a request to `/delay` will result in the following error:

```
[worker-1-1] ERROR io.jooby.kt.Kooby - GET /delay 400 Bad Request
io.jooby.exception.MissingValueException: Missing value: 'coroutineRouter'
	at io.jooby.Router.attribute(Router.java:158)
	at io.jooby.Jooby.attribute(Jooby.java:714)
	at io.jooby.internal.kt.CoroutineLauncher.apply(CoroutineLauncher.kt:18)
	at io.jooby.internal.kt.CoroutineLauncher.apply(CoroutineLauncher.kt:15)
	at io.jooby.internal.handler.DefaultHandler.lambda$apply$e67b40fd$1(DefaultHandler.java:21)
	at io.jooby.Route$Filter.lambda$then$e67b40fd$1(Route.java:91)
	at io.jooby.internal.handler.WorkerHandler.lambda$apply$0(WorkerHandler.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jknack** [comment]
The doc isn't correct. Look here: https://jooby.io/#responses-nonblocking-kotlin-coroutines

You always need:

`{
  coroutine {
    lambda routes or mvc
  }
}`

In your example:

`fun main(args: Array<String>) {
    runApp(args) {
        coroutine {
          mvc(SuspendMvc())
        }
    }
}`

can you fix the doc and send a PR?

Thanks

**Comment by zzj37** [comment]
It works. Thank you!
