### ISSUE TITLE
Route error public assert

### ISSUE THREAD

**Issue by felipepasc** [jooby-project/jooby#3244]
<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 java.lang.NullPointerException: Cannot load from object array because "this.children" is null</h2>

URI: | /public/css/app.min.css
-- | --
500
java.lang.NullPointerException: Cannot load from object array because "this.children" is null
io.jooby.internal.jetty.JettyServlet-287f94b1
java.lang.NullPointerException: Cannot load from object array because "this.children" is null

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">java.lang.NullPointerException: Cannot load from object array because "this.children" is null
	at io.jooby.internal.Chi$Node.findRoute(Chi.java:440)
	at io.jooby.internal.Chi.findInternal(Chi.java:781)
	at io.jooby.internal.Chi.find(Chi.java:771)
	at io.jooby.internal.RouterImpl.match(RouterImpl.java:722)
	at io.jooby.Jooby.match(Jooby.java:605)
	at io.jooby.internal.jetty.JettyServlet.service(JettyServlet.java:40)</pre>
</body>
</html>

        routes(() -> {
            // serve index page or favicon
            assets("/public/*", new AssetHandler(AssetSource.create(MasterModule.class.getClassLoader(), "/public/"))
                    .setMaxAge(Duration.ofDays(1))
                    .setLastModified(false)
                    .setETag(false)
            );
        });
        
        
![image](https://github.com/jooby-project/jooby/assets/64669985/d551cd55-d33f-43c9-8265-6178733cc85d)

**Comment by felipepasc** [comment]
![image](https://github.com/jooby-project/jooby/assets/64669985/0dbedd20-2809-4ccc-b826-56b11e8098a4)
![image](https://github.com/jooby-project/jooby/assets/64669985/b55bedcf-3730-4ecc-b06a-f5b3eaa68bf4)
