### ISSUE TITLE
The quick-start installation isn't working

### ISSUE THREAD

**Issue by jtlapp** [jooby-project/jooby#3536]
The [quick-start docs](https://jooby.io/v1/quickstart/) say to run this line:

```
mvn archetype:generate -B -DgroupId=com.mycompany -DartifactId=my-app -Dversion=1.0-SNAPSHOT -DarchetypeArtifactId=jooby-archetype -DarchetypeGroupId=org.jooby -DarchetypeVersion=1.6.6
```

I adapted it as follows:

```
mvn archetype:generate -B -DgroupId=com.joelapp.joobyapp -DartifactId=jooby-app -Dversion=0.1.0-SNAPSHOT -DarchetypeArtifactId=jooby-archetype -DarchetypeGroupId=org.jooby -DarchetypeVersion=1.6.6
```

When I cd into the directory and run `mvn jooby:run`, I get this exception:

```
[2024-09-22 08:52:23,125]-[Hotswap] INFO  com.joelapp.joobyapp.App - Stopped
[2024-09-22 08:52:23,127]-[Hotswap] ERROR com.joelapp.joobyapp.App - An error occurred while starting the application:
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.FailableCache.get(FailableCache.java:51)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:154)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:581)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:176)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.Guice.createInjector(Guice.java:87)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.Guice.createInjector(Guice.java:78)
	at com.joelapp.joobyapp.jooby-app//org.jooby.Jooby.lambda$new$0(Jooby.java:885)
	at com.joelapp.joobyapp.jooby-app//org.jooby.Jooby.bootstrap(Jooby.java:2996)
	at com.joelapp.joobyapp.jooby-app//org.jooby.Jooby.start(Jooby.java:2197)
	at com.joelapp.joobyapp.jooby-app//org.jooby.Jooby.start(Jooby.java:2178)
	at com.joelapp.joobyapp.jooby-app//org.jooby.Jooby.run(Jooby.java:2107)
	at com.joelapp.joobyapp.jooby-app//com.joelapp.joobyapp.App.main(App.java:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jooby.run.Main.lambda$startApp$3(Main.java:444)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.FailableCache.get(FailableCache.java:51)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:154)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:595)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.createParameterInjector(InjectorImpl.java:990)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.InjectorImpl.getParametersInjectors(InjectorImpl.java:978)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:68)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 28 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:49)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:156)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:90)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.joelapp.joobyapp.jooby-app//com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 51 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:25)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	... 68 common frames omitted
Caused by: com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @686e391e
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:464)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$KeyFactory$Generator.create(KeyFactory.java:221)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:174)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:157)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:149)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:145)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$MethodWrapper.<clinit>(MethodWrapper.java:23)
	... 79 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @686e391e
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:197)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$ReflectUtils$1.run(ReflectUtils.java:61)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:52)
	at com.joelapp.joobyapp.jooby-app//com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
	... 76 common frames omitted
```

And no other output. It hangs (or is in a running state) and requires a `kill`.

```
% java --version
openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
```

**Comment by jknack** [comment]
Hi,

 That is the docs for 1.x which isn't supported but also it must run on Java 1.8. For recent jooby just follow these steps: https://jooby.io/#getting-started

**Comment by jtlapp** [comment]
Okay thanks. I just figured that out. Plus, I've been trying work things on Jooby.org and only just realized that's obsolete too. This has been a frustrating start, but I'm thrilled that the repo is well-maintained.
