### ISSUE TITLE
netty/jetty: HTTP Outputstream.close method must close once and ignore any other call

### ISSUE THREAD

**Issue by hidemikimura** [jooby-project/jooby#3554]
Error log is output when CompletableFuture is used.
```
ExecutorService threadPool = Executors.newVirtualThreadPerTaskExecutor()

ServerOptions serverOptions = new ServerOptions()
	.setPort(9000)
	.setDefaultHeaders(false);
setServerOptions(serverOptions);

use(ReactiveSupport.concurrent());
setExecutionMode(ExecutionMode.EVENT_LOOP);
install(new NettyServer());

get("/", ctx -> CompletableFuture.supplyAsync(() -> {
	try (
		OutputStream os = ctx.responseStream();
		BufferedOutputStream bos = new BufferedOutputStream(os)
	) {
		bos.write("test".getBytes(StandardCharsets.UTF_8));
	} catch (Exception ex) {
		throw new RuntimeException(ex);
	}
	return ctx;
}, threadPool));
```

output log
```
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: LastHttpContent$1, state: 0
	at io.netty.handler.codec.http.HttpObjectEncoder.write(HttpObjectEncoder.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
	at io.netty.handler.stream.ChunkedWriteHandler.write(ChunkedWriteHandler.java:140)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1263)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:428)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:377)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:557)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: unexpected message type: LastHttpContent$1, state: 0
	at io.netty.handler.codec.http.HttpObjectEncoder.throwUnexpectedMessageTypeEx(HttpObjectEncoder.java:364)
	at io.netty.handler.codec.http.HttpObjectEncoder.encodeNotHttpMessageContentTypes(HttpObjectEncoder.java:270)
	at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:184)
	at io.netty.handler.codec.http.HttpObjectEncoder.write(HttpObjectEncoder.java:100)
	... 17 common frames omitted
```

**Comment by jknack** [comment]
Here is the issue:

```
try (
		OutputStream os = ctx.responseStream();
		BufferedOutputStream bos = new BufferedOutputStream(os)
	)
```

The responseStream().close() is called twice: 1) on `os` and then 2) on `bos`.

Here is a simple fix:

```
try (
		BufferedOutputStream bos = new BufferedOutputStream(ctx.responseStream())
	)
```

Still, will add a check so we don't attempt to close twice.
