### ISSUE TITLE
`AssetHandler` overridden in in `Request.assets(String, AssetHandler)`

### ISSUE THREAD

**Issue by authchir** [jooby-project/jooby#356]
I was trying to configure some aspects of my assets and encountered a strange situation where some configuration (i.e. `maxAge`) was working bug others (i.e. `etag` and `lastModified`). Here is a small example tuned for testing:

```Java
assets("/assets/css/**", new AssetHandler("/").etag(false).lastModified(false).maxAge(Duration.ofDays(1).getSeconds()));
assets("/assets/img/**", new AssetHandler("/").etag(false).lastModified(true).maxAge(Duration.ofDays(14).getSeconds()));
assets("/assets/js/**",  new AssetHandler("/").etag(true).lastModified(false).maxAge(Duration.ofDays(2).getSeconds()));
assets("/i18n/**",       new AssetHandler("/").etag(true).lastModified(true).maxAge(Duration.ofDays(7).getSeconds()));
```

The value given for `etag` and `lastModified` is always ignored. I searched in the implementation of `AssetHandler` but everything seems fine. I then inspected the implementations of the different `Request.assets` functions and found that the values of `AssetHandler.cdn`, `AssetHandler.lasModified` and `AssetHandler.etag` are always overridden with the value given in the configuration file:

```Java
@Override
public Route.Definition assets(final String path, final AssetHandler handler) {
  AssetProxy router = new AssetProxy();
  Route.Definition asset = new Route.Definition("GET", path, router);
  on("*", conf -> {
    router.fwd(handler
      .cdn(conf.getString("assets.cdn"))
      .lastModified(conf.getBoolean("assets.lastModified"))
      .etag(conf.getBoolean("assets.etag")));
  });
  return appendDefinition(asset);
}
```

I guess it was so written, so that the default `AssetHandler` created by the other functions would be initialized, but it actually prevents us to specify a fine-grained configuration for different assets. I think this behaviour should be moved to the other `assets` functions.

What are your thoughts?

PS: Quite of topic but, since the framework is already Java 8, I would suggest using the nice [`java.time.Duration`][1] class for the `maxAge` attribute.

[1]: https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html

**Comment by jknack** [comment]
Agreed, will review, cleanup and fix... forgot to do it before 1.0.0.CR1 ... think I can remove AssetProxy now.

```Duration``` makes perfect sense will add that too. Good suggestion

**Comment by authchir** [comment]
Nice. If you want, I can do it a send a pull request.

**Comment by jknack** [comment]
that will be awesome! Try to remove the AssetProxy entirely. It is there to ensure the "order" of the asset route... but then I fixed the order while using ```on``` callbacks... so it shouldn't be necessary now.

So can you please fix the explicit set of the attributes (or fallback to conf) and remove the AssetProxy? 

Let me know if you have questions.

**Comment by authchir** [comment]
I wrote a small patch but fail to write the test case properly. You can see the commit [here][1]. The tests need to refer to some static assets. I tried with some already existing resources I found lying around, but the following error is produced:

```
Running org.jooby.issues.Issue356                                                                                                                                 [7472/9540]
INFO  [2016-04-18 13:48:42,796] [main] org.jooby.issues.Issue356: [dev@undertow]: Server started in 24ms

  GET /file.css       [*/*]     [*/*]    (/anonymous)
  GET /favicon.ico    [*/*]     [*/*]    (/anonymous)
  GET /file.js        [*/*]     [*/*]    (/anonymous)
  GET /empty.css      [*/*]     [*/*]    (/anonymous)

listening on:
  http://localhost:9999/

ERROR [2016-04-18 13:48:42,800] [utow task-1] org.jooby.Err: execution of: GET/ resulted in exception
org.jooby.Err: Not Found(404): /
        at org.jooby.internal.HttpHandlerImpl.lambda$routes$7(HttpHandlerImpl.java:389) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:105) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.RouteChain.next(RouteChain.java:70) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.Route$Chain.next(Route.java:1943) ~[jooby-1.0.0.CR3.jar:na]
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:287) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.undertow.UndertowHandler.handleRequest(UndertowHandler.java:59) [jooby-undertow-1.0.0.CR3.jar:1.0.0.CR3]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202) [undertow-core-1.3.20.Final.jar:1.3.20.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:792) [undertow-core-1.3.20.Final.jar:1.3.20.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]
ERROR [2016-04-18 13:48:42,805] [utow task-2] org.jooby.Err: execution of: GET/file.css resulted in exception
org.jooby.Err: Unsupported Media Type(415): */*
        at org.jooby.internal.HttpHandlerImpl.handle406or415(HttpHandlerImpl.java:484) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.HttpHandlerImpl.lambda$routes$7(HttpHandlerImpl.java:380) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:105) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.RouteChain.next(RouteChain.java:70) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.Route$Chain.next(Route.java:1943) ~[jooby-1.0.0.CR3.jar:na]
        at org.jooby.Route$Handler.handle(Route.java:1536) ~[jooby-1.0.0.CR3.jar:na]
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:105) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.RouteChain.next(RouteChain.java:70) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.Route$Chain.next(Route.java:1943) ~[jooby-1.0.0.CR3.jar:na]
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:287) ~[jooby-1.0.0.CR3.jar:1.0.0.CR3]
        at org.jooby.internal.undertow.UndertowHandler.handleRequest(UndertowHandler.java:59) [jooby-undertow-1.0.0.CR3.jar:1.0.0.CR3]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202) [undertow-core-1.3.20.Final.jar:1.3.20.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:792) [undertow-core-1.3.20.Final.jar:1.3.20.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]

```

[1]: https://github.com/authchir/jooby/commit/5dba36f242d690f33d990fe92e5de9e1ad6f7a7b

**Comment by jknack** [comment]
Your pull request looks good!

I think it can't found the static resources... if found a patch/match but not a resources. Try one of these:

```java
assets("/assets/file.css",
     new AssetHandler("/").etag(false).lastModified(false).maxAge(86400));
```

or

```java
assets("/file.css",
     new AssetHandler("/assets/").etag(false).lastModified(false).maxAge(86400));
```

Also, the 415 error is probably wrong here it should be a 404.

**Comment by jknack** [comment]
nice work you did here. I didn't have to change anything!

Thanks a lot!
