### ISSUE TITLE
[jooby-servlet] deploy  restful-app  in the tomcat9, error message?

### ISSUE THREAD

**Issue by timloo0710** [jooby-project/jooby#483]
My Env is Win 10,  Apache Tomcat/9.0.0.M10, Java virtual mechine C:\Program Files\Java\jre1.8.0_101\bin\server\jvm.dll, 

I modifiy  the sample : restful jdbi,  db connect to oracle,  
What it ran  "mvn  exec:java" was  ok , but deploy it in the Tomcat (Above setting) was not . 

I use 
 <dependency>
        <groupId>org.jooby</groupId>
        <artifactId>jooby-servlet</artifactId>
        <version>0.16.0</version>
    </dependency>
, 

The error is clearly, but I can not figure out what happened!

22-Sep-2016 15:09:13.885 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.jooby.servlet.ServerInitializer
 java.lang.IllegalStateException: App didn't to start: restfuljdbi.App
    at org.jooby.servlet.ServerInitializer.contextInitialized(ServerInitializer.java:65)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4717)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
.........................................................
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: Error found on module: org.jooby.jdbi.Jdbi
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

1 error
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
    at com.google.inject.Guice.createInjector(Guice.java:96)
    at com.google.inject.Guice.createInjector(Guice.java:84)
    at org.jooby.Jooby.bootstrap(Jooby.java:3122)
    at org.jooby.Jooby.start(Jooby.java:3036)
    at org.jooby.Jooby.start(Jooby.java:3004)
    at org.jooby.servlet.ServerInitializer.contextInitialized(ServerInitializer.java:60)
    ... 51 more
Caused by: java.lang.IllegalStateException: Error found on module: org.jooby.jdbi.Jdbi
    at org.jooby.Jooby.install(Jooby.java:3466)
    at org.jooby.Jooby.lambda$null$63(Jooby.java:3207)
    at java.lang.Iterable.forEach(Unknown Source)
....................................................................................

I use "mvn clean package" to make a war to upload to Tomcat. 

Thanks

**Comment by timloo0710** [comment]
and the error messages  mentioned about, 

Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'db'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getAnyRef(SimpleConfig.java:269)
	at org.jooby.jdbc.Jdbc.dbConfig(Jdbc.java:218)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:207)
	at org.jooby.jdbi.Jdbi.configure(Jdbi.java:160)
	at org.jooby.Jooby.install(Jooby.java:3464)
	... 64 more

.................................................................................

But  my db settings in  conf/application.conf   has 

```
db.url = "jdbc:oracle:thin:@192.168.0.10:1521:winbig5"
db.user = "HCGBM"
db.password = "HCGBM"
```

or  maybe I place  another  folder?

In the tomcat container,does  it need some fixes?

Any help? thank you!

**Comment by jknack** [comment]
Hi,
 I can't reproduce it. Here is the full log of the `restful-jdbi` app on Tomcat 9.x and OSX

```
22-Sep-2016 11:21:39.270 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/9.0.0.M10
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 31 2016 15:00:21 UTC
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         9.0.0.0
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.11.6
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_102-b14
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /Users/edgar/tomcat-9.x
22-Sep-2016 11:21:39.271 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /Users/edgar/tomcat-9.x
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF8
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/Users/edgar/tomcat-9.x/conf/logging.properties
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/Users/edgar/tomcat-9.x
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/Users/edgar/tomcat-9.x
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/Users/edgar/tomcat-9.x/temp
22-Sep-2016 11:21:39.272 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /Users/edgar/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
22-Sep-2016 11:21:39.361 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
22-Sep-2016 11:21:39.382 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
22-Sep-2016 11:21:39.384 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
22-Sep-2016 11:21:39.385 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
22-Sep-2016 11:21:39.385 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 374 ms
22-Sep-2016 11:21:39.402 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
22-Sep-2016 11:21:39.402 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/9.0.0.M10
22-Sep-2016 11:21:39.419 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /Users/edgar/tomcat-9.x/webapps/restful-jdbi-1.0.war
22-Sep-2016 11:21:40.216 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11:21:40,813 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:21:40,814 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:21:40,814 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/edgar/tomcat-9.x/webapps/restful-jdbi-1.0/WEB-INF/classes/logback.xml]
11:21:40,814 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
11:21:40,814 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/edgar/tomcat-9.x/webapps/restful-jdbi-1.0/WEB-INF/lib/restful-jdbi-1.0.jar!/logback.xml]
11:21:40,814 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/edgar/tomcat-9.x/webapps/restful-jdbi-1.0/WEB-INF/classes/logback.xml]
11:21:40,851 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:21:40,852 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeFilter scanning period to 15 seconds
11:21:40,852 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/Users/edgar/tomcat-9.x/webapps/restful-jdbi-1.0/WEB-INF/classes/logback.xml]] every 15 seconds.
11:21:40,852 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
11:21:40,853 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:21:40,855 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:21:40,869 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:21:40,899 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:21:40,899 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:21:40,899 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:21:40,900 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@39567a52 - Registering current configuration as safe fallback point

[2016-09-22 11:21:40,982]-[localhost-startStop-1] INFO  com.zaxxer.hikari.HikariDataSource - h2.db - is starting.
[2016-09-22 11:21:41,111]-[localhost-startStop-1] INFO  com.zaxxer.hikari.HikariDataSource -   jdbc:h2:mem:1474554100945;DB_CLOSE_DELAY=-1
[2016-09-22 11:21:41,318]-[localhost-startStop-1] INFO  restfuljdbi.App - [dev@servletcontainer]: Server started in 731ms

  GET    /pets        [*/*]     [*/*]    (/anonymous)
  GET    /pets/:id    [*/*]     [*/*]    (/anonymous)
  POST   /pets        [*/*]     [*/*]    (/anonymous)
  PUT    /pets        [*/*]     [*/*]    (/anonymous)
  DELETE /pets/:id    [*/*]     [*/*]    (/anonymous)

listening on:
  http://localhost:8080/restful-jdbi-1.0

22-Sep-2016 11:21:41.353 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /Users/edgar/tomcat-9.x/webapps/restful-jdbi-1.0.war has finished in 1,934 ms
22-Sep-2016 11:21:41.354 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [http-nio-8080]
22-Sep-2016 11:21:41.359 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [ajp-nio-8009]
22-Sep-2016 11:21:41.360 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 1974 ms
(END)
```

Might be something else is going on... or is probably something windows?

**Comment by jknack** [comment]
It worked in win8 too:

```
edgar@IE11WIN8 ~
$ less tomcat-9.x/logs/catalina.out
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.startup.VersionLoggerLi
22-Sep-2016 09:59:19.384 INFO [main] org.apache.catalina.core.AprLifecycleListen
22-Sep-2016 09:59:19.588 INFO [main] org.apache.coyote.AbstractProtocol.init Ini
22-Sep-2016 09:59:19.696 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.
22-Sep-2016 09:59:19.696 INFO [main] org.apache.coyote.AbstractProtocol.init Ini
22-Sep-2016 09:59:19.712 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.
22-Sep-2016 09:59:19.712 INFO [main] org.apache.catalina.startup.Catalina.load I
22-Sep-2016 09:59:19.759 INFO [main] org.apache.catalina.core.StandardService.st
22-Sep-2016 09:59:19.759 INFO [main] org.apache.catalina.core.StandardEngine.sta
22-Sep-2016 09:59:19.790 INFO [localhost-startStop-1] org.apache.catalina.startu
22-Sep-2016 09:59:21.774 INFO [localhost-startStop-1] org.apache.jasper.servlet.
09:59:22,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT
09:59:22,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT
09:59:22,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found res
09:59:22,618 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource
09:59:22,618 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource
09:59:22,618 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource
09:59:22,680 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction -
09:59:22,680 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction -
09:59:22,680 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will sca
09:59:22,680 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction -
09:59:22,680 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About t
09:59:22,696 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming
09:59:22,712 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA
09:59:22,774 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Se
09:59:22,774 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Atta
09:59:22,774 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction -
09:59:22,774 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@f2bae92 -

[2016-09-22 09:59:22,946]-[localhost-startStop-1] INFO  com.zaxxer.hikari.Hikari
[2016-09-22 09:59:23,337]-[localhost-startStop-1] INFO  com.zaxxer.hikari.Hikari
[2016-09-22 09:59:23,759]-[localhost-startStop-1] INFO  restfuljdbi.App - [dev@s

  GET    /pets        [*/*]     [*/*]    (/anonymous)
  GET    /pets/:id    [*/*]     [*/*]    (/anonymous)
  POST   /pets        [*/*]     [*/*]    (/anonymous)
  PUT    /pets        [*/*]     [*/*]    (/anonymous)
  DELETE /pets/:id    [*/*]     [*/*]    (/anonymous)

listening on:
  http://localhost:8080/restful-jdbi-1.0

22-Sep-2016 09:59:24.009 INFO [localhost-startStop-1] org.apache.catalina.startu
22-Sep-2016 09:59:24.009 INFO [main] org.apache.coyote.AbstractProtocol.start St
22-Sep-2016 09:59:24.024 INFO [main] org.apache.coyote.AbstractProtocol.start St
22-Sep-2016 09:59:24.024 INFO [main] org.apache.catalina.startup.Catalina.start

edgar@IE11WIN8 ~
```

Are you sure did set the `db` properties?

Uncompress your `.war` and see what you have in `WEB-INF/classes/application.conf`

**Comment by timloo0710** [comment]
Thank for your response!

I uncompress my .war, 

in WEB-INF/classes/application.conf 

is

```
# add or override properties
# See https://github.com/typesafehub/config/blob/master/HOCON.md for more details

#db = mem
db.url = "jdbc:oracle:thin:@192.168.0.10:1521:winbig5"
db.user = "HCGBM"
db.password = "HCGBM"

hikari.connectionTimeout = 50000

err.com.security.Forbidden = 403
err.com.security.Forbidden = 401
err.com.security.Forbidden = 402

schema = """
  create table if not exists pets (
    id int not null auto_increment,
    name varchar(255) not null,
    primary key (id)
  );
"""
```


[restful-jdbi.zip](https://github.com/jooby-project/jooby/files/488704/restful-jdbi.zip)

The attachment file is my updated source.  

It ran well  in the develop mode.  Thank you!!

**Comment by timloo0710** [comment]
I use the 

 ```
 <dependency>
      <groupId>com.oracle</groupId>
      <artifactId>ojdbc7</artifactId>
      <version>12.1.0.2</version>
    </dependency>     
```

to connect oracle. 

To download the jar from oracle site , and  add it to my local maven repository  following  the guide

[](https://springframework.guru/configuring-spring-boot-for-oracle/)

I try your original code in my env  latter, then i can compare the result.  Thanks a    lot!

**Comment by jknack** [comment]
Yea, I'm not able to reproduce the problem, but here are couple of general comment.

1. use same jooby version across your project. For example I see: `0.13.0` and `1.0.0.CR7` (from pac4j). This isn't the way of using and might cause some weird classpath issues. Pick one and use that.

2. clean your `<build><plugins>...</plugins></build>` section you don't need any of that. The `war ` is generated by placing the `war.activator` file inside the `src/etc` folder. You can keep `exec` plugin but Jooby offers a more powerful option:  `mvn jooby:run` 

Play a bit with the available `restful-jdbi` example and you will see it is successfully deployed in Tomcat 9. All you need to do is the point `2` described before (clean the plugin section and create the `src/etc/war.activator` file)

Let me know if you find the root problem and/or if you are able to deploy.

Thanks and make sure to star the project 😄
