### ISSUE TITLE
[jooby-jdbc] Use / configure com.impossibl.postgres.jdbc.PGDriver failed

### ISSUE THREAD

**Issue by ludmiloff** [jooby-project/jooby#522]
I'm trying to connect to postgres database via com.impossibl.postgres.jdbc.PGDriver.
Unfortunately, the drive has no url property to set up. When I set db.url = .... in application.conf, jooby-jdbc failed with following:

Caused by: java.lang.RuntimeException: Property url does not exist on target class com.impossibl.postgres.jdbc.PGDataSource
	at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:131)
	at com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:57)
	at java.util.Hashtable.forEach(Hashtable.java:878)
	at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:52)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:315)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:108)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:99)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:363)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:334)
	at org.jooby.Jooby.install(Jooby.java:4709)

When I omit the db.url property, jooby-jdbc fails again, this time with:
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'db.url'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:351)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:334)
	at org.jooby.Jooby.install(Jooby.java:4709)
	... 23 common frames omitted

What is the proper way to configure com.impossibl.postgres.jdbc.PGDriver?
Do I need to write my own module or there is a way to bypass jooby-jdbc url requirements?

Thanks

**Comment by jknack** [comment]
Never thought that a datasource without an `url` ever exist.
There is a workaround, bit hacky:

```
db.url = "jdbc:pgsql://localhost:5432/demo"
db.user= myuser
db.password= mypass

## Required while https://github.com/jooby-project/jooby/issues/522 is still open
databases.pgsql.dataSourceClassName = ""
hikari.jdbcUrl = ${db.url}
```

That makes Hikari to configure datasource in the `old way`.

Give it a try and let me know how it goes.

Thanks

**Comment by ludmiloff** [comment]
That works for me, thanks.

Anyway, I've figured that if I'm able to catch hikariConf and remove url property by myself, it will work too. I just need to get callback called before creating HikariDataSource (Jdbc.java, line 363)

        HikariDataSource ds = new HikariDataSource(hikariConf);
        callback(ds, config);

to

        callback(hikariConf, null);
        HikariDataSource ds = new HikariDataSource(hikariConf);


but that's very ugly.

**Comment by jknack** [comment]
Yea, that was my first option but then realize we never make the call to: `callback(hikariConf, conf);`

I will patch this issue by letting people to execute a `callback` before HDS (as you pointd out) but also fix this in PGDataSource (probably by wrapping it with a DataSource with url support)

Anyway, glad it works and please star Jooby if you didn't already.

Thanks

**Comment by ludmiloff** [comment]
`callback(hikariConf, conf)` sounds great.
You may close this issue as it very rare case, only with com.impossibl.postgres.jdbc.PGDriver probably. And the driver itself is not ready yet, it still has memory leak.

Thanks for your support.

**Comment by jknack** [comment]
Resolved in #527 via `callback(hikariconf)`

**Comment by brandonlamb** [comment]
Got here from google groups. Would someone be able to post a working example of your app code that works? I have this same issue with DB2. I also use PostgreSQL so suspect I doubly need this haha

**Comment by jknack** [comment]
It should works for pgsql, can you point me to the db2 driver?

Thanks
