### ISSUE TITLE
Swagger/jooby-maven-plugin:spec: NPE when using Constructor in App

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#535]
If there is a constructor in the App, I get that exception:

org.jooby.Err: Server Error(500)
	at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:391)
	at org.jooby.internal.HttpHandlerImpl.cleanup(HttpHandlerImpl.java:371)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:312)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:363)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Error while processing class com.mycompany.App
	at org.jooby.spec.RouteProcessor.processInternal(RouteProcessor.java:298)
	at org.jooby.spec.RouteProcessor.process(RouteProcessor.java:133)
	at org.jooby.internal.swagger.SwaggerBuilder.build(SwaggerBuilder.java:111)
	at org.jooby.swagger.SwaggerUI.lambda$install$2(SwaggerUI.java:255)
	at org.jooby.Route$OneArgHandler.handle(Route.java:1727)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:108)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2074)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:304)
	... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.jooby.internal.spec.RouteCollector.accept(RouteCollector.java:89)
	at org.jooby.spec.RouteProcessor.processInternal(RouteProcessor.java:227)
	... 17 common frames omitted

**Comment by jknack** [comment]
Yes, it requires an empty args constructor.

**Comment by jschneider** [comment]
Two things: What is the difference between

{}

and

public App(){}

Both should do the same.
Second: If you really require the initializer, then at least a nice exception should be thrown (instead of a NPE which isn't very helpful at all).

**Comment by jknack** [comment]
No difference between `{}` and `App() {}` was the case of the NPE? If so, then this is a bug.

Let me know if you want to take care of this issue.

Thanks

**Comment by jschneider** [comment]
I have created a pull request: https://github.com/jooby-project/jooby/pull/537

One more thing: What do you think about adding @Nullable/@NonNull annotations?
IntelliJ IDEA supports these with static checks. Helps a lot to avoid these NPE

**Comment by jknack** [comment]
I used to have those before, but then I removed them all. Do we need a new runtime dependency? Don't want to add a dependency for this 😄

**Comment by jschneider** [comment]
Since these are only annotations, it is not necessary to add a runtime dependency. 
<scope>provided</scope> is enough.

**Comment by jknack** [comment]
Fixed with #537
