### ISSUE TITLE
IndexOutOfBoundsException when no javadoc is present in mvc route

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#547]
A "get" method without any doc results in this:
Adding a javadoc will solve the issue.

A missing "@GET" annotation might result in the same problem(?)

java.lang.IndexOutOfBoundsException: Index: 23, Size: 23
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.jooby.spec.RouteProcessor.processInternal(RouteProcessor.java:250)
	at org.jooby.spec.RouteProcessor.process(RouteProcessor.java:133)
	at org.jooby.internal.swagger.SwaggerBuilder.build(SwaggerBuilder.java:111)
	at org.jooby.swagger.SwaggerUI.lambda$install$2(SwaggerUI.java:255)
	at org.jooby.Route$OneArgHandler.handle(Route.java:1727)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:108)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2074)
	at org.jooby.Route$Handler.handle(Route.java:1682)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:108)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2074)
	at org.jooby.metrics.InstrumentedHandler.handle(InstrumentedHandler.java:47)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:108)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2074)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:304)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:363)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jknack** [comment]
I can't reproduce it. Please add a example to reproduce the problem
