### ISSUE TITLE
Inject Issue in Cache modules and MVC 

### ISSUE THREAD

**Issue by Shbnv** [jooby-project/jooby#573]
There is an issue with inject **any** Cache modules into MVC Controller.
For example, Guava:
`
{
   use(GuavaCache.newCache());
   session(GuavaSessionStore.class);
}`
`   @Inject
    public MyMVCRoutes( Cache cache)
    {
        this.cache = cache;
    }`
Getting error:
`[2016-11-23 14:09:48,483]-[HotSwap] ERROR App - An error occurred while stating the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.google.common.cache.Cache was bound.
  while locating com.google.common.cache.Cache
    for the 1st parameter of MyMVCRoutes.<init>(MyMVCRoutes.java:58

  at org.jooby.Jooby.lambda$bindService$50(Jooby.java:2757)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:10)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.bootstrap(Jooby.java:2498)
        at org.jooby.Jooby.start(Jooby.java:1931)
        at org.jooby.Jooby.start(Jooby.java:1919)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jooby.run.Main.lambda$startApp$1(Main.java:237)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by jknack** [comment]
Hi @Shbnv 

Try `Cache<String, Object>`, like:

```java
@Inject public MyMVCRoutes( Cache<String, Object> cache) { this.cache = cache; }
```

**Comment by Shbnv** [comment]
I tried this already:
`1) No implementation for com.google.common.cache.Cache<java.lang.String, java.lang.Object> was bound.
  while locating com.google.common.cache.Cache<java.lang.String, java.lang.Object>`

**Comment by Shbnv** [comment]
Yes! Thank you!
