### ISSUE TITLE
Stork started but doesn't work

### ISSUE THREAD

**Issue by Shbnv** [jooby-project/jooby#580]
Application started normally, but get warning when trying open url:
`[2016-11-25 16:52:10,308]-[nio-worker-3-1] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x0805e01a, /0:0:0:0:0:0:0:1:7492 => /0:0:0:0:0:0:0:1:8080]
java.lang.NoSuchMethodError: io.netty.util.AttributeKey.newInstance(Ljava/lang/String;)Lio/netty/util/AttributeKey;
        at org.jooby.internal.netty.NettyHandler.<clinit>(NettyHandler.java:55)
        at org.jooby.internal.netty.NettyPipeline.jooby(NettyPipeline.java:146)
        at org.jooby.internal.netty.NettyPipeline.http1(NettyPipeline.java:138)
        at org.jooby.internal.netty.NettyPipeline.initChannel(NettyPipeline.java:108)
        at org.jooby.internal.netty.NettyPipeline.initChannel(NettyPipeline.java:55)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)`

Fixed by removing dependency „netty-all-4.0.23.Final.jar“.

**Comment by jknack** [comment]
Why you have `netty-all-4.0.23.Final.jar` in your classpath?

Think you have a classpath problem. Can you please paste the content of your `pom.xml`? and the output of `mvn dependency:tree`?

Thanks.

**Comment by Shbnv** [comment]
> Think you have a classpath problem.
Yes. It gets with „Hadoop“ dependency.

**Comment by jknack** [comment]
@Shbnv glad you find it! Also, if you like Jooby please star the project and follow us at twitter.

Thanks
