### ISSUE TITLE
org.jooby.Err: Not Found(404): /favicon.ico

### ISSUE THREAD

**Issue by cvgaviao** [jooby-project/jooby#584]
I did run the latest archetype as indicated here: http://jooby.org/quickstart/. 

then after run _mvn jooby:run_, I'm seeing:

`listening on:
  http://localhost:8080/

[2016-11-30 20:25:21,620]-[netty task-4-1] ERROR org.jooby.Err - execution of: GET/favicon.ico resulted in exception
Route:
      | Method | Path         | Source      | Name | Pattern      | Consumes | Produces |
      |--------|--------------|-------------|------|--------------|----------|----------|
      | GET    | /favicon.ico | ~unknown:-1 | /err | /favicon.ico | [*/*]    | [*/*]    |

Stacktrace:
org.jooby.Err: Not Found(404): /favicon.ico
	at org.jooby.internal.HttpHandlerImpl.lambda$routes$10(HttpHandlerImpl.java:433)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2101)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:364)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
[2016-11-30 20:25:21,664]-[netty task-4-1] ERROR org.jooby.Err - execution of: GET/favicon.ico resulted in exception
Route:
      | Method | Path         | Source      | Name | Pattern      | Consumes | Produces                                                 |
      |--------|--------------|-------------|------|--------------|----------|----------------------------------------------------------|
      | GET    | /favicon.ico | ~unknown:-1 | /err | /favicon.ico | [*/*]    | [text/html, application/xhtml+xml, application/xml, */*] |

Stacktrace:
org.jooby.Err: Not Found(404): /favicon.ico
	at org.jooby.internal.HttpHandlerImpl.lambda$routes$10(HttpHandlerImpl.java:433)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2101)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:364)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by jknack** [comment]
Browsers always ask for a favicon and your application doesn't provide one.
If you have one, then:

```
{
   assets("/favicon.ico");
}
``` 

It serve a `favicon.ico` file from root of classpath or `public` directory.

Otherwise, you can ignore or silent this error.

Thanks.

**Comment by jknack** [comment]
This will silente the /favicon.ico request #595. Can you please make a review?

Thanks
