### ISSUE TITLE
Method Not Allowed(405): DELETE

### ISSUE THREAD

**Issue by yan5** [jooby-project/jooby#588]
Hi 
I've the following route definition
```
delete("/api/v1/dex/**", appController::authenticate);
delete("/api/v1/dex/review", appController::deleteReview);
```
authenticate is defined as follows:

```
public void authenticate(Request req, Response response, Route.Chain chain) throws Throwable {
...
...
 chain.next(req, response);
...
...
}
```

the REST api request DELETE `/api/v1/dex/review?id=10` is running into the following error:

```
org.jooby.Err: Method Not Allowed(405): DELETE
	at org.jooby.internal.HttpHandlerImpl.handle405(HttpHandlerImpl.java:468)
	at org.jooby.internal.HttpHandlerImpl.lambda$routes$10(HttpHandlerImpl.java:429)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2101)
```
The error is emitted from  `chain.next(req, response);`
But it works if I use POST instead of DELETE. (ie adding post route definition and issuing POST rest api)

**Comment by yan5** [comment]
Sorry realized it was a mistake in the route definition.

**Comment by jknack** [comment]
Glad you figure it out!
