### ISSUE TITLE
Ebean deadlock with shutdown

### ISSUE THREAD

**Issue by Shbnv** [jooby-project/jooby#589]
Hi!
When i press Ctrl+C jooby didn't stop sometimes. 
Ctrl+Break show this error:
`Found one Java-level deadlock:
=============================
"Thread-30":
  waiting to lock monitor 0x000000001d99d118 (object 0x00000006c5569110, a com.avaje.ebeaninternal.s
erver.core.DefaultServer),
  which is held by "Thread-32"
"Thread-32":
  waiting to lock monitor 0x0000000020d9e7d8 (object 0x00000006c55691a0, a java.util.ArrayList),
  which is held by "Thread-30"

Java stack information for the threads listed above:
===================================================
"Thread-30":
        at com.avaje.ebeaninternal.server.core.DefaultServer.shutdownManaged(DefaultServer.java:381)

        - waiting to lock <0x00000006c5569110> (a com.avaje.ebeaninternal.server.core.DefaultServer)

        at com.avaje.ebeaninternal.server.lib.ShutdownManager.shutdown(ShutdownManager.java:147)
        - locked <0x00000006c55691a0> (a java.util.ArrayList)
        at com.avaje.ebeaninternal.server.lib.ShutdownHook.run(ShutdownHook.java:19)
"Thread-32":
        at com.avaje.ebeaninternal.server.lib.ShutdownManager.unregisterEbeanServer(ShutdownManager.
java:191)
        - waiting to lock <0x00000006c55691a0> (a java.util.ArrayList)
        at com.avaje.ebeaninternal.server.core.DefaultServer.shutdown(DefaultServer.java:391)
        - locked <0x00000006c5569110> (a com.avaje.ebeaninternal.server.core.DefaultServer)
        at org.jooby.internal.ebean.EbeanManaged.stop(EbeanManaged.java:59)
        at org.jooby.ebean.Ebeanby$$Lambda$1766/104440788.run(Unknown Source)
        at org.jooby.LifeCycle.lambda$onStop$8(LifeCycle.java:290)
        at org.jooby.LifeCycle$$Lambda$1767/1436475756.accept(Unknown Source)
        at org.jooby.Jooby.lambda$null$55(Jooby.java:2819)
        at org.jooby.Jooby$$Lambda$1903/21642900.run(Unknown Source)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$fireStop$57(Jooby.java:2819)
        at org.jooby.Jooby$$Lambda$1902/91597538.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.jooby.Jooby.fireStop(Jooby.java:2819)
        at org.jooby.Jooby.stop(Jooby.java:2802)
        at org.jooby.Jooby.stop(Jooby.java:2785)
        at org.jooby.Jooby.lambda$start$25(Jooby.java:1934)
        at org.jooby.Jooby$$Lambda$1821/1253966719.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.`

**Comment by jknack** [comment]
is it ebean?

**Comment by Shbnv** [comment]
Yes.
**Probably**, it happened when DB configuration changed.
