### ISSUE TITLE
pac4j AJAX  Unauthorized(401) request exception thrown

### ISSUE THREAD

**Issue by S66D** [jooby-project/jooby#637]
Hi @jknack, Is it possible suppress or handle the thrown exception.
```java
org.jooby.spi.HttpHandler@netty task-4-3 execution of: GET/logs resulted in exception
org.jooby.Err: Unauthorized(401)
	at org.jooby.internal.pac4j.AuthResponse.handle(AuthResponse.java:43)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$c90ccd5f$1(AuthFilter.java:124)
	at org.jooby.internal.pac4j.AuthFilter.find(AuthFilter.java:152)
	at org.jooby.internal.pac4j.AuthFilter.handle(AuthFilter.java:114)
	at org.jooby.Route$Handler.handle(Route.java:1717)
	at org.jooby.internal.pac4j.FormFilter.handle(FormFilter.java:94)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2106)
	at org.jooby.Route$Handler.handle(Route.java:1718)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2106)
	at org.jooby.Route$Handler.handle(Route.java:1718)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2106)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:364)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pac4j.core.exception.HttpAction: AJAX request -> 401
	at org.pac4j.core.exception.HttpAction.unauthorized(HttpAction.java:89)
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:87)
	at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:67)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$c90ccd5f$1(AuthFilter.java:121)
	... 25 common frames omitted
```

**Comment by jknack** [comment]
Yes, checkout: http://jooby.org/doc/#error-handling

You need a custom error handler: http://jooby.org/doc/#error-handling-custom-err-handler

I usually test for 404/401/403 and silent those error with `log.debug`

**Comment by S66D** [comment]
Thank you for yor time @jknack, I have add an error handler but it seems to be there are two same exceptions thrown one that can be handled and the other has been triggered by something.
I will include the code to produce the issue.
```java
import org.jooby.Jooby;
import org.jooby.pac4j.Auth;
public class Main extends Jooby {
    {
        String index =
                   "<HTML>"
                    +  "<SCRIPT type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></SCRIPT>"
                    +  "<SCRIPT type='text/javascript'>"
                            + "function requestAJAX(){"
                            + "$.getJSON('/secure')"
                            + "}"
                    + "</SCRIPT>"
                    + "<BODY>"
                        + "<BUTTON onclick='requestAJAX()'>requestAJAX</BUTTON>"
                    + "</BODY>"
                +  "</HTML>";

        get("/", () -> index);
        get("/login", () -> "login");
        use(new Auth().form("/secure"));
        get("/secure", () -> "Hello Jooby!");
        err((req, rsp, ex) -> rsp.send(ex.getMessage()));
    }
    public static void main(String[] args) {
        run(Main::new, args);
    }
}
```

**Comment by jknack** [comment]
What you doing here looks wrong to me. You first load the page at '/' and try to call `/secure` path. The `/secure` path requires form auth... that's why your ajax call doesn't work.

If this is what you need you must provide a way to authenticate first and then make the `/secure` call.

**Comment by S66D** [comment]
Yes, you need to auth before you can access `/secure` path, but an none-authorize person will try to access.
The ajax work perfectly with a response of unauthorized 401, my issue is why two same error exception are thrown one that can be handled and the other can not be handled by `Jooby.err()` handler, what is the reason to throw two of the same exceptions?

**Comment by jknack** [comment]
Hi @S66D,

 I'm not exactly sure what you mean by 

>  why two same error exception are thrown one that can be handled and the other can not be handled by Jooby.err()

I see one exception which is handled by `err` (all the exceptions are handled by err)

Here is the exception:

```
org.jooby.Err: Unauthorized(401)
	at org.jooby.internal.pac4j.AuthResponse.handle(AuthResponse.java:43)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$b1864522$1(AuthFilter.java:122)
	at org.jooby.internal.pac4j.AuthFilter.find(AuthFilter.java:150)
	at org.jooby.internal.pac4j.AuthFilter.handle(AuthFilter.java:111)
	at org.jooby.Route$Handler.handle(Route.java:1717)
INFO  [2017-02-14 14:30:11,299] [netty task-4-1] AJAX request detected -> returning 401
	at org.jooby.internal.pac4j.FormFilter.handle(FormFilter.java:93)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2106)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:91)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:354)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: #HttpAction# | code: 401 |
	at org.pac4j.core.exception.HttpAction.unauthorized(HttpAction.java:89)
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:69)
	at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:44)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$b1864522$1(AuthFilter.java:119)
	... 17 more
```

It is one exception with an inner cause.

**Comment by S66D** [comment]
Hmm, this is what my exception looks like:
```java
INFO  org.pac4j.http.client.indirect.FormClient@netty task-4-1 AJAX request detected -> returning 401
DEBUG org.jooby.spi.HttpHandler@netty task-4-1 execution of: GET/secure resulted in exception
org.jooby.Err: Unauthorized(401)
	at org.jooby.internal.pac4j.AuthResponse.handle(AuthResponse.java:43)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$c90ccd5f$1(AuthFilter.java:124)
	at org.jooby.internal.pac4j.AuthFilter.find(AuthFilter.java:152)
	at org.jooby.internal.pac4j.AuthFilter.handle(AuthFilter.java:114)
	at org.jooby.Route$Handler.handle(Route.java:1717)
	at org.jooby.internal.pac4j.FormFilter.handle(FormFilter.java:94)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2106)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:364)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pac4j.core.exception.HttpAction: AJAX request -> 401
	at org.pac4j.core.exception.HttpAction.unauthorized(HttpAction.java:89)
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:87)
	at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:67)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$c90ccd5f$1(AuthFilter.java:121)
	... 17 common frames omitted
DEBUG org.jooby.spi.HttpHandler@netty task-4-1 handling err with: org.jooby.Err$DefHandler@5b799640
ERROR org.jooby.Err@netty task-4-1 execution of: GET/secure resulted in exception
Route:
      | Method | Path    | Source                   | Name              | Pattern | Consumes | Produces |
      |--------|---------|--------------------------|-------------------|---------|----------|----------|
      | GET    | /secure | org.jooby.pac4j.Auth:684 | /auth(FormClient) | /secure | [*/*]    | [*/*]    |

Stacktrace:
org.jooby.Err: Unauthorized(401)
	at org.jooby.internal.pac4j.AuthResponse.handle(AuthResponse.java:43)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$c90ccd5f$1(AuthFilter.java:124)
	at org.jooby.internal.pac4j.AuthFilter.find(AuthFilter.java:152)
	at org.jooby.internal.pac4j.AuthFilter.handle(AuthFilter.java:114)
	at org.jooby.Route$Handler.handle(Route.java:1717)
	at org.jooby.internal.pac4j.FormFilter.handle(FormFilter.java:94)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2106)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:364)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pac4j.core.exception.HttpAction: AJAX request -> 401
	at org.pac4j.core.exception.HttpAction.unauthorized(HttpAction.java:89)
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:87)
	at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:67)
	at org.jooby.internal.pac4j.AuthFilter.lambda$handle$c90ccd5f$1(AuthFilter.java:121)
	... 17 common frames omitted

```

Any Idea why?

**Comment by jknack** [comment]
That's odd. Need two things from you:

1. Can you post your `logback.xml` file?

2. Think your example is missing something, due I can reproduce it. Can you please check and confirm if your example is completed?

Thanks.

**Comment by S66D** [comment]
1.  In this example I used all `jooby` default values.

2. That is pretty much it.
Will and I just found out every `org.jooby.Err ` throws the same issue



```java
20:19:08.346 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
20:19:08.346 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
20:19:08.346 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
20:19:08.346 [main] DEBUG org.jooby.spi.Server - netty.threads.boss(1)
20:19:08.346 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
20:19:08.361 [main] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent - Java version: 8
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
20:19:08.361 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
20:19:08.399 [main] DEBUG io.netty.util.internal.PlatformDependent - Javassist: available
20:19:08.399 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\U2331\AppData\Local\Temp\joobyauth
20:19:08.399 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 32 (sun.arch.data.model)
20:19:08.399 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
20:19:08.399 [main] DEBUG io.netty.util.internal.PlatformDependent - io.netty.maxDirectMemory: 259522560 bytes
20:19:08.399 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
20:19:08.399 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
20:19:08.415 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
20:19:08.499 [main] DEBUG org.jooby.spi.Server - netty.threads.worker(16)
20:19:08.530 [main] DEBUG org.jooby.spi.Server - netty.options.SO_REUSEADDR(true)
20:19:08.530 [main] DEBUG org.jooby.spi.Server - netty.worker.options.SO_REUSEADDR(true)
20:19:08.530 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 13920 (auto-detected)
20:19:08.530 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
20:19:08.530 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
20:19:08.599 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
20:19:08.599 [main] DEBUG io.netty.util.NetUtil - \proc\sys\net\core\somaxconn: 200 (non-existent)
20:19:08.684 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:00:00:00:00:00:00:e0 (auto-detected)
20:19:08.684 [main] DEBUG io.netty.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xc363a6a19ae90685
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 2
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 2
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
20:19:08.699 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
20:19:08.715 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
20:19:08.715 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
20:19:08.715 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
20:19:08.715 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0x2807a43e] REGISTERED
20:19:08.715 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0x2807a43e] BIND: /0.0.0.0:8080
20:19:08.731 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0x2807a43e, L:/0:0:0:0:0:0:0:0:8080] ACTIVE
20:19:08.731 [main] INFO com.test.joobyauth.Main - [dev@netty]: Server started in 685ms

  GET /    [*/*]     [*/*]    (/anonymous)

listening on:
  http://localhost:8080/

20:19:10.481 [nio-boss-1-1] DEBUG org.jooby.spi.Server - [id: 0x2807a43e, L:/0:0:0:0:0:0:0:0:8080] RECEIVED: [id: 0x6dc09fb7, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:64290]
20:19:10.493 [nio-worker-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
20:19:10.494 [nio-worker-3-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@b84884
20:19:10.506 [nio-worker-3-1] DEBUG io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.io.netty.handler.codec.http.HttpObjectMatcher
20:19:10.512 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 32768
20:19:10.512 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
20:19:10.512 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
20:19:10.512 [nio-worker-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
20:19:10.529 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - execution of: GET/foo resulted in exception
org.jooby.Err: Not Found(404): /foo
	at org.jooby.internal.HttpHandlerImpl.lambda$routes$10(HttpHandlerImpl.java:433)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2101)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:364)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
20:19:10.531 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: org.jooby.Err$DefHandler@116aac9
20:19:10.532 [netty task-4-1] ERROR org.jooby.Err - execution of: GET/foo resulted in exception
Route:
      | Method | Path  | Source      | Name | Pattern | Consumes | Produces                                                             |
      |--------|-------|-------------|------|---------|----------|----------------------------------------------------------------------|
      | GET    | /foo | ~unknown:-1 | /err | /foo   | [*/*]    | [text/html, application/xhtml+xml, application/xml, image/webp, */*] |

Stacktrace:
org.jooby.Err: Not Found(404): /foo
	at org.jooby.internal.HttpHandlerImpl.lambda$routes$10(HttpHandlerImpl.java:433)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
	at org.jooby.internal.RouteChain.next(RouteChain.java:70)
	at org.jooby.Route$Chain.next(Route.java:2101)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:92)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:364)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

```

Any other Ideas?

**Comment by jknack** [comment]
Think I got it. The root logger is in debug mode, that is why you see the stacktrace printed twice.

Your options are:

1. safely ignore the 1st print from `org.jooby.spi.HttpHandler` where it log the error as `debug`
2. set root logger to `info`
3. set `org.jooby.spi.HttpHandler` logger to trace or turn it off

Again, the reason why you see two prints is bc your code/root logger run in DEBUG mode.

make sense?

**Comment by S66D** [comment]
Yes you are right, it was confusing, and I have suspected it has something to do with logger.
Thanks again for your time.
