### ISSUE TITLE
`AssetHandler` is bypassing jar ressources

### ISSUE THREAD

**Issue by authchir** [jooby-project/jooby#639]
In an application I am developing, I have a compilation step where I apply some transformations to static resources (in this case, some JavaScript code is being transpiled with [babel][1], but the situation will also arrives with any external transformation). Those resources are served as following:

```Java
final Duration days7 = Duration.ofDays(7);
assets("/assets/js/**", new AssetHandler("/").maxAge(days7));
```

However, when running the code in development (i.e. with `./gradlew project:run`) the original files are being served, instead of the transpiled ones. I suspect the problem is caused by [this optimisation][2]. I tried to launch the application and then to rename the directory, thereby disabling this optimisation, and the correct transpiled files then got selected. 

I understand how useful it is most of the time. But there are some rare and specific situations, where this behaviour is not desirable. I proposed that there should be a flag given at initialisation, allowing one to disable this optimisation.

What are your thought about it?

[1]: http://babeljs.io/
[2]: https://github.com/jooby-project/jooby/blob/c35e10e5d8c9e9ed51318b3e211a815a338a4eb7/jooby/src/main/java/org/jooby/handlers/AssetHandler.java#L367-L379

**Comment by jknack** [comment]
Isn't the asset module an option? There is a babel processor already: http://jooby.org/doc/assets-babel

Also, Did you remove those lines and work it? Don't see why those lines affect your use case.

**Comment by authchir** [comment]
Well, this situation with babel is just an example. An other example is a script which reencode some UTF-8 files to ISO 8859-1.

If am am reading correctly and it correlates with my tests, those lines of code check if the file is directly available on the file system and use the jar resources only as a fall-back.

PS I just gave it a tried configuring the asset processor and got the following error:

```
>>> jooby:run[info|Daemon worker]: Hotswap available on: [/home/martin/Documents/sandbox/aga]
>>> jooby:run[info|Daemon worker]:   includes: [**/*.class:**/*.conf:**/*.properties:*.js:src/*.js]
>>> jooby:run[info|Daemon worker]:   excludes: []
16:27:08.789 [HotSwap] INFO com.gfaga.portal.docManager.Main - Stopped
16:27:08.795 [HotSwap] ERROR com.gfaga.portal.docManager.Main - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.jooby.spi.HttpHandler was bound.
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.netty.NettyServer.<init>(NettyServer.java:83)
  at org.jooby.netty.Netty.configure(Netty.java:36)

2) An exception was caught and reported. Message: java.nio.file.NoSuchFileException: public
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:704)
        at org.jooby.Jooby.bootstrap(Jooby.java:2731)
        at org.jooby.Jooby.start(Jooby.java:1958)
        at org.jooby.Jooby.start(Jooby.java:1940)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jooby.run.Main.lambda$startApp$1(Main.java:237)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: public
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at javaslang.control.Try.getOrElseThrow(Try.java:473)
        at org.jooby.Jooby.lambda$bootstrap$46(Jooby.java:2668)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        ... 16 common frames omitted
Caused by: java.nio.file.NoSuchFileException: public
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at org.jooby.internal.assets.Watcher.registerAll(Watcher.java:86)
        at org.jooby.internal.assets.Watcher.<init>(Watcher.java:102)
        at org.jooby.internal.assets.LiveCompiler.<init>(LiveCompiler.java:67)
        at org.jooby.assets.Assets.configure(Assets.java:325)
        at org.jooby.Jooby.install(Jooby.java:3120)
        at org.jooby.Jooby.lambda$bindService$48(Jooby.java:2811)
        at org.jooby.Jooby.lambda$null$43(Jooby.java:2667)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$bootstrap$46(Jooby.java:2656)
        ... 20 common frames omitted
The message received from the daemon indicates that the daemon has disappeared.
```

**Comment by jknack** [comment]
Yea all that can be done within the asset module and creating custom processors.

Do you have a public directory? Here is a demo project with the asset processor working: https://github.com/jooby-project/devdayar16

**Comment by authchir** [comment]
Ok, sorry for the delay.

I just create a small [demo project][1] to test the babel processor using Gradle. You can simply test with the following commands:

```
$ git clone git@github.com:authchir/jooby-gradle-demo.git
$ cd jooby-gradle-demo
$ ./gradlew joobyRun
```

While downloading the `foo.js` file, the following error get generated.

```
Stacktrace:
org.jooby.Err: Server Error(500)
        at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:398)
        at org.jooby.internal.HttpHandlerImpl.cleanup(HttpHandlerImpl.java:372)
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:314)
        at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:91)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:354)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/eclipsesource/v8/V8Value
        at org.jooby.assets.Babel.process(Babel.java:84)
        at org.jooby.assets.AssetCompiler.compile(AssetCompiler.java:418)
        at org.jooby.assets.AssetCompiler.build(AssetCompiler.java:377)
        at org.jooby.internal.assets.AssetHandlerWithCompiler.send(AssetHandlerWithCompiler.java:40)
        at org.jooby.handlers.AssetHandler.doHandle(AssetHandler.java:322)
        at org.jooby.handlers.AssetHandler.handle(AssetHandler.java:280)
        at org.jooby.Route$Handler.handle(Route.java:1717)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
        at org.jooby.internal.RouteChain.next(RouteChain.java:70)
        at org.jooby.Route$Chain.next(Route.java:2106)
        at org.jooby.Route$Handler.handle(Route.java:1718)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
        at org.jooby.internal.RouteChain.next(RouteChain.java:70)
        at org.jooby.Route$Chain.next(Route.java:2106)
        at org.jooby.Route$Handler.handle(Route.java:1718)
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:113)
        at org.jooby.internal.RouteChain.next(RouteChain.java:70)
        at org.jooby.Route$Chain.next(Route.java:2106)
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:306)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.eclipsesource.v8.V8Value from [Module "jooby-gradle-demo:main" from AppModuleLoader@1edb32a1 for finders []]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
        ... 28 common frames omitted
```

[1]: https://github.com/authchir/jooby-gradle-demo

**Comment by jknack** [comment]
Oh right, you need this: https://github.com/jooby-project/jooby/blob/master/jooby-assets-j2v8/pom.xml#L33-L112

It works out of box in Maven... but you need to manually configure for gradle.

Babel runs on top of v8 via j2v8 (and native lib)

**Comment by authchir** [comment]
Hello,
It now works perfectly for `./gradlew joobyRun` with the transitive dependency added. However, when I produced a distribution, the asset manager did not seem to work when run directly from the jar.

Here are my steps from the same [example project][1]:

```
$ ./gradlew clean build
:clean
:compileJava
:processResources
:classes
:jar
:startScripts
:distTar
:distZip
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 1.74 secs
$ cp build/distributions/jooby-gradle-demo.tar /tmp
$ cd /tmp
$ tar -xvf jooby-gradle-demo.tar
jooby-gradle-demo/
jooby-gradle-demo/lib/
jooby-gradle-demo/lib/jooby-gradle-demo.jar
jooby-gradle-demo/lib/jooby-1.0.3.jar
jooby-gradle-demo/lib/jooby-netty-1.0.3.jar
jooby-gradle-demo/lib/jooby-assets-1.0.3.jar
jooby-gradle-demo/lib/jooby-assets-babel-1.0.3.jar
jooby-gradle-demo/lib/j2v8_linux_x86_64-4.5.0.jar
jooby-gradle-demo/lib/slf4j-api-1.7.21.jar
jooby-gradle-demo/lib/logback-classic-1.1.7.jar
jooby-gradle-demo/lib/config-1.3.1.jar
jooby-gradle-demo/lib/javaslang-2.0.4.jar
jooby-gradle-demo/lib/guava-19.0.jar
jooby-gradle-demo/lib/guice-multibindings-4.1.0.jar
jooby-gradle-demo/lib/netty-codec-http-4.1.7.Final.jar
jooby-gradle-demo/lib/netty-codec-http2-4.1.7.Final.jar
jooby-gradle-demo/lib/netty-handler-4.1.7.Final.jar
jooby-gradle-demo/lib/javassist-3.20.0-GA.jar
jooby-gradle-demo/lib/netty-transport-native-epoll-4.1.7.Final.jar
jooby-gradle-demo/lib/jooby-assets-j2v8-1.0.3.jar
jooby-gradle-demo/lib/logback-core-1.1.7.jar
jooby-gradle-demo/lib/javaslang-match-2.0.4.jar
jooby-gradle-demo/lib/guice-4.1.0.jar
jooby-gradle-demo/lib/netty-codec-4.1.7.Final.jar
jooby-gradle-demo/lib/netty-buffer-4.1.7.Final.jar
jooby-gradle-demo/lib/netty-transport-4.1.7.Final.jar
jooby-gradle-demo/lib/netty-common-4.1.7.Final.jar
jooby-gradle-demo/lib/javax.inject-1.jar
jooby-gradle-demo/lib/aopalliance-1.0.jar
jooby-gradle-demo/lib/netty-resolver-4.1.7.Final.jar
jooby-gradle-demo/bin/
jooby-gradle-demo/bin/jooby-gradle-demo
jooby-gradle-demo/bin/jooby-gradle-demo.bat
$ jooby-gradle-demo/bin/jooby-gradle-demo
Feb 27, 2017 12:40:14 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.nio.file.NoSuchFileException: public
java.lang.RuntimeException: java.nio.file.NoSuchFileException: public
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at javaslang.control.Try.getOrElseThrow(Try.java:473)
        at org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2690)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:706)
        at org.jooby.Jooby.bootstrap(Jooby.java:2753)
        at org.jooby.Jooby.start(Jooby.java:1960)
        at org.jooby.Jooby.start(Jooby.java:1942)
        at org.jooby.Jooby.run(Jooby.java:1872)
        at org.jooby.gradleDemo.Main.main(Main.java:34)
Caused by: java.nio.file.NoSuchFileException: public
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at org.jooby.internal.assets.Watcher.registerAll(Watcher.java:86)
        at org.jooby.internal.assets.Watcher.<init>(Watcher.java:102)
        at org.jooby.internal.assets.LiveCompiler.<init>(LiveCompiler.java:67)
        at org.jooby.assets.Assets.configure(Assets.java:325)
        at org.jooby.Jooby.install(Jooby.java:3144)
        at org.jooby.Jooby.lambda$bindService$49(Jooby.java:2833)
        at org.jooby.Jooby.lambda$null$44(Jooby.java:2689)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2678)
        ... 12 more

12:40:14.126 [main] INFO org.jooby.gradleDemo.Main - Stopped
12:40:14.133 [main] ERROR org.jooby.gradleDemo.Main - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.jooby.spi.HttpHandler was bound.
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.netty.NettyServer.<init>(NettyServer.java:81)
  at org.jooby.netty.Netty.configure(Netty.java:36)

2) An exception was caught and reported. Message: java.nio.file.NoSuchFileException: public
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:706)
        at org.jooby.Jooby.bootstrap(Jooby.java:2753)
        at org.jooby.Jooby.start(Jooby.java:1960)
        at org.jooby.Jooby.start(Jooby.java:1942)
        at org.jooby.Jooby.run(Jooby.java:1872)
        at org.jooby.gradleDemo.Main.main(Main.java:34)
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: public
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at javaslang.control.Try.getOrElseThrow(Try.java:473)
        at org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2690)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        ... 8 common frames omitted
Caused by: java.nio.file.NoSuchFileException: public
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at org.jooby.internal.assets.Watcher.registerAll(Watcher.java:86)
        at org.jooby.internal.assets.Watcher.<init>(Watcher.java:102)
        at org.jooby.internal.assets.LiveCompiler.<init>(LiveCompiler.java:67)
        at org.jooby.assets.Assets.configure(Assets.java:325)
        at org.jooby.Jooby.install(Jooby.java:3144)
        at org.jooby.Jooby.lambda$bindService$49(Jooby.java:2833)
        at org.jooby.Jooby.lambda$null$44(Jooby.java:2689)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$bootstrap$47(Jooby.java:2678)
        ... 12 common frames omitted
```

PS: Maybe it would be a good idea, once it works correctly, to provide this or a similar example project somewhere in the documentation or under the jooby-project umbrella. So that other can refer to it for later use.

[1]: https://github.com/authchir/jooby-gradle-demo

**Comment by jknack** [comment]
There is an existing [demo](https://github.com/jooby-project/devdayar16) (more or less). You will see there how to use the asset module in development as well as in prod like env.

The `prod` distribution is generated by `mvn clean package`, then you started the application with `stork` launcher using a none dev environment (like uat, test, stage, prod). This none dev environment makes the Asset module to use the bundled and optimized asset files generated by `mvn clean package`. That's how the asset module should be used it bc in prod mode all the heavyweight dependencies (j2v8, babel.js, etc...) are not required.

Finally, also think there is a bug here (not only bad usage) where the Asset module assumes there is a `public` classpath directory and isn't there.

It is probably better to remove the optimization via conf file as you early pointed out. Are you able to send a pull request?

**Comment by authchir** [comment]
> There is an existing demo (more or less). You will see there how to use the asset module in development as well as in prod like env.

Yes, I looked at this example project. But I was more referring to an example of a Gradle project, where things like the transitive dependencies would be visible.

> This none dev environment makes the Asset module to use the bundled and optimized asset files generated by mvn clean package. That's how the asset module should be used it bc in prod mode all the heavyweight dependencies (j2v8, babel.js, etc...) are not required.

This is the big question. Were is the static generation of the assets implemented? Is it done by the `jooby-maven-plugin`? If yes, it explains why it does not work with Gradle.

**Comment by jknack** [comment]
We do have a joobyAssets task: HTTP://jooby.org/doc/gradle via https://github.com/jooby-project/jooby/tree/master/jooby-gradle-plugin

**Comment by authchir** [comment]
Oh, somehow I did not notice this command. I just tried a few different use of it did not manage to generate a distribution that can run outside of `joobyRun`. I am probably doing something wrong. Can you provide an example based on this simple project?
