### ISSUE TITLE
Cannot find jackson class

### ISSUE THREAD

**Issue by mcjp78** [jooby-project/jooby#664]
Hi,
I'm having this issue while starting jooby. I am using maven and have included jackson in classpath.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude$Value
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:44)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:483)
	at org.jongo.marshall.jackson.configuration.AbstractMappingBuilder.<init>(AbstractMappingBuilder.java:39)
	at org.jongo.marshall.jackson.JacksonMapper$Builder.<init>(JacksonMapper.java:63)
	at org.jooby.mongodb.Jongoby.<init>(Jongoby.java:108)
	at pw.jeopy.CheckServer.App.<init>(App.java:27)
	at org.jooby.Jooby.run(Jooby.java:1849)
	at pw.jeopy.CheckServer.App.main(App.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonInclude$Value
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by jknack** [comment]
Starting from where? Guess it is from IDE, right?

Make sure your IDE has been updated with your project dependencies.

Also, can you share your `pom.xml` and the output of `mvn dependencies:tree`?

**Comment by mcjp78** [comment]
Both maven and ide, but I fixed it.

What an odd error though, the Jackson annotation package version didn't match that of the rest of Jackson dependencies. I thought it was the point of maven to prevent that...
