### ISSUE TITLE
The Ebean module doesn't work. 

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#695]
Hi,
First of all many thanks toyou for making this great framework Jooby!
Following the guide and documentation I  setup my first trial jooby project, and I want to use Ebean.  I wrote just an entity class com.mycompany.Person like

@Entity
public class Person {
    @Id
    Long id;
    String name;
    int workYear;
    Date birthday;
}

and a MVC class route com.mycompany.PersonController like

public class PersonController {
    @Inject
    EbeanServer ebeanServer;

    @GET @POST
    @Path("/person/add")
    public String add(Person person){
        ebeanServer.save(person);
        return person.id.toString();
    }

    @GET
    @Path("/person/show")
    public Person show(Long id){
        Ebean.find(Person.class, id);
        return ebeanServer.find(Person.class, id);
    }
}

Also I introduced the ebean module in the starter class

public class App extends Jooby {
  {
    use(new Ebeanby().doWith( conf -> {
        //conf.addClass(Person.class);   //this is commented because it just causes a compile error
    }));
  }
  ......
}

Please note that above I comment the code line for conf.addClass(Person.class) because it causes an compile error "cannot resolove method 'addClass(...)'" for conf object. I debug and found this lambda callback was called 2 times.  And at frist time this "conf" object is an instance of  com.zaxxer.hikari.HikariConfig class, not of com.avaje.ebean.config.ServerConfig class.

When I mvn jobby:run this app and access to url :http://localhost:8080/person/add,  it just response error
message:  "The type [class com.mycompany.Person] is not a registered entity? If you don't explicitly list the entity classes to use Ebean will search for them in the classpath. If the entity is in a Jar check the ebean.search.jars property in ebean.properties file or check ServerConfig.addJar().  ". Obviously it was because I commented that line. Ebean didn't register Person entity class.

Then I modified the code  like following to cast the object,  and it just worked!

if(conf instanceof com.avaje.ebean.config.ServerConfig) ((com.avaje.ebean.config.ServerConfig)conf).addClass(Person.class);

I know Ebean module inherits from JDBC module, maybe this is the cause for the compiling error. 

Further more,  I wish ebean would auto-find my entities class, rather than adding them manually.  My conf/application.conf file is:

db = mem
ebean.defaultServer = true
ebean.register = true
ebean.ddl.generate=true
ebean.ddl.run=true
ebean.debug.sql=true
ebean.debug.lazyload=false
ebean.disableClasspathSearch = false
ebean.search.packages = com.mycompany

Thank you.

Thomas

**Comment by jknack** [comment]
Hi,

 You're right the error comes from Jdbc module and the use of generics :(

 You can easily fix this by using the object type in the lambda callback:

```java
use(new Ebeanby().doWith(ServerConfig conf -> {
   conf.addClass(Person.class);
});
``` 

Why is this? The `doWith` is a common name between modules that let you configure something... Some jdbc modules (like ebean) need to configure one or more sub-systems (including the DataSource itself)... so we add the generic doWith method to follow/keep the Jooby module convention. The drawback is that you need to add the type and the documentation need to be updated.

Here is an example where you can configure hikari and ebean:


 ```java
use(new Ebeanby()
   .doWith(HikariConfig conf -> {
      ...
    })
    .doWith(ServerConfig conf -> {
     conf.addClass(Person.class);
   });
``` 

Going to mark this issue as documentation enhancement.

auto-find? Set the `ebean.disableClasspatSearch = true`

Glad you enjoy Jooby!

**Comment by thomasguo** [comment]
Thank you, @jknack .
Actually I had tried ebean.disableClasspatSearch = true  or ebean.disableClasspatSearch = false, but neither work.

**Comment by thomasguo** [comment]
Just now I upgraded to jooby 1.1.0 and used the new ebean-starter project,  the issue disappeared. No idea what the root cause is but problem solved, anyway.

**Comment by jknack** [comment]
@thomasguo Cool! Also, I created this: https://github.com/jooby-project/ebean-starter just for you!

**Comment by thomasguo** [comment]
@jknack  Thank you, that ebean-starter project really helps a lot.   But when using it  I found another issue:  the hot reloading doesnt work.  Stack message on the console is:

[INFO] Scanning for projects...
Exception in thread "HotswapScanner" javax.xml.parsers.FactoryConfigurationError
: Provider __redirected.__SAXParserFactory not found
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:200)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:
127)
        at groovy.xml.FactorySupport$2.run(FactorySupport.java:58)
        at java.security.AccessController.doPrivileged(Native Method)
        at groovy.xml.FactorySupport.createFactory(FactorySupport.java:35)
        at groovy.xml.FactorySupport.createSaxParserFactory(FactorySupport.java:
56)
        at groovy.util.XmlSlurper.<init>(XmlSlurper.java:128)
        at groovy.util.XmlSlurper.<init>(XmlSlurper.java:114)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstru
ctor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteN
oUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor
(AbstractCallSite.java:255)
        at io.repaint.maven.tiles.TileModel$_strippedPom_closure2.doCall(TileMod
el.groovy:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.codehaus.groovy.runtime.IOGroovyMethods.withReader(IOGroovyMethod
s.java:1183)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.withReader(Resource
GroovyMethods.java:1604)
        at org.codehaus.groovy.runtime.dgm$1027.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMetho
dSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMeta
MethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
llSite.java:125)
        at io.repaint.maven.tiles.TileModel.strippedPom(TileModel.groovy:29)
        at io.repaint.maven.tiles.TileModel.loadTile(TileModel.groovy:52)
        at io.repaint.maven.tiles.TileModel.<init>(TileModel.groovy:57)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.loadModel(Tiles
MavenLifecycleParticipant.groovy:216)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.loadAllDiscover
edTiles(TilesMavenLifecycleParticipant.groovy:639)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.orchestrateMerg
e(TilesMavenLifecycleParticipant.groovy:338)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.afterProjectsRe
ad(TilesMavenLifecycleParticipant.groovy:286)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.jooby.JoobyMojo.lambda$execute$2(JoobyMojo.java:208)
        at org.jooby.JoobyMojo.lambda$setupCompiler$4(JoobyMojo.java:292)
        at org.jooby.run.Watcher.processEvents(Watcher.java:142)
        at org.jooby.run.Watcher.lambda$new$0(Watcher.java:68)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: __redirected/__SAXParserFactory
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:1
24)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
        ... 48 more

**Comment by jknack** [comment]
Tried it yesterday and the only thing didn't work was the query-beans #697 

Did you get this error with ebean-starter project? How can I reproduce it?

**Comment by thomasguo** [comment]
Yes, this error occurs both in ebean-starter project and my own project.  I ran it with command  "mvn jooby:run" .  It could start and run normally.  Only in case I try to modify some code the error occurs and modified code were not compiled hottly.  

My dev env is:
Maven home: D:\green\maven-3.3.1
Java version: 1.8.0_60, vendor: Oracle Corporation
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
