### ISSUE TITLE
Postgresql database reload with 1.1.0

### ISSUE THREAD

**Issue by olabomba** [jooby-project/jooby#705]
Hi,
With 1.0.3 the class reload works perfectly.
However, in 1.1.0, with the combination Hibernate + Postgresql an error is occuring when reloading, as soon as I modify a class.
I've switched back to 1.0.3.
Regards.

**Comment by jknack** [comment]
Odd, will look later but will be great is you can isolate the problem and provide an example project to reproduce the error.

Also, did you get an error?

**Comment by olabomba** [comment]
Here is the trace:

```
at.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:postgresql://localhost:5432/localdb
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:88)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:323)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
	at org.jooby.jdbc.Jdbc.configure(Jdbc.java:365)
	at org.jooby.hbm.Hbm.configure(Hbm.java:484)
	at org.jooby.Jooby.install(Jooby.java:3132)
	at org.jooby.Jooby.lambda$bindService$52(Jooby.java:2821)
	at org.jooby.Jooby.lambda$null$47(Jooby.java:2677)
	at javaslang.control.Try.run(Try.java:52)
	at org.jooby.Jooby.lambda$bootstrap$50(Jooby.java:2666)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at org.jooby.Jooby.lambda$new$0(Jooby.java:683)
	at org.jooby.Jooby.bootstrap(Jooby.java:2741)
	at org.jooby.Jooby.start(Jooby.java:1954)
	at org.jooby.Jooby.start(Jooby.java:1935)
	at org.jooby.Jooby.run(Jooby.java:1865)
	at today.localshop.App.main(App.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jooby.run.Main.lambda$startApp$1(Main.java:241)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:81)
	... 33 more

[2017-03-28 17:41:59,891]-[HotSwap] INFO  fr.joobytest.App - Stopped
[2017-03-28 17:41:59,896]-[HotSwap] ERROR fr.joobytest.App - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.jooby.spi.HttpHandler was bound.
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.netty.NettyServer.<init>(NettyServer.java:81)
  at org.jooby.netty.Netty.configure(Netty.java:36)

2) An exception was caught and reported. Message: Failed to get driver instance for jdbcUrl=jdbc:postgresql://localhost:5432/localdb
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)

```

The driver is well reloaded in 1.0.3.

**Comment by jknack** [comment]
Add this to your `.conf`:

```
hikari.dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
```

make sure you are on 42 version:

```xml
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>42.0.0</version>
</dependency>
```

Will fix it soon.
