### ISSUE TITLE
MockRouter throws UnsupportedOperationException with RequestLogger enabled

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#720]
Hi,

I am trying to create some  unit tests. This code works finde:

` MockRouter mockRouter = new MockRouter(new Electra());
 String result = mockRouter.get("/hello");
`

But as soon as I add this line to my app:

`use("*", new RequestLogger().latency().log(REQUEST_LOG::debug));`

I get an exception:

````
java.lang.UnsupportedOperationException: public abstract void org.jooby.Response.complete(org.jooby.Route$Complete)

	at org.jooby.test.MockRouter.lambda$empty$11(MockRouter.java:465)
	at com.sun.proxy.$Proxy5.complete(Unknown Source)
	at org.jooby.Response$Forwarding.complete(Response.java:223)
	at org.jooby.RequestLogger.handle(RequestLogger.java:238)
	at org.jooby.test.MockRouter.execute(MockRouter.java:367)
	at org.jooby.test.MockRouter.execute(MockRouter.java:347)
	at org.jooby.test.MockRouter.get(MockRouter.java:327)
	at com.cedarsoft.autoresultat.server.test.SampleTest.basic(SampleTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
````

**Comment by jknack** [comment]
Yea, you need to mock Response.complete

```java
Response rsp = EasyMock.createMock(Response.class);
EasyMock.expect(rsp.complete(...)).andReturn(...);

new MockRouter(new Electra(), req, rsp);
```

This is an EasyMock example but you are free to use any other mock library.

**Comment by jschneider** [comment]
complete() is void. So probably the code has to look a little bit different.
With Mockito this seems to work:

````
    Request request = Mockito.mock(Request.class);
    Response response = Mockito.mock(Response.class);
    Mockito.doNothing().when(response).complete(ArgumentMatchers.any());

    mockRouter = new MockRouter(new Electra(), request, response);
````
