### ISSUE TITLE
debug: java.lang.NoClassDefFoundError: javaslang/control/Try$CheckedConsumer

### ISSUE THREAD

**Issue by pierredavidbelanger** [jooby-project/jooby#733]
This is more a question here.

I try to follow [this doc](http://jooby.org/doc/devtools/#maven-options) to enable debug.

I start the application with:

```bash
mvn clean jooby:run -Dapplication.fork=true -Dapplication.debug=true
```

I see this exception:

```
Listening for transport dt_socket at address: 8000
Exception in thread "main" java.lang.NoClassDefFoundError: javaslang/control/Try$CheckedConsumer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jooby.run.AppModuleLoader.newModule(AppModuleLoader.java:85)
	at org.jooby.run.AppModuleLoader.build(AppModuleLoader.java:74)
	at org.jooby.run.Main.<init>(Main.java:86)
	at org.jooby.run.Main.main(Main.java:156)
Caused by: java.lang.ClassNotFoundException: javaslang.control.Try$CheckedConsumer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
```

And this one:

```
Exception in thread "Thread-2" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javaslang/control/Try$CheckedRunnable
	at org.jooby.JoobyMojo$ShutdownHook.run(JoobyMojo.java:74)
Caused by: java.lang.NoClassDefFoundError: javaslang/control/Try$CheckedRunnable
	... 1 more
Caused by: java.lang.ClassNotFoundException: javaslang.control.Try$CheckedRunnable
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 1 more
```

This application do not start, and I am back to the shell prompt.

I guess there is a dependency not met, but I fail to see it.

**Comment by huysamen** [comment]
It's the `-Dapplication.fork=true` causing it. See #698. It has been fixed in 1.1.1.

**Comment by pierredavidbelanger** [comment]
@huysamen you are absolutely right.
I just tested my app with `1.1.1-SNAPSHOT` and it works.
I will close this one.

**Comment by prepor** [comment]
Have the same error with `gradle joobyAssets`:

```
Caused by: java.lang.NoSuchMethodError: javaslang.control.Try.of(Ljavaslang/control/Try$CheckedSupplier;)Ljavaslang/control/Try;
        at org.jooby.run.JoobyProject.lambda$newClassLoader$2(JoobyProject.java:304)
        at org.jooby.run.JoobyProject.newClassLoader(JoobyProject.java:305)
        at org.jooby.run.JoobyContainer.run(JoobyContainer.java:242)
        at org.jooby.run.AssetTask.process(AssetTask.java:270)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```

**Comment by jknack** [comment]
@prepor is there anything more in the stacktrace?

Please file a new issue.

Thanks
