### ISSUE TITLE
HikariCp: mySQL 6.x driver support

### ISSUE THREAD

**Issue by adewaleafolabi** [jooby-project/jooby#763]
While trying the ebean starter application with mysql i encountered the error below. It seems the newer version (6.0.6) of MySQL driver is not compatible with Hikaricp. 

`[2017-05-09 13:49:46,742]-[HotSwap] INFO  com.zaxxer.hikari.HikariDataSource - mysql.library - Starting...
May 09, 2017 1:49:46 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource from [Module "starter.ebean.ebean-starter:main" from AppModuleLoader@23dbe385 for finders []]
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource from [Module "starter.ebean.ebean-starter:main" from AppModuleLoader@23dbe385 for finders []]
        at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:93)
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:319)
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
        at org.jooby.jdbc.Jdbc.configure(Jdbc.java:365)
        at org.jooby.ebean.Ebeanby.configure(Ebeanby.java:187)
        at org.jooby.Jooby.install(Jooby.java:3132)
        at org.jooby.Jooby.lambda$bindService$52(Jooby.java:2821)
        at org.jooby.Jooby.lambda$null$47(Jooby.java:2677)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$bootstrap$50(Jooby.java:2666)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:683)
        at org.jooby.Jooby.bootstrap(Jooby.java:2741)
        at org.jooby.Jooby.start(Jooby.java:1954)
        at org.jooby.Jooby.start(Jooby.java:1935)
        at org.jooby.Jooby.run(Jooby.java:1865)
        at starter.ebean.App.main(App.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jooby.run.Main.lambda$startApp$1(Main.java:242)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

Also from HikariCp's github page there's a warning there

⚠ MySQL and MariaDB DataSources are known to be broken with respect to network timeout support. Use jdbcUrl configuration instead.

I've attached the full log file as a zip. 
[error.log.zip](https://github.com/jooby-project/jooby/files/986613/error.log.zip)

**Comment by huysamen** [comment]
It's because the MySQL driver package name changed from 5.x to 6.x. For now use any version 5.x of the driver (such as the version included in Jooby) until all the relevant modules (jdbc, ebean, hikari etc) can be upgraded. I think I have a branch like that somewhere, will try to do PR sometime this week.

**Comment by jknack** [comment]
We now support 6.x mySQL driver, but you need to add it manually to your classpath.

See #780
