### ISSUE TITLE
Exceptions thrown from handler methods appear in log

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#764]
```
@SuppressWarnings({"unchecked", "rawtypes" })
public class ExceptionsStillGoInLog extends Jooby {
  {
    use(new Jackson());
    get("/", (req, rsp) -> {
      throw new UnsupportedOperationException("goodbye");
    });
    err((req, rsp, err) -> {
      rsp.send(err.getCause().getMessage());
    });
  }
  public static void main(final String[] args) {
    run(ExceptionsStillGoInLog::new, args);
  }
}
```
And this is wha goes in the log:

```
19:32:46.151 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - execution of: GET/ resulted in exception
java.lang.UnsupportedOperationException: goodbye
	at mypkg.ExceptionsStillGoInLog.lambda$new$0(ExceptionsStillGoInLog.java:12)
	at org.jooby.Route$Handler.handle(Route.java:1720)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:97)
	at org.jooby.internal.RouteChain.next(RouteChain.java:77)
	at org.jooby.Route$Chain.next(Route.java:2109)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:312)
	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:91)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
19:32:46.161 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: mypkg.ExceptionsStillGoInLog$$Lambda$11/1159785389@5419f379
```

The decision to log the exception or not should come after (or inside) the err() handling block, IMO:

```
err((req, rsp, err) -> {
  log(err);
});
```

**Comment by jknack** [comment]
Hi @paul-hammant you logback.xml is in DEBUG mode:

>  DEBUG org.jooby.spi.HttpHandler - execution of: GET/ resulted in exception

If you need debug, set/use debug for your application package/namespace
