### ISSUE TITLE
Assets module doesn't work in case deploy as a war file

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#766]
Hi,

I like to use the Assets module.  If I run the quickstart demo application via  mvn jooby:run, it works.  If I package the application as a fat-jar, it runs well.  But if I package the app into an war file and put it under a tomcat server, it cannot start and throws an NoSuchFileException exception:

=====================================================
10-May-2017 17:00:33.245 INFO [localhost-startStop-1] com.google.inject.internal
.MessageProcessor.visit An exception was caught and reported. Message: java.nio.
file.NoSuchFileException: public
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: public
        at com.google.common.base.Throwables.propagate(Throwables.java:240)
        at javaslang.control.Try.getOrElseThrow(Try.java:473)
        at org.jooby.Jooby.lambda$bootstrap$50(Jooby.java:2678)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:
340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.
java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInje
ctorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:683)
        at org.jooby.Jooby.bootstrap(Jooby.java:2741)
        at org.jooby.Jooby.start(Jooby.java:1954)
        at org.jooby.Jooby.start(Jooby.java:1935)
        at org.jooby.Jooby.start(Jooby.java:1925)
        at org.jooby.servlet.ServerInitializer.contextInitialized(ServerInitiali
zer.java:60)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContex
t.java:4772)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContex
t.java:5196)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase
.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:70
1)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)

        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:917)

        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:
1701)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: public
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.j
ava:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.jav
a:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.jav
a:102)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFile
AttributeViews.java:53)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFile
AttributeViews.java:38)
        at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystem
Provider.java:193)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at org.jooby.internal.assets.Watcher.registerAll(Watcher.java:86)
        at org.jooby.internal.assets.Watcher.<init>(Watcher.java:102)
        at org.jooby.internal.assets.LiveCompiler.<init>(LiveCompiler.java:67)
        at org.jooby.assets.Assets.configure(Assets.java:325)
        at org.jooby.Jooby.install(Jooby.java:3132)
        at org.jooby.Jooby.lambda$bindService$52(Jooby.java:2821)
        at org.jooby.Jooby.lambda$null$47(Jooby.java:2677)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$bootstrap$50(Jooby.java:2666)
        ... 25 more
=====================================================

And the app is very simple like here:

public class App extends Jooby {

  {
    use(new Assets());
    get("/", () -> "Hello World!");
  }

  public static void main(final String[] args) {
    run(App::new, args);
  }

**Comment by jknack** [comment]
There are 2 options:

1. Set `assets.watch` to false
2. Set `application.env` to something different of `dev` (like uat, stage, prod, etc..)

The LiveCompiler fails to start due the `public` directory isn't available. The livecompiler is an optional `dev` only tool.

**Comment by thomasguo** [comment]
Got it.  I have verified that 2 options actually work. Thanks.
