### ISSUE TITLE
Exceptions in log for missing resources, despite 404 handler.

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#789]
Jooby v1.1.1

Clipped from AppEngine log:

```
A  org.jooby.Err: Not Found(404): /stssys.htm
A  	at org.jooby.internal.HttpHandlerImpl.lambda$routes$10(HttpHandlerImpl.java:446)
A  	at org.jooby.internal.FallbackRoute.handle(FallbackRoute.java:113)
A  	at org.jooby.internal.RouteChain.next(RouteChain.java:77)
A  	at org.jooby.Route$Chain.next(Route.java:2109)
A  	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:312)
A  	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:91)
A  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
A  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
A  	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
A  	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
A  	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
A  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
A  	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
A  	at java.lang.Thread.run(Thread.java:745)
A  07:43:26.855 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: org.jooby.Router$$Lambda$28/1150284200@7f77e91b
A  07:43:26.855 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: org.jooby.Router$$Lambda$28/1150284200@2357d90a
A  07:43:26.855 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: com.paulhammant.buildradiator.BuildRadiatorMain$$Lambda$30/1663619914@145eaa29
A  07:43:28.471 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - execution of: POST/command.php resulted in exception
A  org.jooby.Err: Not Found(404): /command.php
A  	at org.jooby.internal.HttpHandlerImpl.lambda$routes$10(HttpHandlerImpl.java:446)
A  	at org.jooby.internal.FallbackRoute.handle(FallbackRoute.java:113)
A  	at org.jooby.internal.RouteChain.next(RouteChain.java:77)
A  	at org.jooby.Route$Chain.next(Route.java:2109)
A  	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:312)
A  	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:91)
A  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
A  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
A  	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
A  	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
A  	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
A  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
A  	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
A  	at java.lang.Thread.run(Thread.java:745)
A  07:43:28.472 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: org.jooby.Router$$Lambda$28/1150284200@7f77e91b
A  07:43:28.472 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: org.jooby.Router$$Lambda$28/1150284200@2357d90a
A  07:43:28.472 [netty task-4-1] DEBUG org.jooby.spi.HttpHandler - handling err with: com.paulhammant.buildradiator.BuildRadiatorMain$$Lambda$30/1663619914@145eaa29
A  GET 200 57 B 4 ms Wget(linux) /cgi/common.cgi GET 200 57 B 4 ms Wget(linux) 
A  GET 200 57 B 9 ms Wget(linux) /stssys.htm GET 200 57 B 9 ms Wget(linux) 
A  GET 200 6.44 KB 5 ms Wget(linux) / GET 200 6.44 KB 5 ms Wget(linux) 
A  POST 200 57 B 4 ms Wget(linux) /command.php POST 200 57 B 4 ms Wget(linux) 
A  GET 200 6.44 KB 3 ms Mozilla/5.0 / GET 200 6.44 KB 3 ms Mozilla/5.0 
A  GET 200 6.44 KB 3 ms curl/7.17.1 (mips-unknown-linux-gnu) libcurl/7.17.1 OpenSSL/0.9.8i zlib/1.2.3 / GET 200 6.44 KB 3 ms curl/7.17.1 (mips-unknown-linux-gnu) libcurl/7.17.1 OpenSSL/0.9.8i zlib/1.2.3 
```
There's a err(404,...) `handler` which works just fine for many bogus routes that malware is trying to discover on my server. But these two, `/stssys.htm` and `/command.php` have stack traces in the log, whereas others do not. Weird.

Also AppEngine is doing one whole log entry per line of stack trace, but I think that is their problem, not Jooby's.

**Comment by jknack** [comment]
> DEBUG org.jooby.spi.HttpHandler - execution of: POST/command.php resulted in exception

Don't set the default/global log level to DEBUG, use INFO. If you truly need debug in a prod server either:

- use debug for your application package
- turn off the org.jooby.spi.HttpHandler logger

**Comment by paul-hammant** [comment]
Here's what I have for `/conf/logback.xml`, dude:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true" scanPeriod="15 seconds" debug="false">
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>[%d{ISO8601}]-[%thread] %-5level %logger - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```

**Comment by jknack** [comment]
That looks fine, which is odd.

Something else is going on bc these lines:

> DEBUG org.jooby.spi.HttpHandler - execution of: POST/command.php resulted in exception

Clearly go out as debug :(
