### ISSUE TITLE
Multiple entries with same key

### ISSUE THREAD

**Issue by DrorBuhnik** [jooby-project/jooby#802]
Using this kind MVC route:
```
@Path("/")
@MyAnnotation(test = true)
public class MyRoute {

    @GET
    @Path("/test1")
    public Result test1() {
        return Results.ok();
    }

    @GET
    @Path("/:dummy")
    public Result test2(String dummy) {
        return Results.ok();
    }
}
```

will result in
```
java.lang.IllegalArgumentException: Multiple entries with same key: test=true and test=true,
    at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186),
    at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102),
    at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88),
    at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359),
    at org.jooby.internal.RouteChain.attrs(RouteChain.java:100),
    at org.jooby.internal.RouteChain.next(RouteChain.java:74),
    at org.jooby.Route$Chain.next(Route.java:2109),
    at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:312),
    at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:91),
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105),
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362),
    at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38),
    at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353),
    at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66),
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858),
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144),
    at java.lang.Thread.run(Thread.java:748)
```

There is no way that I know to workaround this issue
Currently we are doing some ugly things like removing 'test1' from the route list and manually checking the parameter in 'test2'

BTW, I love working with Jooby, it's a great project! Thanks for all your hard work

**Comment by jknack** [comment]
It's a great project and glad you enjoy it!

What version of jooby are you running?
It should work in latest release 1.1.2

**Comment by DrorBuhnik** [comment]
Currently 1.1.1
I'm check with the latest 1.1.2 and will update

**Comment by DrorBuhnik** [comment]
1.1.2 fixed the issue!
Many thanks
