### ISSUE TITLE
Incompatible Class Change Error when running Jooby Ebean Starter on Java 9-ea

### ISSUE THREAD

**Issue by fwgreen** [jooby-project/jooby#832]
I tried the Ebean Starter on Java 9-ea b176.  It compiles but doesn't run:
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/jooby/Env. Method lambda$static$0(Lcom/typesafe/config/Config;Lorg/jooby/Router;Ljava/util/Locale;)Lorg/jooby/Env; at index 277 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.jooby.Env.<clinit>(Env.java:518)
	at org.jooby.Jooby.<init>(Jooby.java:835)
	at org.jooby.Jooby.<init>(Jooby.java:892)
	at starter.ebean.App.<init>(App.java:10)
	at org.jooby.Jooby.run(Jooby.java:2072)
	at starter.ebean.App.main(App.java:14)
```

**Comment by jknack** [comment]
Well yea this is the first try on Java 9 😄 

It is probably good time to start playing with it

**Comment by MrPowerGamerBR** [comment]
Now that Java 9 is released... when can we expect a fix? This is still happening with the latest Jooby version (on Maven Central) + `Java(TM) SE Runtime Environment (build 9+181)`

**Comment by simon-nicholls** [comment]
Just encountered this, as my Arch switched to Java 9 as default.

Looking around on the net at similar errors, I see updating the ASM dependency to 6.0 being touted as a fix. e.g. 

https://github.com/bdonlan/invokedynamic-proxy/issues/12

**Comment by simon-nicholls** [comment]
Thanks @jknack!

I built `1.2.0-SNAPSHOT` with JDK 1.8, updated my project pom to use it, and used a `3.0.0-M1` `maven-enforcer-plugin` build/plugins/plugin override to get its JDK version parsing fix.

 Initial tests look good.

**Comment by jknack** [comment]
Did you see the warning about illegal reflection access? I couldn't figure it out.

**Comment by simon-nicholls** [comment]
I do if I try to `mvn install` Jooby itself with JDK 9:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jooby.JoobyRunTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.158 sec <<< FAILURE! - in org.jooby.JoobyRunTest
initializationError(org.jooby.JoobyRunTest)  Time elapsed: 0.007 sec  <<< ERROR!
org.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by org/powermock/core/classloader/MockClassLoader cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
```

Looks like `powermock 2.0.0-beta.5` adds the required JDK 9 support:

https://github.com/powermock/powermock/issues/783
