### ISSUE TITLE
jooby-maven-plugin:spec - Kotlin supported?

### ISSUE THREAD

**Issue by Ingwersaft** [jooby-project/jooby#835]
Hi,

I was playing around with the jooby kotlin starter and tried to add jooby-swagger, but I get the following problem when building:

```
mvn -X clean package 
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.8.0-58-generic", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building kotlin-starter 1.1.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kotlin-starter ---
[INFO] Deleting /home/mauer/workspace/jooby-kotlin-starter/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce.versions) @ kotlin-starter ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ kotlin-starter ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ kotlin-starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/mauer/workspace/jooby-kotlin-starter/src/main/resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ kotlin-starter ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- kotlin-maven-plugin:1.1.2-5:compile (compile) @ kotlin-starter ---
[INFO] Kotlin Compiler version 1.1.2-5
[WARNING] Source root doesn't exist: /home/mauer/workspace/jooby-kotlin-starter/target/generated-sources/annotations
[INFO] Compiling Kotlin sources from [/home/mauer/workspace/jooby-kotlin-starter/src/main/kotlin]
[INFO] Module name is kotlin-starter
[INFO] 
[INFO] --- jooby-maven-plugin:1.1.3:spec (default) @ kotlin-starter ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.872 s
[INFO] Finished at: 2017-07-14T08:46:44+02:00
[INFO] Final Memory: 40M/428M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jooby:jooby-maven-plugin:1.1.3:spec (default) on project kotlin-starter: Can't build route spec for: starter.kotlin.AppKt: starter.kotlin.AppKt.<init>() -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooby:jooby-maven-plugin:1.1.3:spec (default) on project kotlin-starter: Can't build route spec for: starter.kotlin.AppKt
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Can't build route spec for: starter.kotlin.AppKt
        at org.jooby.RouteProcessorMojo.execute(RouteProcessorMojo.java:247)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.InstantiationException: starter.kotlin.AppKt
        at java.lang.Class.newInstance(Class.java:427)
        at org.jooby.JoobyRunner.run(JoobyRunner.java:240)
        at org.jooby.RouteProcessorMojo.execute(RouteProcessorMojo.java:243)
        ... 22 more
Caused by: java.lang.NoSuchMethodException: starter.kotlin.AppKt.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 24 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

You can find my code [here](https://github.com/Ingwersaft/kotlin-starter).
Is Kotlin unsupported by the spec goal, or did I something wrong? Help would be appreciated :)

Thanks in advance!

**Comment by jknack** [comment]
It is not supported :( but support is coming see #758.

Still, Mvc routes should work better today in Kotlin

**Comment by Ingwersaft** [comment]
Alright, finally got it working using Mvc routes :)
I had alot of problems (well, swagger.json was empty regardless what I tried) until I looked at the SwaggerUI source and saw:
```
  private static final Pattern TAG = Pattern.compile("(api)|/");
  private Predicate<RouteSpec> predicate = r -> r.pattern().startsWith("/api");
```
Adding `api` to my path and Voila! It works!
I just now looked again at [the docu](http://jooby.org/doc/spec/#swagger-options) and the default `api` filter mentioned... well maybe I'm blind 😆 

Thanks for the quick response and thanks for creating such an awesome framework 👍

**Comment by jknack** [comment]
Cool!

Yea there is a default `/api` filter (needs to be more visible) 😄

**Comment by Ingwersaft** [comment]
One more thing :smile: 
When I have a method returning Unit it seems this breaks the generated API spec (at least swagger-ui can't load the generated swagger.json)
```
swagger-client.js:1022 Uncaught TypeError: Cannot read property 'void' of undefined
    at Operation.resolveModel (swagger-client.js:1022)
    at new Operation (swagger-client.js:938)
    at SwaggerClient.buildFromSpec (swagger-client.js:690)
    at Resolver.resolve (swagger-client.js:416)
    at Object.response (swagger-client.js:592)
    at process.EventEmitter.response (swagger-client.js:3271)
    at process.EventEmitter.EventEmitter.emit (shred.bundle.js:1391)
    at emit (shred.bundle.js:1191)
    at shred.bundle.js:1211
    at setBodyAndFinish (shred.bundle.js:1815)
```
And the corresponding (I think) part of the spec:
```
"responses": {
          "204": {
            "schema": {
              "$ref": "#/definitions/void"
            }
          }
        }
```

**Comment by jknack** [comment]
More kotlin support is comming see #858 

Going to test and fix unit results
