### ISSUE TITLE
Jars don't include in stork

### ISSUE THREAD

**Issue by Shbnv** [jooby-project/jooby#836]
4 jars don't include in stork archive. Classes from these jars also don't include in fat jar. These jars are j2v8_win32_x86_64-4.6.0.jar, jooby-assets-clean-css-1.1.3.jar, jooby-assets-j2v8-1.1.3.jar, jooby-assets-less-1.1.3.jar 

If these jars copy in lib folder manually stork work correctly.

pom.xml:
`
<dependencies>

        
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-undertow</artifactId>
            <version>1.1.3</version>
        </dependency>
        
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-assets</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-assets-less</artifactId>
            <version>1.1.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-assets-clean-css</artifactId>
            <version>1.1.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-ftl</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-guava-cache</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-pac4j</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-jdbc</artifactId>
            <version>1.1.3</version>
            <exclusions>
                <exclusion>
                    <groupId>com.zaxxer</groupId>
                    <artifactId>HikariCP</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        

        
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.1.1</version>
        </dependency>

        
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.6.2</version>
        </dependency>
        
        
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.16</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.16</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jooby</groupId>
                <artifactId>jooby-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>assets</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>`

**Comment by jknack** [comment]
Hi Svan,

 That's right. Asset dependencies (j2v8, clean-css, etc.) are usually too expensive to include in the final application (fat-jar or stork).

A final application should be started with an environment, like:

    bin/myapp --start prod

Why? In `dev` mode we want to compile assets on the fly, it helps us to be more productive but also it is more expensive in terms of memory and cpu. Starting the application in any other mode, use the already processed assets so there is no extra overhead.

If you truly want `dev` behaviour in your final application then just remove the `provided` scope line for those library in your `pom.xml`

Cool?

**Comment by Shbnv** [comment]
I tried run:
`c:\takeda\run>bin\myapp.bat --run prod
Jul 17, 2017 9:48:18 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.ClassNotFoundExce
ption: org.jooby.assets.Less
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jooby.assets.L
ess
        at com.google.common.base.Throwables.propagate(Throwables.java:240)
        at javaslang.control.Try.getOrElseThrow(Try.java:473)
        at org.jooby.Jooby.lambda$bootstrap$50(Jooby.java:2885)`

**Comment by Shbnv** [comment]
In addition:
`c:\myapp\run>bin\myapp.bat --install prod
This version of c:\myapp\run\bin\myapp64.exe is not compatible with
 the version of Windows you're running. Check your computer's system information
 and then contact the software publisher.`

**Comment by jknack** [comment]
How did you build the stork distribution?

Can you share your pom.xml?

**Comment by Shbnv** [comment]
ok
[pom.zip](https://github.com/jooby-project/jooby/files/1152669/pom.zip)
[stork.zip](https://github.com/jooby-project/jooby/files/1152670/stork.zip)

**Comment by jknack** [comment]
Couple of comments:

1. add the `<scope>provided</scope>` to less and clean-css dependencies
2. you don't need to specify the jooby version on jooby dependencies, remove all them and you will get a clean pom
3. if you need/want a recent version of hikari just set the property <hikari.version>

It should looks like (didn't try):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jooby</groupId>
        <artifactId>modules</artifactId>
        <version>1.1.3</version>
    </parent>

    <artifactId>myapp</artifactId>
    <groupId>my.app</groupId>
    <version>1.0-SNAPSHOT</version>

    <name>MyApp</name>
    <description>generated by Jooby archetype</description>

    <properties>
        <jooby.version>1.1.3</jooby.version>
        <hikari.version>2.6.2</hikari>

        <!-- Startup class -->
        <application.class>my.app.App</application.class>
    </properties>

    <dependencies>
        <!-- Server -->
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-undertow</artifactId>
        </dependency>
        <!-- logging -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

        <!-- Tests -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-assets</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-assets-less</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-assets-clean-css</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-ftl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-guava-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-pac4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby-jdbc</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.impossibl.pgjdbc-ng/pgjdbc-ng -->
        <!--dependency>
            <groupId>com.impossibl.pgjdbc-ng</groupId>
            <artifactId>pgjdbc-ng</artifactId>
            <version>0.7</version>
        </dependency-->

        <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.1.1</version>
        </dependency>
        
        <!-- https://mvnrepository.com/artifact/org.apache.poi/poi -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.16</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.16</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <!-- Build fat jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jooby</groupId>
                <artifactId>jooby-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>assets</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

```

**Comment by Shbnv** [comment]
If i uncomment „“ — i'll get the error described above https://github.com/jooby-project/jooby/issues/836#issuecomment-315679001

**Comment by jknack** [comment]
not sure what do you mean with:

> If i uncomment „“ —

but I found a typo in: `<hikari.version>2.6.2</hikari>` it should be `<hikari.version>2.6.2</hikari.version>`

**Comment by Shbnv** [comment]
sorry.
If i uncomment 
`<!--scope>provided</scope-->`

**Comment by jknack** [comment]
probably the stork dist for windows doesn't handle process arguments (prod) but I doubt it.

try the fat jar: java -jar myapp.jar prod

**Comment by Shbnv** [comment]
Yes, i tried id and get other error:
```
$ java -jar myapp-1.0-SNAPSHOT.jar prod
ш■ы 17, 2017 5:24:48 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(Unknown Source)
        at org.jooby.assets.AssetCompiler.spath(AssetCompiler.java:798)
        at org.jooby.assets.AssetCompiler.lambda$null$10(AssetCompiler.java:668)
        at org.jooby.assets.AssetCompiler.lambda$strlist$22(AssetCompiler.java:790)
        at java.util.ArrayList.forEach(Unknown Source)
        at org.jooby.assets.AssetCompiler.strlist(AssetCompiler.java:790)
        at org.jooby.assets.AssetCompiler.lambda$fileset$16(AssetCompiler.java:668)
        at java.lang.Iterable.forEach(Unknown Source)
        at org.jooby.assets.AssetCompiler.fileset(AssetCompiler.java:663)
        at org.jooby.assets.AssetCompiler.<init>(AssetCompiler.java:297)
        at org.jooby.assets.Assets.configure(Assets.java:497)
        at org.jooby.Jooby.install(Jooby.java:3344)
        at org.jooby.Jooby.lambda$bindService$53(Jooby.java:3033)
        at org.jooby.Jooby.lambda$null$47(Jooby.java:2884)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$bootstrap$50(Jooby.java:2873)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:884)
        at org.jooby.Jooby.bootstrap(Jooby.java:2948)
        at org.jooby.Jooby.start(Jooby.java:2161)
        at org.jooby.Jooby.start(Jooby.java:2142)
        at org.jooby.Jooby.run(Jooby.java:2072)
        at my.app.App.main(App.java:68)

[2017-07-17 17:24:48,128]-[main] INFO  my.app.App - Stopped
[2017-07-17 17:24:48,137]-[main] ERROR my.app.App - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.jooby.spi.HttpHandler was bound.
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.undertow.UndertowServer.<init>(UndertowServer.java:250)
  at org.jooby.undertow.Undertow.configure(Undertow.java:220)

2) An exception was caught and reported. Message: String index out of range: 0
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:884)
        at org.jooby.Jooby.bootstrap(Jooby.java:2948)
        at org.jooby.Jooby.start(Jooby.java:2161)
        at org.jooby.Jooby.start(Jooby.java:2142)
        at org.jooby.Jooby.run(Jooby.java:2072)
        at my.app.App.main(App.java:68)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(Unknown Source)
        at org.jooby.assets.AssetCompiler.spath(AssetCompiler.java:798)
        at org.jooby.assets.AssetCompiler.lambda$null$10(AssetCompiler.java:668)
        at org.jooby.assets.AssetCompiler.lambda$strlist$22(AssetCompiler.java:790)
        at java.util.ArrayList.forEach(Unknown Source)
        at org.jooby.assets.AssetCompiler.strlist(AssetCompiler.java:790)
        at org.jooby.assets.AssetCompiler.lambda$fileset$16(AssetCompiler.java:668)
        at java.lang.Iterable.forEach(Unknown Source)
        at org.jooby.assets.AssetCompiler.fileset(AssetCompiler.java:663)
        at org.jooby.assets.AssetCompiler.<init>(AssetCompiler.java:297)
        at org.jooby.assets.Assets.configure(Assets.java:497)
        at org.jooby.Jooby.install(Jooby.java:3344)
        at org.jooby.Jooby.lambda$bindService$53(Jooby.java:3033)
        at org.jooby.Jooby.lambda$null$47(Jooby.java:2884)
        at javaslang.control.Try.run(Try.java:52)
        at org.jooby.Jooby.lambda$bootstrap$50(Jooby.java:2873)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        ... 8 common frames omitted
```

**Comment by Shbnv** [comment]
Yeah!
I found a cause of the error above: i had empty section in assets.conf:
```
assets
{
    fileset
    {
        base: 
            [
                assets/stylesheets/bs/st.less, 
                assets/javascripts/jquery-3.2.1.min.js, 
                assets/javascripts/bootstrap.min.js
            ]
        admin: []
    }

```
After i remove `admin: []` fat jar starts successfully

**Comment by jknack** [comment]
oh cool!! glad you found it! and going to fix it later.

**Comment by jknack** [comment]
And please star/follow the project please (if you like it)
