### ISSUE TITLE
LiveReload does not work with Gradle Project

### ISSUE THREAD

**Issue by JStumpp** [jooby-project/jooby#848]
With gradle the LiveReload throws the following exception:
```
C:\dev\sandbox\joobytest\my-app>gradlew joobyRun
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:joobyRun
>>> jooby:run[info|Daemon worker Thread 2]: Hotswap available on: [C:\dev\sandbox\joobytest\my-app]
>>> jooby:run[info|Daemon worker Thread 2]:   includes: [**/*.class;**/*.conf;**/*.properties;**/*.html]
>>> jooby:run[info|Daemon worker Thread 2]:   excludes: []
[2017-08-02 14:18:29,019]-[HotSwap] INFO  com.mycompany.App - Stopped
[2017-08-02 14:18:29,024]-[HotSwap] ERROR com.mycompany.App - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.Set<org.jooby.filewatcher.FileEventOptions> was bound.
  while locating java.util.Set<org.jooby.filewatcher.FileEventOptions>
    for the 4th parameter of org.jooby.filewatcher.FileMonitor.<init>(FileMonitor.java:252)
  at org.jooby.filewatcher.FileWatcher.configure(FileWatcher.java:540)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:884)
        at org.jooby.Jooby.bootstrap(Jooby.java:2948)
        at org.jooby.Jooby.start(Jooby.java:2161)
        at org.jooby.Jooby.start(Jooby.java:2142)
        at org.jooby.Jooby.run(Jooby.java:2072)
        at com.mycompany.App.main(App.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jooby.run.Main.lambda$startApp$1(Main.java:427)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
>>> jooby:run[error|HotSwap]: com.mycompany.App.start() resulted in error
java.lang.NullPointerException
        at org.jooby.run.Main.lambda$startApp$1(Main.java:432)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
Example Project:
https://github.com/JStumpp/jooby-gradle-livereload

**Comment by jaytheking** [comment]
Just looked into this for you, i could not reproduce your issue with after cloning your repo.

Output of `./gradlew -version`
```
user@Flatbread:~/Desktop/tmp/jooby-gradle-livereload (master)$ ./gradlew -version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.4.0-89-generic amd64
```

Though i did experience a file not found issue stack trace for not having a `resources` folder inside `/src/main/`.

If you have gradle installed locally on your machine reinitialize your gradle wrapper and to use latest gradle version.

**Comment by JStumpp** [comment]
Just did a clean clone again (yes, the resources-folder was missing), but after creating, the problem is the same. It is on windows. 
Output of gradlew -version
```
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Windows 10 10.0 amd64
```

**Comment by jaytheking** [comment]
Hhmmm interesting, I noticed you don't have the jooby core library in your build file. Try adding it.

Here is my build file that works in Windows as far as I know 

````
group 'com.linesmarts'
version '1.0-SNAPSHOT'
 
apply plugin: 'java'
apply plugin: 'jooby'
apply plugin: 'application'
apply plugin: "com.github.johnrengelman.shadow"
 
sourceCompatibility = 1.8
mainClassName = "com.linesmarts.App"
 
buildscript {
 
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
 
    dependencies {
        /**
         * joobyRun
         */
        classpath group: 'org.jooby', name: 'jooby-gradle-plugin', version: '1.1.3'
        classpath "com.github.jengelman.gradle.plugins:shadow:1.2.4"
    }
}
 
repositories {
    mavenCentral()
}
 
dependencies {
 
    // jooby core library
    compile group: 'org.jooby', name: 'jooby', version: '1.1.3'
 
    // use jetty for web server as netty does not compile properly
    compile group: 'org.jooby', name: 'jooby-jetty', version: '1.1.3'
 
    // database driver for postgresql
    compile group: 'org.postgresql', name: 'postgresql', version: '42.1.1'
 
    // javascript serialization
    compile group: 'org.jooby', name: 'jooby-gson', version: '1.1.3'
 
    // fancy error pages
    compile group: 'org.jooby', name: 'jooby-whoops', version: '1.1.3'
 
    // https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink
    compile group: 'org.eclipse.persistence', name: 'eclipselink', version: '2.5.1'
 
    // http://jdbi.org/getting_jdbi/ - cant decide on eclipse or pure jdbi
    compile group: 'org.jdbi', name:'jdbi', version: '2.78'
 
    testCompile group: 'junit', name: 'junit', version: '4.12'
 
    // Eclipselink JPA ORM library
    compile 'org.eclipse.persistence:eclipselink:2.5.0'
 
    testCompile 'io.rest-assured:rest-assured:3.0.3'
}
 
// jooby run command configuration
joobyRun {
    mainClassName = 'com.linesmarts.App'
    compiler = 'on'
    includes = ['**/*.class', '**/*.conf', '**/*.properties']
    excludes = []
    logLevel = 'debug'
}
}
````

**Comment by JStumpp** [comment]
I tried adding it, still the same problem, but it is a runtime dependency anyway:
```
+--- org.jooby:jooby-livereload:1.1.3
|    \--- org.jooby:jooby-filewatcher:1.1.3
|         \--- org.jooby:jooby:1.1.3
```
@jaytheking in your gradle file the livereload dependency is missing and the problem only appears if 
```
use(new LiveReload());
```
is in the App.java

**Comment by jaytheking** [comment]
aahhh i see, ok sorry i missed that detail. I'll add that as a dependency in my gradle and in the App() and see what happens. Ive only been using jooby for REST api part and havent looked at the asset reloading part.

**Comment by JStumpp** [comment]
@jaytheking Thanks a lot for the help.
Unfortuately adding the public folder did not work for me. Did I miss something? Here is the updated app:
https://github.com/JStumpp/jooby-gradle-livereload

**Comment by jaytheking** [comment]
@JStumpp Hey i re-cloned your repo and tried the changes. The only issue i got was the missing resources folder in `src/main/`. I dont have a windows machine to spin up and try the build against windows but on ubuntu 16.04 everything works fine for me now.

if you really want to page to reload itself ive used `setTimeout(function(){window.location.reload();}, 2000)` in a script tag. Its not ideal but works. If i get a chance to use a windows machine ill try pulling your repo and running some tests again.

**Comment by JStumpp** [comment]
Could be a Windows problem, the problem persists no matter which directories exist or do not exist.

**Comment by jknack** [comment]
Can you try with 1.2.1?

**Comment by JStumpp** [comment]
Getting a HotSwap error now with version 1.2.1:
```
C:\dev\sandbox\jooby-gradle-livereload>gradlew joobyRun
:compileJava
:processResources NO-SOURCE
:classes
:joobyRun
>>> jooby:run[info|Daemon worker]: Hotswap available on: [C:\dev\sandbox\jooby-gradle-livereload]
>>> jooby:run[info|Daemon worker]:   includes: [**/*.class;**/*.conf;**/*.properties]
>>> jooby:run[info|Daemon worker]:   excludes: []
>>> jooby:run[error|HotSwap]: com.mycompany.App.start() resulted in error
java.lang.LinkageError: Failed to link org/jooby/internal/run__/JoobyRef (Module "my-app:main" from AppModuleLoader@3dd51c6c for finders [])
        at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437)
        at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
        at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
        at org.jboss.modules.Module.loadModuleClass(Module.java:560)
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
        at org.jooby.run.Main.lambda$startApp$1(Main.java:419)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javaslang/control/Try$CheckedConsumer
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
        at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: javaslang.control.Try$CheckedConsumer from [Module "my-app:main" from AppModuleLoader@3dd51c6c for finders []]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
        ... 18 more
```

**Comment by jknack** [comment]
Something else is going on here:

> Caused by: java.lang.NoClassDefFoundError: javaslang/control/Try$CheckedConsumer

Javaslang was removed in 1.2.0.

Show me your build.gradle file please

**Comment by JStumpp** [comment]
Sure, the project is update here: https://github.com/JStumpp/jooby-gradle-livereload

**Comment by jknack** [comment]
I sent a PR, merge and try again

**Comment by JStumpp** [comment]
Thanks, i missed the plugin. Now the old error is back:
```
C:\dev\sandbox\jooby-gradle-livereload>gradlew clean joobyRun
Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
:clean
:compileJava
:processResources
:classes
:joobyRun
>>> jooby:run[info|Daemon worker]: Hotswap available on: [C:\dev\sandbox\jooby-gradle-livereload]
>>> jooby:run[info|Daemon worker]:   includes: [**/*.class;**/*.conf;**/*.properties]
>>> jooby:run[info|Daemon worker]:   excludes: []
[2017-11-02 13:01:59,780]-[Hotswap] INFO  com.mycompany.App - Stopped
[2017-11-02 13:01:59,787]-[Hotswap] ERROR com.mycompany.App - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.Set<org.jooby.filewatcher.FileEventOptions> was bound.
  while locating java.util.Set<org.jooby.filewatcher.FileEventOptions>
    for the 4th parameter of org.jooby.filewatcher.FileMonitor.<init>(FileMonitor.java:252)
  at org.jooby.filewatcher.FileWatcher.configure(FileWatcher.java:536)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.jooby.Jooby.lambda$new$0(Jooby.java:882)
        at org.jooby.Jooby.bootstrap(Jooby.java:2974)
        at org.jooby.Jooby.start(Jooby.java:2176)
        at org.jooby.Jooby.start(Jooby.java:2157)
        at org.jooby.Jooby.run(Jooby.java:2088)
        at com.mycompany.App.main(App.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jooby.run.Main.lambda$startApp$3(Main.java:439)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
>>> jooby:run[error|Hotswap]: com.mycompany.App.start() resulted in error
java.lang.NullPointerException
        at org.jooby.run.Main.lambda$startApp$3(Main.java:444)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by jknack** [comment]
Give me the Windows OS version you try this

**Comment by JStumpp** [comment]
Windows 10

**Comment by jknack** [comment]
Found the issue, but was almost impossible to test this in Windows :(

For some odd reason... Gradle daemon doesn't set the working directory to `jooby-gradle-livereload`... so file watcher try to look for directories inside the `.gradle/daemon/3.5`

does it sounds familiar to you?
