### ISSUE TITLE
Could not find javaslang/API

### ISSUE THREAD

**Issue by mcjp78** [jooby-project/jooby#929]
Hi,
I recently stated getting this error with Kooby, Jooby, and using Morphia.
```2017-10-27 16:34:51,855]-[main] ERROR org.jooby.Kooby - An error occurred while starting the application:
java.lang.NoClassDefFoundError: javaslang/API
	at org.jooby.internal.netty.NettyServer.lambda$configure$5(NettyServer.java:347)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.jooby.internal.netty.NettyServer.configure(NettyServer.java:341)
	at org.jooby.internal.netty.NettyServer.bootstrap(NettyServer.java:307)
	at org.jooby.internal.netty.NettyServer.start(NettyServer.java:288)
	at org.jooby.Jooby.start(Jooby.java:2205)
	at org.jooby.Jooby.start(Jooby.java:2147)
	at org.jooby.Jooby.run(Jooby.java:2078)
	at org.jooby.JoobyKt.run(Jooby.kt:280)
	at today.accounts.server.Main.main(Main.kt:28)
Caused by: java.lang.ClassNotFoundException: javaslang.API
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 common frames omitted```

**Comment by mcjp78** [comment]
Fixed by updating
