### ISSUE TITLE
Pebble template files not found when running integration test

### ISSUE THREAD

**Issue by mcgaw** [jooby-project/jooby#936]
Hi, I've attached a fresh project, created using the Maven archetype on the getting started page. Only change is to add the Pebble dependency _and move the route handler to a controller style class_. The basic integration test fails with:
```
Caused by: java.io.FileNotFoundException: Template not found: /templates/hello in [pebble]
	at org.jooby.internal.AbstractRendererContext.render(AbstractRendererContext.java:277)
	at org.jooby.internal.ResponseImpl.send(ResponseImpl.java:559)
	at org.jooby.Response.send(Response.java:640)
	at org.jooby.internal.mvc.MvcHandler.handle(MvcHandler.java:258)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2475)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)

```
Cheers.
[jooby-pebble.zip](https://github.com/jooby-project/jooby/files/1433262/jooby-pebble.zip)

OS: XUbuntu
Java: 1.8.0_131

**Comment by mcgaw** [comment]
Thanks dude.
