### ISSUE TITLE
Mvc websocket fails to detect generic type

### ISSUE THREAD

**Issue by jkbbwr** [jooby-project/jooby#951]
```
package x

import org.jooby.*
import org.jooby.mvc.Consumes
import org.jooby.mvc.Path
import org.jooby.mvc.Produces
import java.util.*


@Path("/ws")
@Produces("application/text")
@Consumes("application/text")
class Handler : WebSocket.Handler<String> {
    override fun onClose(status: WebSocket.CloseStatus) {
        println(status)
    }

    override fun onMessage(message: String) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun onOpen(req: Request, ws: WebSocket) {
        TODO("magic")
    }

    override fun onError(err: Throwable) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

}

fun main(args: Array<String>) {
    run(*args) {
        ws(Handler::class.java)
    }
}
```

Creates the following exception

```
/usr/lib/jvm/default-runtime/bin/java -javaagent:/home/jakob/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/173.3727.78/lib/idea_rt.jar=38041:/home/jakob/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/173.3727.78/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/default-runtime/jre/lib/charsets.jar:/usr/lib/jvm/default-runtime/jre/lib/deploy.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/dnsns.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/jaccess.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/localedata.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/nashorn.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/sunec.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/default-runtime/jre/lib/ext/zipfs.jar:/usr/lib/jvm/default-runtime/jre/lib/javaws.jar:/usr/lib/jvm/default-runtime/jre/lib/jce.jar:/usr/lib/jvm/default-runtime/jre/lib/jfr.jar:/usr/lib/jvm/default-runtime/jre/lib/jfxswt.jar:/usr/lib/jvm/default-runtime/jre/lib/jsse.jar:/usr/lib/jvm/default-runtime/jre/lib/management-agent.jar:/usr/lib/jvm/default-runtime/jre/lib/plugin.jar:/usr/lib/jvm/default-runtime/jre/lib/resources.jar:/usr/lib/jvm/default-runtime/jre/lib/rt.jar:/home/jakob/projects/personal/coffeehouse/out/production/classes:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.2.0-rc-39/6c4ebc8f9f0a416e7d91f077a46733ec1c075b28/kotlin-stdlib-jdk8-1.2.0-rc-39.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jooby/jooby-lang-kotlin/1.2.3/186694aa7c97aa4f77c9c4b4c507090d87a55383/jooby-lang-kotlin-1.2.3.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jooby/jooby-undertow/1.2.3/637d095b0a3f4afaf1018dc512583c4ce43a7cd2/jooby-undertow-1.2.3.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jooby/jooby/1.2.3/798d4edde6bf5b362bff4ad68f348ca506b3f20c/jooby-1.2.3.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.xerial/sqlite-jdbc/3.21.0/347e4d1d3e1dff66d389354af8f0021e62344584/sqlite-jdbc-3.21.0.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/io.requery/requery-kotlin/1.4.1/8bc21705a2816949de76d316fa1a9e3a324dd20c/requery-kotlin-1.4.1.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/io.requery/requery/1.4.1/aca696541886ec39e6f2b0e41f4f17a631719c43/requery-1.4.1.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.0-rc-39/ae42bc454751b52eaa40ca34316c4b7e407e6062/kotlin-stdlib-jdk7-1.2.0-rc-39.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre8/1.1.51/cc8e639ff087472268912159cd66c01f2765c657/kotlin-stdlib-jre8-1.1.51.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.1.51/8b5933578dc55f32cfc1a25f1db6371e4161fb8f/kotlin-stdlib-jre7-1.1.51.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.0-rc-39/f460d8579fbe883d1dedaa52b226c8ab48b8a780/kotlin-stdlib-1.2.0-rc-39.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/com.typesafe/config/1.3.1/2cf7a6cc79732e3bdf1647d7404279900ca63eb0/config-1.3.1.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jooby/funzy/0.1.0/39d23c2da957d578352e74bd65540d12bd0caf20/funzy-0.1.0.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/com.google.inject.extensions/guice-multibindings/4.1.0/3b27257997ac51b0f8d19676f1ea170427e86d51/guice-multibindings-4.1.0.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/eeb69005da379a10071aa4948c48d89250febb07/guice-4.1.0.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/21.0/3a3d111be1be1b745edfa7d91678a12d7ed38709/guava-21.0.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/io.undertow/undertow-core/1.4.20.Final/59659eb4f48e218beef447477f638bf81b36933d/undertow-core-1.4.20.Final.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.2.3/864344400c3d4d92dfeb0a305dc87d953677c03c/logback-core-1.2.3.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jboss.logging/jboss-logging/3.2.1.Final/fedf11b3d4665a434b554a5891fe7f208f029f45/jboss-logging-3.2.1.Final.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jboss.xnio/xnio-nio/3.3.8.Final/8dafaf230666e526c53e544ab6a9d6ecfcbab4ee/xnio-nio-3.3.8.Final.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jboss.xnio/xnio-api/3.3.8.Final/7942ba8330c91a12006c912e040d25a77a58c525/xnio-api-3.3.8.Final.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/aopalliance/aopalliance/1.0/235ba8b489512805ac13a8f9ea77a1ca5ebe3e8/aopalliance-1.0.jar:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar io.codehop.coffeehouse.MainKt
19:48:25.288 [main] DEBUG org.jooby.Kooby - config tree:
└── merge of system properties
 └── org/jooby/spi/server.conf @ jar:file:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jooby/jooby-undertow/1.2.3/637d095b0a3f4afaf1018dc512583c4ce43a7cd2/jooby-undertow-1.2.3.jar!/org/jooby/spi/server.conf
  └── org/jooby/mime.properties @ jar:file:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jooby/jooby/1.2.3/798d4edde6bf5b362bff4ad68f348ca506b3f20c/jooby-1.2.3.jar!/org/jooby/mime.properties
   └── org/jooby/jooby.conf @ jar:file:/home/jakob/.gradle/caches/modules-2/files-2.1/org.jooby/jooby/1.2.3/798d4edde6bf5b362bff4ad68f348ca506b3f20c/jooby-1.2.3.jar!/org/jooby/jooby.conf: 1

19:48:25.309 [main] DEBUG org.jooby.spi.Server - undertow.bufferSize(16384)
19:48:25.310 [main] DEBUG org.jooby.spi.Server - undertow.workerThreads(64)
19:48:25.313 [main] DEBUG org.jooby.spi.Server - server.ALLOW_EQUALS_IN_COOKIE_VALUE(true)
19:48:25.313 [main] DEBUG org.jooby.spi.Server - server.DECODE_URL(true)
19:48:25.313 [main] DEBUG org.jooby.spi.Server - server.URL_CHARSET(UTF-8)
19:48:25.314 [main] DEBUG org.jooby.spi.Server - server.MAX_PARAMETERS(1000)
19:48:25.314 [main] DEBUG org.jooby.spi.Server - server.IDLE_TIMEOUT(0)
19:48:25.314 [main] DEBUG org.jooby.spi.Server - server.ALWAYS_SET_KEEP_ALIVE(true)
19:48:25.314 [main] DEBUG org.jooby.spi.Server - server.MAX_HEADERS(200)
19:48:25.314 [main] DEBUG org.jooby.spi.Server - server.MAX_HEADER_SIZE(8192)
19:48:25.314 [main] DEBUG org.jooby.spi.Server - server.MAX_ENTITY_SIZE(204800)
19:48:25.314 [main] DEBUG org.jooby.spi.Server - server.MAX_COOKIES(200)
19:48:25.316 [main] DEBUG org.jooby.spi.Server - worker.WORKER_NAME(utow)
19:48:25.317 [main] DEBUG org.jooby.spi.Server - socket.BACKLOG(1024)
19:48:25.327 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
19:48:25.329 [main] DEBUG io.undertow - starting undertow server io.undertow.Undertow@428640fa
19:48:25.334 [main] INFO org.xnio - XNIO version 3.3.8.Final
19:48:25.344 [main] INFO org.xnio.nio - XNIO NIO Implementation Version 3.3.8.Final
19:48:25.405 [utow I/O-1] DEBUG org.xnio.nio - Started channel thread 'utow I/O-1', selector sun.nio.ch.EPollSelectorImpl@67bdd69b
19:48:25.405 [utow I/O-2] DEBUG org.xnio.nio - Started channel thread 'utow I/O-2', selector sun.nio.ch.EPollSelectorImpl@3bf676c0
19:48:25.406 [utow I/O-3] DEBUG org.xnio.nio - Started channel thread 'utow I/O-3', selector sun.nio.ch.EPollSelectorImpl@5efc1271
19:48:25.407 [utow I/O-4] DEBUG org.xnio.nio - Started channel thread 'utow I/O-4', selector sun.nio.ch.EPollSelectorImpl@510a134e
19:48:25.408 [utow I/O-5] DEBUG org.xnio.nio - Started channel thread 'utow I/O-5', selector sun.nio.ch.EPollSelectorImpl@536e6e57
19:48:25.408 [utow I/O-6] DEBUG org.xnio.nio - Started channel thread 'utow I/O-6', selector sun.nio.ch.EPollSelectorImpl@2df32bae
19:48:25.408 [utow I/O-7] DEBUG org.xnio.nio - Started channel thread 'utow I/O-7', selector sun.nio.ch.EPollSelectorImpl@6d7494a9
19:48:25.408 [utow I/O-8] DEBUG org.xnio.nio - Started channel thread 'utow I/O-8', selector sun.nio.ch.EPollSelectorImpl@3f1ec1f3
19:48:25.409 [utow Accept] DEBUG org.xnio.nio - Started channel thread 'utow Accept', selector sun.nio.ch.EPollSelectorImpl@71be1d30
19:48:25.409 [main] DEBUG io.undertow - Configuring listener with protocol HTTP for interface 0.0.0.0 and port 8080
19:48:25.444 [main] INFO org.jooby.Kooby - [dev@undertow]: Server started in 681ms

  WS /ws    [application/text]     [application/text]

listening on:
  http://localhost:8080/

19:48:27.600 [utow task-1] DEBUG io.undertow.websockets.core.request - Attempting websocket handshake with io.undertow.websockets.core.protocol.version13.Hybi13Handshake@300c9dcd on HttpServerExchange{ GET /ws request {Connection=[Upgrade], Sec-WebSocket-Version=[13], Sec-WebSocket-Key=[nwWWPTTwS0rhGiSSV+VOUw==], Upgrade=[websocket], Origin=[http://127.0.0.1:8080], Host=[127.0.0.1:8080]} response {Content-Length=[0]}}
19:48:27.601 [utow task-1] DEBUG io.undertow.request - Upgrading request HttpServerExchange{ GET /ws request {Connection=[Upgrade], Sec-WebSocket-Version=[13], Sec-WebSocket-Key=[nwWWPTTwS0rhGiSSV+VOUw==], Upgrade=[websocket], Origin=[http://127.0.0.1:8080], Host=[127.0.0.1:8080]} response {Content-Length=[0]}}
19:48:27.641 [utow task-1] ERROR org.jooby.WebSocket - execution of WS/ws resulted in exception
java.lang.IllegalArgumentException: Can't extract message type from: io.codehop.coffeehouse.chat.Handler
	at org.jooby.internal.mvc.MvcWebSocket.lambda$messageType$4(MvcWebSocket.java:287)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.jooby.internal.mvc.MvcWebSocket.messageType(MvcWebSocket.java:286)
	at org.jooby.internal.mvc.MvcWebSocket.<init>(MvcWebSocket.java:228)
	at org.jooby.internal.mvc.MvcWebSocket.lambda$newWebSocket$1(MvcWebSocket.java:233)
	at org.jooby.internal.WebSocketImpl.connect(WebSocketImpl.java:417)
	at org.jooby.internal.HttpHandlerImpl.lambda$handle$4(HttpHandlerImpl.java:484)
	at org.jooby.internal.undertow.UndertowWebSocket.connect(UndertowWebSocket.java:286)
	at org.jooby.internal.undertow.UndertowResponse.lambda$end$0(UndertowResponse.java:320)
	at io.undertow.websockets.WebSocketProtocolHandshakeHandler$1.handleUpgrade(WebSocketProtocolHandshakeHandler.java:198)
	at io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(HttpReadListener.java:383)
	at io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(HttpServerConnection.java:232)
	at io.undertow.server.HttpServerExchange$ExchangeCompleteNextListener.proceed(HttpServerExchange.java:1858)
	at io.undertow.server.handlers.GracefulShutdownHandler$GracefulShutdownListener.exchangeEvent(GracefulShutdownHandler.java:182)
	at io.undertow.server.HttpServerExchange.invokeExchangeCompleteListeners(HttpServerExchange.java:1258)
	at io.undertow.server.HttpServerExchange.terminateResponse(HttpServerExchange.java:1538)
	at io.undertow.server.Connectors.terminateResponse(Connectors.java:143)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:197)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:195)
	at io.undertow.conduits.HeadStreamSinkConduit.exitFlush(HeadStreamSinkConduit.java:192)
	at io.undertow.conduits.HeadStreamSinkConduit.flush(HeadStreamSinkConduit.java:133)
	at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
	at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119)
	at io.undertow.server.HttpServerExchange.closeAndFlushResponse(HttpServerExchange.java:1694)
	at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1672)
	at io.undertow.websockets.spi.AsyncWebSocketHttpServerExchange.endExchange(AsyncWebSocketHttpServerExchange.java:213)
	at io.undertow.websockets.core.protocol.Handshake.upgradeChannel(Handshake.java:131)
	at io.undertow.websockets.core.protocol.Handshake.performUpgrade(Handshake.java:124)
	at io.undertow.websockets.core.protocol.Handshake.performUpgrade(Handshake.java:152)
	at io.undertow.websockets.core.protocol.version13.Hybi13Handshake.handshakeInternal(Hybi13Handshake.java:66)
	at io.undertow.websockets.core.protocol.Handshake.handshake(Handshake.java:102)
	at io.undertow.websockets.WebSocketProtocolHandshakeHandler.handleRequest(WebSocketProtocolHandshakeHandler.java:204)
	at org.jooby.internal.undertow.UndertowResponse.end(UndertowResponse.java:321)
	at org.jooby.internal.ResponseImpl.end(ResponseImpl.java:483)
	at org.jooby.internal.ResponseImpl.done(ResponseImpl.java:453)
	at org.jooby.internal.HttpHandlerImpl.done(HttpHandlerImpl.java:518)
	at org.jooby.internal.HttpHandlerImpl.cleanup(HttpHandlerImpl.java:565)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:504)
	at org.jooby.internal.undertow.UndertowHandler.handleRequest(UndertowHandler.java:252)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jkbbwr** [comment]
Way to introspect to find the type
```
ParameterizedTypeImpl types = (ParameterizedTypeImpl) Handler.class.getGenericInterfaces()[0];
System.out.println(types.getActualTypeArguments()[0]);
```
Obviously don't rely on indexing for generic interfaces

**Comment by jkbbwr** [comment]
Btw, work around for anyone facing this issue. 

Implement each interface separately. 

```
class Handler : WebSocket.OnMessage<String>, WebSocket.OnError /* ... */
```
