### ISSUE TITLE
jooby:run fails with Java 8 161+

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#990]
```
javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory not found
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:200)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
        at jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:235)
        at jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:78)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:319)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:254)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:480)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:487)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:357)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:292)
        at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.<init>(XMLSchemaFactory.java:97)
        at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:232)
        at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:146)
        at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:213)
        at __redirected.__SchemaFactory.<clinit>(__SchemaFactory.java:65)
        at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:80)
        at org.jboss.modules.Module$1.run(Module.java:129)
        at org.jboss.modules.Module$1.run(Module.java:116)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.jboss.modules.Module.<clinit>(Module.java:116)
```

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by jknack** [comment]
Workaround is to upgrade jboss-modules for jooby:run:

```xml
<build>
    <plugins>
      <plugin>
        <groupId>org.jooby</groupId>
        <artifactId>jooby-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.jboss.modules</groupId>
            <artifactId>jboss-modules</artifactId>
            <version>1.7.0.Beta3</version>
          </dependency>
        </dependencies>
      </plugin>
  </plugins>
</build>
```
